In [23]:
#2021.08.18. WED
#Team_밥믈리에

#00. 패키지 호출
import pandas as pd 
import numpy as np 
import re 
import itertools
import csv
import konlpy
from konlpy.tag import Okt
from collections import Counter

#00-1. 사전변수 정의하기.
CULTIVAR = '고시히카리'

STOPWORD = []
with open('../data/stop_word_list.csv', 'r') as file :
    reader = csv.reader(file)
    for row in reader                                :
        STOPWORD.append(row)
STOPWORD = STOPWORD[0]

In [24]:
#01. 데이터셋 결합하기. 
#(1) 쿠팡 데이터셋 불러오기. 
review_data_01 = pd.read_excel(f'../data/Coupang/{CULTIVAR}.xlsx')

#(2) 쿠팡 데이터셋 확인하기.
review_data_01

,name,kg,delivery,rate,date,review,rice
0,이화에월백하고 고시히까리 3kg 강화섬쌀 ES강화농산 강화쌀 고시히까리 강화섬쌀 강...,3kg,무료배송,5,2021.06.06,NaN,NaN
1,대한농산 보약같은 고시히카리 쌀,5kg,무료배송,5,2021.08.14,NaN,NaN
2,2020년햅쌀/슈퍼오닝/특등급쌀/고시히카리/쌀20Kg/쌀10Kg/쌀4Kg/안중농협쌀...,4kg,무료배송,5,2021.07.21,NaN,NaN
3,2020년햅쌀/슈퍼오닝/특등급쌀/고시히카리/쌀20Kg/쌀10Kg/쌀4Kg/안중농협쌀...,5kg,무료배송,5,2021.06.24,NaN,표면 매끈해요\n도정일 최근이에요\n쌀알 보통이에요
4,2020년햅쌀/슈퍼오닝/특등급쌀/고시히카리/쌀20Kg/쌀10Kg/쌀4Kg/안중농협쌀...,6kg,무료배송,5,2021.05.16,NaN,NaN
...,...,...,...,...,...,...,...
13078,한가위쌀 김포 고시히카리쌀 백미,20kg,무료배송,4,2016.01.19,NaN,NaN
13079,한가위쌀 김포 고시히카리쌀 백미,20kg,무료배송,4,2016.01.13,밥이 맛있네요...윤기도 좔좔~~~두번째 구매합니다.번창하십시요,NaN
13080,한가위쌀 김포 고시히카리쌀 백미,20kg,무료배송,4,2015.12.19,빠른 배송 너무 좋아요,NaN
13081,한가위쌀 김포 고시히카리쌀 백미,20kg,무료배송,5,2015.11.17,맛있는 김포 고시히카리쌀 잘 받았습니다♥\n배송도 빠르고~아주 만족!,NaN
13082,한가위쌀 김포 고시히카리쌀 백미,20kg,무료배송,5,2015.11.15,처음 구입해봤는데 정말쌀알이 맑고 부스러진것도 거의없이 좋아요\n밥을했는데 밥알이 ...,NaN

In [25]:
#(3) 롯데 데이터셋 불러오기.
review_data_02 = pd.read_excel('../data/crawling_LotteON.xlsx', sheet_name = CULTIVAR)

#(4) 롯데 데이터셋 확인하기. 
review_data_02

,product_name,cultivar,review_01,review_02,score,date
0,엘그로 완전미 평택 고시히카리 (5KG),고시히카리,재구매,NO_VALUE,5,1시간 전
1,엘그로 완전미 평택 고시히카리 (5KG),고시히카리,온라인 구입시 품절이 잘되요,NO_VALUE,5,8시간 전
2,엘그로 완전미 평택 고시히카리 (5KG),고시히카리,고시하카리 소량판매 좋아요,NO_VALUE,5,2021.08.17
3,엘그로 완전미 평택 고시히카리 (5KG),고시히카리,잘 받았습니다~~~,NO_VALUE,5,2021.08.16
4,엘그로 완전미 평택 고시히카리 (5KG),고시히카리,한달사용기,NO_VALUE,5,2021.08.14
...,...,...,...,...,...,...
1318,[2020년산] 고시히카리 10kg,고시히카리,당일도정은 아니고 8월6일 도정된거네요. 기존에 먹던게 있는데 요즘 안나와서ㅜ일단 ...,“보통이에요”,5,2020.08.19
1319,윤기가 흐르는 고시히카리쌀 5kg 안성양성농협,고시히카리,고시히까리 인데 별차이모르겠어요\n그저그래요,“보통이에요”,4,2020.07.04
1320,[온세일]2020년 햅쌀 백미/고시히카리/추청쌀 10kg 모음전,고시히카리,마트판매가보다 저렴하게 구입할수 있어 우선 구매했습니다.\n아직 사용전이니 나중에 ...,“재구매의사 있어요”,4,2020.07.13
1321,[2020년산] 고시히카리 20kg,고시히카리,물품 잘 받았습니다. 감사합니다.^^,“재구매의사 있어요”,5,2020.06.15
1322,고시히카리 14kg (7kg*2포) / 무료배송,고시히카리,일요일구매 화요일오전 배송받았어요.\n(CJ대한통운)\n항상먹는 쌀이예요. 씨눈 적...,“꼼꼼해요”,5,2019.10.01

In [26]:
#(5) 데이터셋 취합하기. 
review_data = pd.DataFrame(map(str, review_data_01['review'].append(review_data_02['review_01'])))

#(6) 취합 데이터셋 확인하기.
len(review_data), type(review_data)

(14406, pandas.core.frame.DataFrame)

In [27]:
#02. 데이터셋 전처리하기. 
#(1) 결측값 제거하기. 
review_data[review_data[0]=='nan'] = np.nan
review_data = review_data.dropna(axis=0)

#(3) 리스트로 변환하기. 
review_data = review_data[0].values.tolist()

#(4) 데이터셋 구조 확인하기. 
review_data

['맛있습니다\n맛있습니다 잘먹고있어요',
 '아주맛있다까진아니고 괜찮은편입니다',
 '밥맛이 진짜 조아요~\n밥맛이 진짜 조으네요~',
 '배송 겁내 빠름',
 '밥맛이 정말 좋아요.\n아쉬운 것은 혈당 관리 때문에 잡곡밥을 먹어야 해서...',
 '좋아요 ㅎㅎ\n잘 먹을께요',
 '밥할 때 냄새가 나고 밥맛이 텁텁하여 썩 좋은 느낌은 아니었습니다',
 '바구미 한마리가 기어다니는걸 보고 실망',
 '도정일이 6월이더라고요ㅜㅠ\n쌀이 하얗지 않고 냄새도 좀 나요ㅠㅠ',
 '아이 이유식하려고 샀어요~\n쌀 상태 좋습니다!',
 '굿굿\n항상 맛잇게 먹고있어요',
 '평택슈퍼오닝알아주는쌀이라주문함',
 '밥냄새도 너무 좋고 맛있어요',
 '쌀 괜찮아요 밥맛도 맛있어요!',
 '걱정안해도 되네요 좋아요\n품질좋아요.',
 '맛있음\n믿고먹는 평택쌀',
 '맛있어요. 재구매의사 있습니다.',
 '물건이 안왔는데 왜 배송완료죠??',
 '전 이쌀구매해먹은지 2년 넘엇어요 밥맛도 최고 윤기도짱',
 '재구매 하려고요~',
 '난 고시히카리만 먹는데 어느 순간 매장에 산거랑 인터넷에 산거랑 다른다는 생각이 많이듬.\n인터넷에 산 고시히카리 제대로 된것 못봤슴.\n이것도 별로네요.밥 맛이.',
 '최애 쌀입니다',
 '가장맛있는쌀',
 '진짜맛있는 쌀입니다',
 '맛있어요',
 '맛 있네요.. 담에 또 구매 할께요',
 '햅쌀이라는데 재고 느낌',
 '저는 작년부터 이 쌀만 먹는데 쿠팡에 있길래 쿠팡을 통해서도 두번째 구매입니다\n주문받고 도정해주셔서 기간은 4-5일 걸리는데 그래도 쌀이 너무 좋아요\n깨끗하고 밥도 참 이쁘게 고슬고슬 됩니다 다른 쌀 못 먹겠더라구요\n배송기간이 있어서 잠시 4키로짜리 좋다는 걸로 사서 먹으면서 기다렸는데 별로.. 이*쌀 강*섬쌀 등등 다 먹어봤는데 이게 최고에요~\n그래서 떨어지기 며칠전 미리 주문해놓습니당',
 '평택살았을때 맛이 생각나서 시켰는데 최악이네요ㅠㅠ',
 '맛있어요',
 '찰지고 맛있어요 만족합니다 ^^~~',
 '맛나요~ 완전 맛나요~~\n꾸준히 주문해서 먹었는데 한번은 가격이 너무 비싸져서 다른 쌀 먹어봤는데 슈퍼오닝이 제 입맛을 버릇없게 만들었네요.. 다른쌀은 찰지고 꼬수운 맛이 덜해요..\n한번 맛없다 느끼니 진짜 밥 부지런히 지어먹는데도 왜 이리 닳지 않고 오래 먹는지...ㅠ\n겨우 다 먹고 다시 슈퍼오닝으로 밥 짓는데 이제 세상 맛난 밥 먹고 있네요\n꼬숩고 찰지고... 거기다 수확한지 한참 됐는데도 도정을 몇일 전 바로해서 보내주니 수분감이 많아서(어쩜 품종 때문일지도...) 밥할때 다른 쌀에 비해 물을 살짝 적게 잡아도 매우 찰지고 촉촉해요~~\n예전엔 쌀을 대충 사서 먹었는데 맛난 쌀에 입맛이 길들여지니 좋은점은 반찬에 덜 집중해도 된다는거.. 나쁜 점우 다른쌀은 먹기 겁난다는거..\n요정도네요..\n어쨌든 앞으로 한참 동안은 요것만 먹을듯해요 가격만 계속 요정도로 유지 해준다면요~~~ 여러번 주문해 먹어봤지만 배송 상태도 항상 괜찮았어요\n비닐팩에 배송 되다 첨으로 박스에 왔던데 다행히 배송 상태 양호 했어요',
 '항상 먹는 거라 리뷰라 필요 옶어요',
 '누가 슈퍼오닝만 먹는다고해서 그게뭔지 찾아서 샀거든요\n근데 쌀씻으며 보니 때깔부터 다르더니만\n밥맛 넘좋네요!\n오늘 남편이랑 타마고스시 해먹었는데 진짜 밖에서먹는 초밥맛이었어요.\n도정도 7월에한거고 싱싱하달까?\n다먹고 또사러올게요. 기대이상이군요.',
 '재구매했어요',
 '밥맛이 좋음',
 '차지고 맛있네요\n맛있네요 완죤',
 '함께 일하는 언니가 추천해서 이쌀을 샀는데 ~~안좋네요 도정한지도 오래된것같고 밥맛도 별로고요~다시는 사먹지 말아야겠네요',
 '썩 좋은지는 모르겠어요',
 '아주 굿\n아주 맛있어요\n문의도 친절하게 해주시고요\n여기서만 시켜먹어요~~',
 '가격에 비해서 만족해요~ 마트에서 이보다 더 비싼가격으로 싼 쌀도 안좋았는데 윤기 있고 밥맛도 좋아요~^^',
 '쌀이 깨끗해보이고 밥 맛이 좋습니다.\n쌀이 좋아요',
 '맛있어요..두번째 구매했는데 밥맛이 좋아요..',
 '이 판매업자의 모든 상품은 시중가보다 엄청 비싸요^^~\n와~, 완전히 속았어요.\n2020년 햅쌀 송탄농협 슈퍼오닝 고시히카리,4kg,1개\n믿어지나요? 48200원, 4kg에 48200원, 혹 가격 오기 기재까 아닐까 문의했더니 갓 도정한 쌀이고, 같은 제품이라도 가격차이가 있다고 쿠팡측에서 확인했다고 상담원 문자옴, 판매자의 전화번호 071-7424-6536 이번호는 신호 가자마자 끊어지고 끊어지고..,010전화인 줄 알았는데 070으로 사작하는 판매업자(디엘컴퍼니샵), 판매업자 상품을 보니 농산물뿐 아니라 공산품도 와우, 어떤거는 따블이네요, 8k쌀이면 96400원, 20kg이면 241000원, 완전 속았어요. 어째 이런 사람을 정상적인 판매업자로 등록시켜 주었는지, 주의해서 가격이나 중량을 체크하지 못한 제가 밥이였였나요?. 와 기분 참, 어째 이런 사람을,,코로나 펜데믹 세상 별사람이 다있군.\n\n판매업자의 또다른 상품 https://store.coupang.com/vp/vendors/A00307116/products?vendorName=%EB%94%94%EC%97%98%EC%BB%B4%ED%8D%BC%EB%8B%88&productId=128902742&outboundShippingPlaceId=\n\n도시락 싸들고 이 판매업자 쿠팡에서 퇴출활동 하고 싶은데..',
 '10 키로가 부담스러운 가족에겐\n\n적당한 4키로 입니다.\n\n밀폐용기 5리터 에 쏙들어가서 2달먹으면 딱 알맞아요.\n\n밥맛도 찰지고 요즘 쿠팡에서 산 쌀들 왠만하면 다 맛있고\n\n괜찮더라구요.',
 '맛있어요',
 '고시힠카리 젤 마시써!\n쫀득쫀득 윤기 좌르르 -',
 '한번시켜서 먹어보구 재구입햇어요\n쿠팡서 다른데도시켜서 먹어봣는데\n여기쌀이제일 나은듯해요 밥맛좋아요',
 '휼륭해요',
 '좋은 쌀입니다.\n개인적으로 안중고시히까리가 최고에요.\n그 다음이 평택입니다.\n맛있습니다.\n\n도정일이 올해 4월이에요',
 '박스가 너무커서 다 뜯어져서왔네요 ㅠ',
 '윤기나는 맛있는밥 매일 잘먹고 있네요~~',
 '맛있었겠죠\n엄빠는 브랜드, 품종 안 따지고 그냥 단일 품종이면 오케이지만\n애기 먹는 쌀은 고시히카리,\n그중에서도 좋다하는 브랜드인 수퍼오닝으로 샀어요.\n다 애만 먹여서 맛은 못 봤네요.',
 '쌀이 신선하고 밥맛 좋네요..배송 빠르고 재구매 할께요\n쌀이 신선하고 밥맛 좋네요..배송 빠르고 재구매 할께요',
 '밥맛이 좋아요\n고시히카리 매번 먹는쌀입니다 이쌀 먹다 일반쌀 먹기 힘들어요',
 '찰기가 좋고 맛있어요.',
 '선물했는데 좋아합니다',
 '안 좋은 후기가 있어서 걱정했는데 찰밥 같이 맛있고 윤기가 있어요 너무 맛있어요',
 '쌀이 싱싱하고 좋아요',
 '밥맛 좋아서 재구매해요..\n쌀알이 촉촉하고 알차며..밥맛이 좋아서 재구매 하면서 상품평 남겨요..배송도 빨라요',
 '굿이예용',
 '밥 맛있네여~~',
 '햅쌀이라서 명절에 먹으려고시킨건데\n도정날짜가 한달하고도 20일이넘은게\n왔네요..ㅜㅜ비추입니다',
 '3번째 구매입니다\n밥 잘 지어먹고싶다!\n쌀이 기본이죠\n솥이 휘슬러여도 쌀이 묵은쌀이면 꽝입니다\n근데 휘슬러에 슈퍼오닝쌀로 밥 하면 죽음이에요\n집 가서 밥먹을 생각뿐',
 '지금 계속 슈퍼오닝 고시히카리 먹는데 좋습니다.\n혼자 살면 4kg, 둘이 살면 10kg가 좋을 듯 싶습니다.',
 '맛나고 좋아요\n가격도합리적이고요.\n배송도 만족입니다',
 '역시 쌀은 고시히카리.\n\n신동진은 알도 작고 날리는 느낌이라 식사후 뭔가 불만족스러운데\n\n고시히카리. 거기다 햅쌀이니까\n\n어렸을적 친할아버지께서 힘들게 농사 지어주셨던 그 밥의 맛이 나네요.',
 '맛있대요',
 '훌륭했어요.',
 '지금 3번째 구매인가?4번째인가 잘모르겠지만\n쌀 맛갠찮아요 세구이지만 집에서 밥을 잘 안먹어서 작은걸 구매하기 시작했는데 딱 좋아요\n\n재구매의사 있어요',
 '4kg 단위로 자주 주문해요. 맛이 좋아요.',
 '먹는 내내 밥맛좋게 먹었어요.~\n밥맛이 좋아요',
 '3번 구매입니다\n배송은 기냥 봉다리에 와서 불안 했는데 안터졌네요',
 '깨끗하고 밥 맛있어요',
 '항상 먹는 쌀이예요 ㅎㅎ 밥이 맛있어요',
 '역시 고시히카리\n\n윤기 좔 좔\n\n쫀득쫀득\n\n여름철 밥 맛 살아나네요',
 '밥하면 질어요\n고시히카리인데\n차지거나 달큰한 맛이 없어요\n그냥 일반쌀이랑 별 차이 없네요\n고시히카리나 추청쌀은 그냥 밥만 먹어도 달큰하니 맛있어서 이래서 좋은 쌀 사먹는구나 했는데...\n\n밥하면 물기도 많고 별로였어요\n물 줄여서 밥 지어도 쌀알이 쫀득하지가 않고 퍼석해요\n가끔 쿠팡에서 주문하던 당진쌀이 밥맛이 더 좋은 것 같네요\n\n전에 먹던 홈플러스 고시히카리를 다시 사야 할 듯 해요\n\n19,900원에 구입했어요',
 '추천합니다!아주 맛있어요!',
 '전에 구매해서 먹고 밥맛이 갠찮아서 또 재구매했어요\n다 먹고나면 재구매의사있어요',
 '두번째구매입니다. 뜯기전이지만 바로전에 먹어봤던지라 믿고 재구매했어요. 지금까지 여러브랜드 먹어봤지만 젤 괜찮았어요. 여름이라 소량으로 샀어요.',
 '예전에 먹어보고 괜찮아서 또 샀어용',
 '맛있네요. 쌀알도좋구요^^',
 '사지마세요~냄새나서 못 먹겠어요 ㅜ',
 '세번째 재구매 입니다~ 배송 빨라서 좋구요 쌀 상태도 늘 좋아요! 2018년 쌀이도 도정일이 2019년 7월19일로 비교적 최근이네요~ 두 식구고 집에서 먹는 밥이라 해야 아침 한끼 정도라 4kg 주문해도 충분히 한달은 넘게 먹는 것 같아요! 재구매 의사 있어요^^',
 '밥은 아직 안 해봤어요 좀전에 받았는데 구멍나 있어서 쌀알 좀 버리게 됐네요 배송의 문제인건지...',
 '밥 맛있어요',
 '갓지은 밥이 윤기가 흐르고 밥맛이 좋습니다\n내내 이천쌀만 구매해먹다가 바꿔봤는데 품질 좋습니다\n생쌀이 깨진것도 많지않은거같고 만족스러워 재구매 의사있습니다 계속 이런 품질 상태를 유지해주시길 바랍니다',
 '진 밥 좋아하는 분들 추천\n꼬들밥 좋아하는데 물을 조금 넣어도 밥이 질게 되네요 ㅠㅠ\n맛없진 않은데 제 스타일은 아님ㅎㅎㅎ..',
 '깨끗하고 맛있어요~~~',
 '운이나쁜건지\n보름전 정미된게왔어요\n하지만 밥맛이좋아요\n미각이 훌륭한 삼식이라...\n맛난데요',
 '구매해서 지금 밥을 해먹고 있는데 쌀도 갠찮고 좋아요\n다시 재구매 할려고 장바구니에 담아놨네요 좋아요',
 '늘이것만먹어요\n가격이적당해서좋아오',
 '밥맛좋은쌀\n쌀은 고시히카리만 먹어용\n매번 도정한지 얼마 안된게 와서 맛이 너무 좋음\n돌지난 아기까지 3가족인데 평일엔 거의 밥을 안먹어서\n4키로 사면 2달은 먹는듯..\n요것도 정기배송이 있음 좋겠네오',
 '여러가지 쌀을시켜먹엇지만 정말 최고에요~~말이필요없음 ~~최고쫀득쫀득~~~이렇게 맛잇는쌀은 처음~~진짜 태어나서 먹어본쌀중 최고~~최고..!!!',
 '배송 빠르고 좋아요~',
 '맛있고 운 좋게도 도정일자가 가까운 상품이 배송되어 신선했어요^^',
 '맛있어요',
 '쌀마다 상품평이 호불호가 갈려서 찾다찾다 이 제품은 안좋은평은 하나도 없는것같아 구매해봤어요. 지퍼팩은 아니지만 여름이라 소분해서 냉장고 넣을거라 상관없지싶어요. 쌀알도 좋고 찹쌀 조금 섞어서했더니 아이가 먹다 남긴 차가운 상태여도 맛있더라구요ㅎㅎ 여름이라 4키로짜리 샀는데 잘산것같아요~!',
 '넘나 맛나네요\n짱맛있어요.\n고시히카리 첨 먹어보는데\n쌀눈도 살아있도 밥도 쫀득하니 맛나요.',
 'Good!\nGood!',
 '맛나요',
 '쌀은 조금씩 여기저기 주문해서 먹는데 송탄 쌀은 벌써 세네번째 구매예요! 가격, 배송, 품질 다 만족합니다. 재구매 의사 있어요~',
 '맛있네요 쫀득하구',
 '쌀이 터져서 왔어요\n애 당장 먹여야돼서 그냥 먹이는데 신발장에 쌀 쏟아지고 난리도 아니네요^^',
 '쌀은 좋아요\n쌀이 참 이뿌네요\n다만 제 밥솥이 안좋아요',
 '재구매에요 이때까지 먹어본 쌀중에 젤 맛있음! 짱짱맛',
 '터졌어요',
 '6월 2일 주문해서 3일날 받았는데\n도정일이 5월 31일로 굉장히 최근이네요',
 '밥 맛이 좋아요.',
 '밥 맛이 좋아요 고슬고슬 !',
 '보통쌀',
 '윤기있고 찰진 밥맛\n골든퀸3호 먹다가 이 제품 주문해봤는데 더 맛있네요.\n윤기가 좌르르하고 찰져요.',
 '윤기 흐름. 항상 특등급만 먹어와서 상등급 괜찮을까 했는데 이것도 괜찮네요',
 '좋아요~쿠팡은 배송이빨라너무 좋구\n쌀도 괜찮네요~~',
 '초보 주부라 밥 할때 좀 질게 되어서 다시 해봐야 알겠지만, 특별히 맛있다는 생각보단 평범했어요.. 워낙 밥맛이 좋다는 소문만 믿고 주문했지만, 밥 짓는것도 실력이 필요한가 봅니다. 물 잘 맞취서 맛있고 윤기있는 밥 대접하고 싶네요~',
 '밥맛좋은 고시히까리\n밥맛 진짜 좋아요~~ 강추합니다.\n그런데 배송이 비닐봉투에 담겨왔는데 찢겨있었어요.\n물론 안에 쌀알들도 많이 밖으로 흘러나왔네요.\n배송을 박스포장이나 안전하게 해주면 좋을듯합니다.',
 '상품이 터진게 넣어져서왔어요.',
 '우선 4kg을 시켜 먹어봤는데\n저는 별로네요.\n찰기도 없고 다른 고시히카리 쌀과는 다르게\n맛이 없어요.\n물을 적게 넣어서 그런가 싶어 많이 넣어봤는데도\n변함없이 푸석해요.\n지금 다른쌀 구매해보려해요ㅜㅜ',
 '두번째 구매예요~ 쌀은 조금씩 사서 이것저것 먹어보는 편인데, 슈퍼오닝 쌀 마음에 들어 4kg 한번 더 구매했어요~ 도정일도 최근이고 만족합니다!',
 '기대하고 했는데 망해쓰ㅠ죽밥을했네요비싼가격하는거 갗아오',
 '최고의밥맛선생님\n진짜 리얼 대존맛이에요.\n전 우리집 밥솥이 안좋아서 이때까지 밥이 그저그런줄알았는데\n쌀이 문제였어요. 안불려도 어쩜 이렇게 찰지고 맛나죠????? 재구매 무조건힙니다',
 '늘 먹던것입니다',
 'ㅈㅏㄹ먹고있어요',
 '10kg시키다가 작은것 시켰는데,, 역시 찰져요~',
 '만족해요\n작년11월쯤부터 계속 이쌀먹었는데\n품종자체가 찰진것같아요\n다른쌀처럼 똑같이 밥물잡으면\n밥이 찰기가많아서 질은느낌이나요\n개인적으로 진밥을 안좋아해서\n물 살짝 덜잡고 밥하니 딱 좋습니다',
 '윤기가 있고 맛있네요',
 '고시히카리 쌀중 아주 칭찬합니다\n옛날엔 안성꺼 진짜 좋아했는데...\n어느순간 요즘 고시히카리 쌀이 왜케\n맛이 없어졌는지... ㅉㅉㅉ 할쯤\n시켰는데 도정날짜는 3/26 도착일은 4/7이네요\n밥하면 일반쌀은 시간 지나면\n노래 지는데 이쌀은 꽤 오래 하얗습니다\n윤기도 찰기도 오래가네요',
 '믿고먹는 고시히카리 쌀이에요!\n쌀 맛있었어요!\n너무 무거워서 쿠팡으로 시켜봤는데요.\n1인가구이며 2019.01.08일에 사서 2019.04.08에 다먹었어요! 2끼먹는 기준으로했을때요!\n자취생들이 사서 두고먹기 좋은 량과 좋은 품질!\n쌀벌레도 안나왓어요! :) 너무 상태좋아서 재구매의사있어요~고시히카리쌀은 역시나 맛있네요',
 '쌀알이 원래 먹던것보다 작은편임 그리고 짱짱맛',
 '아직 안먹어봤어요..\n비싸지만 밥맛좋다해서 우선 4키로 주문했네요~\n도정일이 11일 이상 전이지만...\n맛있길 기대해봅니다',
 '고시히카리인데..전 맛이 별로 였어요.\n제가 생각한 고시히카리가 아녔어요ㅠ',
 '도정은 1주일 정도 되요 좋아요',
 '후기 꼼꼼히 살피고 주문했어요~ 다른 쌀보다 가격은 좀 있는편인데 후기가 좋더라구요~ 아직 밥은 안해봤는데 배송 빠르고 배송 상태도 깔끔히 잘 전달 받았어요! 도정일도 최근이예요~ 밥 해서 먹어보고 맛있으면 재구매 의사 있습니다~',
 '상자가 다 찢어져서 배송 됨.쌀터졌을까봐 화날뻔',
 '쌀이 윤기나고 밥맛도 좋아요',
 '드셔보세요~!\n두번째 주문했구요 3번째 주문 전 후기 남김니다. 쌀이 뽀야니 이쁘구요 정말 달아요. 남편도 깔이 맛있었어서 맨밥을 계속 씹게된다고 하네요. 늘 찹쌀 섞어먹었는데 이제는 그냥 먹습니다. 강추요',
 '쌀은 괜찮은데 끈기가 좀 없는것같음',
 '받자마자 밥 해봤는데 정말 찰지고 맛있어요',
 '다시 구매예정 입니다\n아기 후기이유식 제품으로 구매했어요.\n쌀알이 깨끗하네요.',
 '자주 사는 상품입니다. 말 할 필요없이 좋습니다♥',
 '재구매함.\n두번째 구입.\n맛있어서 재구매.\n밥이 찰기가 돌고 촉촉한게 밥맛이 좋아요.\n이천쌀 우렁쌀 별의별걸 다 먹어봤는데 이게 제일 맛있네요.',
 '맛은 있는 데 쪼금 비싼 감이ㅎㅎ',
 '맛있는쌀 저렴하게 잘 샀어용~\n고시히카리 쌀이 맛있다고 해서 구매해봣어요. 찰밥처럼 쫀쫀하고 진짜 맛있게 지어집니다~ 사진은 김이 서려서 뿌옇게 나왔는데.. 추천해요',
 '밥맛이 상당히 좋습니다. 적은 포장으로 자주 사먹는게ㅡ밥맛을 좋게하는 방법인듯',
 '찰지내요.',
 '맛있어요~ 구수한 밥냄새가 나요',
 '굿',
 '찰기있고 맛납니당! 값이 나가는만큼 맛있네용',
 '굿',
 '좋아요 밥 맛있어요',
 '밥 맛있네요~~',
 '쿠팡의 배송은 좋으나 가격이 조금 비싸요 5Kg도 아니고',
 '잘받고 잘먹고 있네요',
 '다음에도시켜먹을거에요\n밥알이살아잇고맛잇어요',
 '까다로운 울엄마 입맛에 합격',
 '배송포장모두만족\n밥맛도찰지고\n맛있어요\n아쉬운점\n쌀이부서짐이있어요\n너무많이씻으면\n안될듯',
 '고시히카리 치고는 밥맛이 별로에요ㅜ\n맛이없다는건 아닌데, 아쉬워요 뭔가ㅜ',
 '특등은 아닙니당 쌀불려서 밥해봐야겠지만\n특등인줄 알고 샀는데 상등이네요 ㅠㅜ\n\n밥은 아직 안해봐서 ㅋㅋ',
 '밥이 좀 질게 되더라구요 물 양을 좀 다르게 해야할까요? 밥맛은 좋아요',
 'jmt',
 '살다살다 쌀씻다가 밥 겁나 맛있것네하기는 처음이네요\n\n2년묵은 쌀만먹다가 이거먹으니 밥 개존맛...',
 '밥알이 푸석한 게....고시히카리 맞나 싶어요.\n\n갓지은 밥도 별로 ㅜ ㅠ',
 '괜찮아요.\n때깔 좋고 밥하믄 찰지게 잘되요.',
 '이제 쌀 유목민 안해도된당!\n밥맛이 꾸르맛!\n이천쌀 철원오대미 우렁이쌀 추정 온갖거 다 먹어봤는데\n역시 고시히카리~ 고시히카리~ 하는 이유가 있네요.\n최고인듯??\n다음날 먹어도 맛있어요 ㅠㅠ 살찔듯;;',
 '비싸지만 초강추쌀!\n3번째구입..솔직히 타4kg 쌀보다 6~7천원 정도 비싸지만 이거먹다가 딴쌀 못먹겠슴..차지고 윤기,간지 좔좔거림..쌀과 사랑에 빠지긴 처음',
 '이천대왕님쌀만 쭉 먹었는데 쌀 괜찮네요~ 찹쌀 섞은것처럼 쫄깃하고 맛있네요~~',
 '아직안먹었어서 밥맛은 모르겠어요\n쌀알이 굉장히 작은데...\n지금 다이어트중이라 밥알이라도 큰거먹고싶었는데....\n욕심이겠죠 네네',
 '한번두매하고\n두번째구매입니당~~~~~♡♡♡♡\n역시나배송빠르고 맛잇고\n부족함이없네용^^\n4키로짜리 품절이라 재입고알림해놧어용ㅎㅎ',
 '나 좀 쌀 미식가다 하시는분들 거 꼭 드세요 정말최고ㅜ\n밥맛에 민감하신 분들!! 이거 꼭 드셔보세요 정말 맛잇어요 정말 정말 이게 내가 원하단 쌀밥의 참맛임 ㅋㅋ',
 '맛나요\n밥맛있음',
 '도정날짜도 신선하고\n밥맛도좋고\n배송도빠르고\n믿을수있는인증마크도잇고\n어느것하나 단점이없네요~^^\n계속구매할예정입니당ㅎㅎ',
 '지인에게 추천받아서 구매했는데, 정말 밥 맛이 좋네요!!^^',
 '쌀자체는 좋은데 물을 잘맞춰야 겠더라구요 보통쌀에비해 좀질게되는 경향이^^;;; 그치만 밥맛은 최고입니다!',
 '맛있습니다\n윤기는 나는데 쌀알이 조금 작은게 걸리네요 비교적 맛은 좋네요',
 '햅쌀이 필요한 그대들에게 춫천이요^. ~\n시가댁에서 농사지어서 쌀을 보내주시는데 햅쌀 받기까지 시간이 쫌 남아서 시중쌀을 구매하게되었습니다.\n\n햅쌀 먹고싶은데 온라인에서 구매하는건 처음이라 망설여졌는데\n상품포장 겉면에 도정일이 12월 초라고 인쇄되어있어서 믿음이 가네요^^;\n\n밥을 지어보니 밥알도 쫀득쫀득하고 맛있습니다.\n쌀떨어지면 재구매의사 있습니다.\n\n- 배송상태 : 로켓배송으로 다음날 바로 발송, 상태 good\n종이박스로 포장',
 '굿!\n굿!',
 '찰밥같이찰지고좋아요',
 '추천합니다\n밥솥이 좋지않은거같아서 쌀이라도 맛있는거 먹으려구 유명하길래 구매해봤어요!\n그전에 먹던쌀보다 맛있어요ㅎㅎ\n계속 시켜먹을게요^^',
 '이천쌀먹다가 최근별로맘에안들어서\n구매해봤는데 맛있네요\n더 찰지다고해야되나?\n이천쌀보다더나은것같아요\n진짜밥이 맛있네요\n다먹으면 또구매할게요',
 '고시히카리 한번 사먹어보고 고시히카리 품질에 반해서\n비싸도 이품종만 먹어요;)\n정기배송하던게 품절이되어서 요거한번 사봤는데\n역시 이것도 괜찮네요!\n잘 먹겠습니다^^',
 '맛나요. 이유식으로 구매 했오요',
 '맛있어요',
 '햅쌀이라그런지 밥이 윤기나고 맛있어요',
 '밥에 윤기가 돌고 맛나네요.',
 '맛있네요',
 '맛있습니다',
 '햅쌀이라 맛있어요',
 '맛있어요\n쌀이 깔끔허네요\n근데 쌀알이 조금 작은 듯 하네요',
 '재구매의사높음\n고시히카리는 처음인데 밥 맛있네요\n또 살 것 같습니다.',
 '맛있어요~~',
 '항상 시켜먹는 썰이에요\n쫄깃하고 맛있어요',
 '반 존맛탱구리 완전 강추',
 '쌀이 넘좋아요.밥솥에 보온해두어도 쌀알이 살아있어요',
 '고시히카리 쌀이 유명해서 구매해서 먹어보니 맛있습니다.\n\n재구매 의사 있습니다.',
 '추천. 밥맛조하\n상태좋고 깨끗. 밥도 찰지고 맛나요. 굿굿.',
 '불순물 뜨는것 없고 깨끗해서 좋아요',
 '쌀이 정말 찰지고 맛나네요. 맛있어요',
 '쌀사러가기 귀찮아서 시켜봤는데 기대이상이었습니다. 햅쌀답게 찰지고 맛있어요. 강추합니다^^',
 '슈퍼오닝ㅎㅎ\n나쁘지 않아요 날짜도 최근이고 맛도 괜찮고.\n저흰 여기에 잡곡 섞어 먹는데. 아이도 어른도 잘먹고 있습니당 ㅎ',
 '좀 비싸서 망설였는데 쌀 좋아용\n눈도 하얗고 밥해봤ㄴ데 찰밥처럼 찰지네요',
 '밥맛있게 잘되서 좋아요',
 '좋습니다\n찰진 밥맛 좋아요',
 '쌀을 까다롭게 고르는 편인데 급하게 쌀이 떨어져 로켓배송이 되는주에 주문했는데 예상보다 맛나고 좋으네요. 추천합니다.',
 '햇반만 먹다 최근 밥해먹으려고 주문햇는데 쌀이 맛나요\n상품평은 없고 긴가민가 한번 주문해봣어여 로켓배송도 되고해서 주문햇는데 완전만족합니다 쌀눈이 살아있고 쌀 빛깔도 살아있네여 사진 원래 안찍는데 첨으로 찍어봣네여 흑미좋아해서 같이 주문해봣네여\n진짜 밥이 맛있어여\n포장도 깔끔하게 되있었어요',
 '밥이 윤기나고 맛있습니다.',
 '밥맛이 최고예요\n단골될듯합니다',
 '기버터 가격이 좀 비싸요~~조금 큰용량있으면 좋겠어요',
 '풍질이 별로에요ㅠㅠ',
 '밥맛이 너무 좋아요\n밥맛이 좋네요',
 '밥맛좋아요~^^',
 '좋아요 좋아요 좋아요',
 '밥 맛 정말 좋네요 이렇게 좋은 쌀 처음 먹어보네요\n재 구매 확실하네요',
 '밥맛이 좋아요',
 '괜찮은거같아요',
 '추천해요!\n밥맛이 너무 좋아요^^',
 '기존에 임금님 이천쌀 먹었고요\n가격이 조금 덜 부담스러운 고시히카리도 한번 먹어보자 해서 구매했는데 맛도 좋고요.\n한동안 자주 시켜먹게 될것 같아요.',
 '대체적으로 괜찬아요 배송이 좀만더 빠르면 합니다',
 '고시히까리... 이것도 특,상,중,하로 구분되는줄 이제야 알았네요.이번에 산 물건은 "상"으로 표기되어 있는데 가산농협엔 특품은 없나요? 다른곳 쌀보다 2~3천원 싸길래 샀는데 기왕 젤 비싼 고시히까리 먹는 사람이 특품을 찾지 하등급 찾겠어요?',
 '고실고실\n빛나고\n졸깃 실하다',
 '밥맛이너무좋아요^^',
 '윤기좋고 맛도좋고감솨요~',
 '너무 맛있었구요.또재구매해서 먹을꺼예요.',
 '깨끗해요\n20키로 구매 했습니다.\n쌀 깨끗하니 좋네요\n밥맛도 괜찮아요.\n배송도 빠르고 꼼꼼하게 포장 되서 왔습니다.\n\n다시 구매하게 된다면 이제품 택하겠습니다~~',
 '맛있어요~\n잡곡과 섞어도 찰지네요~\n맛있게 잘 먹을게요~',
 '두 번째 구입해요. 밥 맛 좋아요',
 '후회 없을 밥맛!!',
 '정말 쌀이윤기나고 맜있습니다\n처음엔 비싸다 생가했는데 밥맛에 비하면\n비싼것이아니네요\n잘먹을게요',
 '밥맛이 너무 좋아서 밥 할 맛 납니다\n감사합니다\n많이 많이 파세요^^',
 '밥맛 조흠\n이전에 철원쌀 먹었는데 역시 맛이 좋음 대신 물을 조금 적게 넣어서 해야 좋은 것 같음 기존의 물량으로는 조금 질은 느낌이 옵니다',
 '감사합니다.\n밥맛좋아요 두그릇씩 먹는답니다.물은 좀 평소보다 적게 넣어야할듯....',
 '비싼만큼 완전 찰지고 맛있어요.',
 '너무좋아요^^',
 '고시히까리쌀 맛있어요',
 '첫째 구매한 쌀은 괞찬았는 데\n두번째구매한 이번 쌀은 형편없어요\n마치 동남아에서 수입한 쌀처럼\n날라다닙니다.',
 '고시히카리 밥맛좋아요. 최고',
 '쌀이 딱 어제떨어졌거든용.ㅋ\n신속하게 배송해주신덕에 저녁밥을 해먹을수있었네용~^^\n후기보니까 다들 맛있다고 칭찬하시기에 믿고\n주문했는데용~^^\n너무 촉촉하고 찰지고 좋아용~^^\n퇴근하고 늦게와서 후다닥 씻어서 불릴시간도 없이 쾌속으로\n했는데도 너무 맛있게 잘된거있죵~^^\n다음에도 또 다음에도 쭈~욱 요쌀만 찾을거같아용~최고^^',
 '품질이 좋아 확실히 밥이 윤기도 있고 맛있어요',
 '좋은 품질과 엄청 빠른 배송\n상품평이 좀 늦었네요. 좋은 품질과 빠른 배송 대만족입니다.',
 '찰지고 싸고 좋아요',
 '밥맛좋아요.찰기굿,윤기굿,달큰해요',
 '다른쌀 못먹음..중독주위\n최고의 밥맛',
 '재구매했는데 넘 좋네요!!! 고맙습니다...',
 "단일품종이긴 한데 품질이 '하'네요. 구매시 몰랐음\n품질의 하등급 표기는 상품설명 화면에 나와있었는지 보지도 못했네요 제품포장의 하등급표기를 보니 왠지 쌀이 안좋아보입니다. 밥을 하면 윤기는 별로 없어도 먹을만하네요",
 '녹색날알이 너무많았어요',
 '또 주문했습니다. 다음에 또 주문할게요!',
 '사실 쌀인 줄 알고 현미 주문했어요ㅎㅎ; 평생 먹을 분량의 현미인듯',
 '쌀 맛있어요~~~또 주문합니다.',
 '초록색 현미가 많이 섞여 있어서 별루입니다\n촉록색 현미가 많다는건 다 여물지않은\n벼를 수확했기 때문입니다 실망입니다\n잘은 안해도 바르게는 해야지요',
 '빠른배송 좋은 상품\n빠른배송 좋은 상품',
 '화성의 조암 고시히까리가 맞나요?\n이런 쌀은 한번도 못봤던\n품질에서 맛과 향이 너무 다릅니다\n오랫동안 먹어왔던 만큼 어느정도 느낌이 있는데 너무 달라요\n물이 조금 많으면 떡밥되고 조금 덜넣으면 밥알 자체가 까슬하고 어디 외국 수입 쌀 인가요?\n햇살마을? 방앗간 이름인가요?\n상점 이름인가요?\n그 동안 최고 품질 좋은 쌀이라 생각했는데, 정말 실망했어요 안 사고 싶네요 ㆍ',
 '2020년 햅쌀 조암농협 화성고시히카리\n2020년 햅쌀 조암농협 화성고시히카리, 1개, 10Kg',
 '좋아요.',
 '물건 참 좋네요\n좋은물건 싸\n포장 깔끔했어요\n물건 참 좋네요\n좋은물건 싸게 잘샀습니다. 추천드려요',
 '이쌀먹을때 똥 아주 잘쌋음!',
 '보보통\n약가비쌈.10키로인지 알고 삿는데 약간 맛있음',
 '기존에 먹었던 현미보다는 찰기가 있어 만족합니다.',
 '밥 맛이아주좋아요 윤기나고 찰지고',
 '당일 도정해서 그런지 밥맛이 최고입니다 좀비싸지만 최고입ㄴ다 적극 추천합니다',
 '배송도 빠르고 제품 품질도 좋았어요 만족합니다~',
 '가격은 좀쎄지만 밥맛하나 만큼은 좋아요',
 '도정한지 오래지않아 좋아요\n밥 이 차지고 맛도좋아요 3년째 단골이네요',
 '정말 이번에는 더 찰지고 맛나요 ^^ 주위에 소개도 하고 비싸도 이거만 먹을래요',
 '윤기가 좌르르~~밥맛 좋아요!!',
 '쌀이 찰지고 맛있습니다 다음에도 구입하고 싶어요',
 '정말맛없는쌀입니다 그냥씰이네요 요번에 뜯구보니 그전에먹던쌀이여서 너무내자신을 잘보지않쿠 비씨니당근맛이겟다하구산게실수이네요ㅜ 뜯어으니 어쩔수읍이 몇달을먹어야겟네요',
 '감사합니다 ~^^',
 '너무 맛있어서 엄마네도 뱌달시켜드렸어요 ~',
 '밥맛 나는 쌀\n제일 맛있는 쌀이예요. 그냥 김치만 갖고도 밥이 맛있어서 잘 먹을 수 있는 쌀입니다.',
 '확실히 때깔이 다릅니다\n어렸을때 농사지어 먹어본 쌀밥입니다\n쌀뜨물이 뽀얗게 나오네요\n밥만먹어도 맛있어요 ㅎㅎ',
 '아주 좋아요\n쿠팡에서 구매한 쌀중엔 최고의품질 입니다',
 '맛도 품질도 쵝오!\n항상 먹는 쌀\n여기만큼 쌀 맛있고,\n품질 좋은곳,\n아직 못 찾았어요.\n여기쌀이 쵝오요~',
 '저희집은 이 쌀만 먹어요\n가격이 좀 비싼 편이지만 밥맛이 끝내줘요',
 '쌀윤기죽입니다\n가격대가 있긴하지만 아깝지않아요.\n밥만 먹어도 너무 맛있어요^^',
 '늘시켜먹는 쌀 밥이 달아요',
 '밥 맛있어요 쌀알도 만족하구요',
 '맛있어요',
 '95점 ^^',
 '20키로쌀을 주문했는데 옮기다 가벼워서 무게를 재보니 19kg 이네요 황당하네요~~~~~\n\n돈을 1키로만큼 환불해주시던지 주소로 1kg 따로 더 보내주세요!!\n신뢰를 바탕으로 지금까지 5번정도시킨것같은데 무게 재보지 않았는데 지금까지 먹었던것도 의심되네요!!!\n담부턴 못시켜먹을것같네요 !!\n속여서팔지맙시다',
 '아직 먹어보진 않았는데 괜찮을것 같아요...',
 '기분 별로ᆢ 먹어보고ᆢ\n쌀은 먹던거 남아서 먹고 먹어야되서 아직은 않먹어 밨지만 상품평보고 주문했으니 맛나겠지요 먹어보고 맛없으면 마저 남길께요 맛~나면 패스 근데 박스에 포장되서 왔는데도 불구하고 박스는 괜챦은데 옆구리가 조금 터져왔네요 그럼 터진걸 보냈다는 얘기인감 기분좀 언짠아 별 4개요 안만 씻어먹는거라해도 먹는 주식을 터져보내심 아니되오~~~',
 '여태껏 먹은것중 가장 괜찮은것같아 또 구입하고싶네요\n처음 구입해봤는데\n찰지고 윤기도 좋고 밥맛이 상당히 좋네요\n또 구입하고 싶습니다',
 '맛이 있어요\n빨라서 좋아요',
 '다른쌀보다 밥통에해놓으면색이 바라지않음',
 '너무느리다 느려도 너무 느리다 돈이 이중으로들고 욕만',
 '쌀이 품질이 너무 좋아서 일년넘게 시켜 먹고있는데 배송\n배송지연으로 마트에가서 쌀 사서왔음\n배송날짜을 지켰으면 하는 바람입니다',
 '가산 농협 고시히까리쌀 최고입니다 바로 도정 해서 주니까 밥맛은 최고입니다',
 '윤기돌고 찰기도 있어서 꼭 이 제품을 애용하고있어요',
 '많은 쌀을 먹어본결과 고시히까리쌀 최고입니다',
 '쌀이 너무 많이고 친정엄마가 제일 좋아하는 쌀요..',
 '쌀알이 고르고 밥에 윤기가 쟈르르 흘러요\n그동안 시켰던 어떤ㅈ비쌌던 쌀보다 훨씬 좋아요~',
 '처음 시켜본 품종인데 맛있어요\n쌀 윤기도 흐르고 식어도 색이 변하거나 밥알이 날리지 않아 좋아요',
 '항상 먹는쌀 맛있어요',
 '3번째구매.쌀굿',
 '여러번 재구매합니다 밥맛최고예요\n저희는이살만구매합니다',
 '세번째 배송으로 먹고 있어요 맛나요',
 '밥맛이 좋아요 농부님들 수고하셨어요',
 '좋아요\n계속 구매하여 먹고있는데 좋습니다',
 '지금까지 여러번째 구매해봤는데 여기 쌀이 젤 맛있었어요\n항상 변하지 않는 맛과 정성에 감사해요',
 '다른쌀 섞이지않고 고르고 밥도맛잏머요',
 '쌀을 택배하는사람이 내동챙이 쳐놓고 가서 터져있었네요 어이없음',
 '굿 쌀진짜 좋아요\n두번째구매.친정엄마가 밥맛이 촣다고에서 또구매했어요\n진짜내가먹어보고 밥맛이 최고굿 촣은쌀 감사해요.또 재구매 생각있습니다.',
 '밥맛도 좋고 좋아요',
 '밥맛이 맛있어요',
 '누룽지쌀(?)을 다른곳에서 구입해 먹었는데 품절이라 여기저기 뒤져보다 평이 좋아서 구매를 했어요\n그런데 생각보다 밥맛도 좋고 도정한지 얼마 안되어서 그런지 구수하면서 윤기도 흐르는게 정말 괜찮았어요\n두번째 구매합니다',
 '윤기가 반지르르 밥맛이 좋아요',
 '쌀 느무 맛있어요~ㅎㅎ\n밥할때 고소한 냄새가 진동해요~\n고슬고슬하게 지어서 김만 싸먹어도 넘나 맛있네요~\n햅쌀도 아닌데...햅쌀 나오면 얼마나 맛있을까요?ㅎㅎ\n비싸도 재구매 할거에요~',
 '친정에 쌀이 떨어져서 구매했는데.찰지고 맛있다고 하네요.밥만먹어도좋다고하십니다.재구매 의사있음.',
 '찰지고 맛있어요',
 '먹어보지 않아 모르겠어요',
 '항상구매한 상품입니다.',
 '오자마자씻어서 전기밥솥에밥을 했는대 너무찰지고 맛있네요~~압력밥솥에하면 더찰지고맛날거같네요~~구수한밥냄새~식욕이땡기네요 ㅎㅎ',
 '찰지고 맛있어요~\n20kg사서 밥맛이 없으면 그것만큼 난감한일이\n없을텐데~맛있어서 다행이에요~\n우리쌀 좋아요~\n다른쌀 섞지말고 팔아주세요~\n쭈욱~사먹을수 있게 해주세요~',
 '가격대비 배송도 늦고 품질도 가격대비 별로ᆢ',
 '배송빠르고 물건 마음에듭니다',
 '밥맛이 좋아요\n앞으로 이쌀로 바꿔야겠어요',
 '좋아요 .',
 '구매한 이유는 1달전에 한번먹어보니 쌀이 정말좋더군요 추천합니다',
 '포천 고시히까리쌀 먹어보고 다시 주문합니다 밥맞 최고입',
 '좋네요~',
 '배송오는날에 안오고 하루 늦게오는게 좀불편햏어요',
 '좋아요\n다른지역 쌀보다 좋은 편입니다',
 '가격대비 품질 별로네요\n재구매 안합니다',
 '두번째구입해요 맛있고만족합니다',
 '이글을 보시는분들 절대로 사지 말라고 하고 싶네요\n고시히까리라고 비싸게 샀는데 영 안 좋네요.쌀알이 찹쌀처럼 불투명하고 밥을 해도 맛이 없어요.돈 아까워 죽겠어요.20키로를 언제 다먹나 걱정이에요,ㅠㅠ',
 '없는 밥맛도 땡기는 찰지고 달달한 쌀밥입니다.\n고시히카리 비싸서 그렇지 가격만 아니면 고민할 필요없는 찰지고 맛난 쌀입니다. 암튼 쌀가격 좀 내렸으면 좋겠어요. 이제 보통쌀은 못먹게 된 높아진 입맛~재구매합니다.',
 '윤기흐르고 맛있어요.',
 '상등급이라 기대했는데 결과는실망.',
 '보통\n밥 맛이 좋은건 모르겠고 그냥저냥 괜찮아용\n나쁘진않습니다',
 '좋아요\n좋아요좋아요좋아요좋아요',
 '쌀알도좋고 밥맛도 좋아요 지금껏 먹은 쌀 중에으뜸입니다',
 '평이 좋아 샀는데 , 아직 해먹진 않아서 ㅡ',
 '배송빠르고 물건 마음에듭니다',
 '맛있어서 재구매합니다',
 '쌀이 쫀득하고 맛나요 재구매 할라고요',
 '비싼만큼 그값을 합디다',
 '상품평보고 샀는데 맛있습니다...',
 '가산농협 2018년 햅쌀 포천 고시히카리쌀1개.20kg\n수욜 주문하고 토욜 받앗네요.연휴도 끼고 좋은 제품 부탁도 드리고..\n일단 마트에서 고시히카리20kg만 항상 사먹었는데 마트에서 사면 잡곡이랑 섞어서 보관하다가 갑자기 흰쌀밥에 김치 얹어서 먹고 싶다는 충동ㅋ.\n살이야 찌던 말던 일단 남아있는 쌀도 있는데도 불구하고 구매했네요.\n상품평.가격.이것저것 따지고 비교하고 그나마 여기가 딴데보다 상품평도 좋고해서 일단 시켜보자는 맘에 첫구매에도 불구하고 20kg 시키면서 좋은 제품 부탁 글을 남기니 바로 도정해서 보내주신다는 답글.\n연휴가 끼어서 3일만에 도착했는데 박스에 포장되서 배달이 왔더라고요.\n보는 순간 기분이 좋아지고 작은거에도 신경을 쓰신다는 생각에 얼릉 풀어서 보관통에 담아서 정리하고 밥을 했는데 밥솥뚜껑을 여는순간 하얀 쌀밥이 군침돌게 하더라고요.\n그 자리서 한그릇 떠서 김치랑 순삭해버렸네요ㅋ\n일단 밥이 달다고 해야되나? 찹쌀 섞은것처럼 밥이 찰기도 있네요...신랑도 맛잇다고 아주 흐뭇해하네요...\n기존에 있는 쌀과 비교해서는 당일도정 맞는것 같고 밥맛이 넘넘 조아요.\n밥할때 물은 기본보다 쫌 덜 잡는게 맞는거 같네요.\n조은 쌀.맛잇는 쌀.보내주셔서 감사하고 담에 재구매 100%입니다.\n마니 파세요~^&^',
 '좋아요',
 '만족합니다.\n쌀이 윤기있고 밥맛이 일반쌀보다 찰기있고 맛나요. 재구매합니다. 품질이 동일하길 기대해봐요.',
 '역시 고시히가리쌀...\n고시히가리쌀 다른 곳 보다는 싼이유로 샀는데 ..\n주문과 동시에 도정에 들어가니 참 좋네요\n쌀을 물에 불려해서 밥을하니 좀 질더군요\n그래서 쌀씻어 바로하니 맛있는밥이되었어요.윤기도 좔좔좔..',
 '맛나요',
 '만족합니다.',
 '밥윤기나고 찰지고 맛있어요~^^',
 '쌀 좋아요 받자마자 해봣어요',
 '맛납니더',
 '찰지고 맛있네요~',
 '첫번째구매였는데 밥맛이 좋네요..다음에도 사야겠어요',
 '맛있어요',
 '밥이찰기도없고 금방퍼저요\n이쌁은 만원에 사라고해도\n두번다시 안사요',
 '요건 사야돼 윤기 찰기 밥맛 최고\n온라인으로 쌀은 처음 구매인데요 걱정하면서 시켰는데\n오잉 잘산것같아요 윤기나구요 촉촉하고 찰기도 찹쌀섞은듯\n하네요 인생쌀로 정했어요 이제 이걸로 주욱 사야겠어요\n\n마트서 싼 쌀사니깐 찰기도없고 식으면 누래지고 딱딱해지더라구요 그래서 좋은쌀 사나봐요 ㅜㅜ\n살림고자라 아무생각없이 밥맛이즈뭔들 그냥 살았는데\n세상 헛살았어용 ㅜㅜ\n\n좋은쌀 감사합니다 또 무한 거래할께요 ^---^',
 '비싼값 하네요. 밥맛 짱좋습니다',
 '맛있어요\n꼼꼼하게 포장 되어 왔어요///\n밥맛도 좋네요///',
 '밥맛이 좋아요',
 '좋아요 아가 이유식에 쓸 좋은 쌀 찾다가 샀어요',
 '배송도 빠르고 주문 상품의 품질도 만족스럽네요.',
 '저렴한 가격에 좋은 쌀 사서 넘 좋아요^^',
 '맛잇어요',
 '맛나요',
 '밥맛굿이예요 회사밥안먹고도시락싸가네요',
 '배송이 좀 느렸지만 잘 먹을게요',
 '밥이 찰지고 맛있어요',
 '쌀알갱이가 깨진 것이 좀 많은 듯',
 '찰지고 맛있어요',
 '.',
 '밥맛이 아주 좋아요 다음에도 계속 다시구매할게요',
 '너무맛나여',
 '최고',
 '정기적로 구매 해야겠네요~~\n고시히카리쌀 밥맛이좋다고 하여 구매 하였는데 밥이 맛있네요~~~',
 '밥을해보니 윤기가 자르르 ~~~찰지고 밥맛이 좋네요^^쌀 알이 좀 작다는것 빼고는 최고입니다 종종 이용할께요~~~~~~',
 '최고',
 '최고',
 '아직 먹어보지않아서리 평을 할 수 없네요',
 '최고',
 '밥 맛이 최고 ^^\n저울로 달아보니 20k맞고요 밥 맛도 너무 좋아요\n빠른 배송에 감사합니다 ^~*',
 '이렇게 좋은쌀을 많은분이드셔봤스면합니다',
 '쌀이름을정말잘지으셨네여 밥맛이정말 기찹니다',
 '롯켓배송인데도 하루 늦었는데 포장상태가 엉망 밥못했어요\n최악입니다\n왜 찢어진채로 온건지 몰라요.\n아침에 밥할려고 꺼냈다가 쌀 다 쏟았내요\n치운다고 아침부터 땀좀 흘렸어요\n배송하기전에 검수 안하나요??',
 '맛있는 쌀!\n자취해서 소용량으로 포장된걸로 샀어요\n밥 지어먹었는데 쌀이 넘 맛있네요',
 '밥알이 조금 작아요 기존쌀의 3/2 내지 절반정도',
 '맛이없어요',
 '맛있어요!!\n여름에는 쌀벌레가 많이 생겨서 냉장고에 넣고 먹으려고 소량씩 주문해요:)\n\n밀봉도 편하게 되어 벌레 생길 일은 절대 없겠네요!!\n\n쌀 표면도 대체로 매끄럽고 좋네요~\n\n만들어서 먹어보니까 처음에 윤기가 좌르르르한게 맛있었어용ㅎㅎㅎ\n\n가격도 저렴해서 자취생 분들이 먹기 딱 좋을듯 해요!!\n\n근데 가격이 확실히 저렴하다 보니까 등급은 보통이네여 ㅎ\n\n지인들이 등급에 따라 차이가 많이 난다던데 다음엔 등급 특으로도 한 번 먹어보고 싶어요! ㅎㅎㅎ\n\n밥 맛도 좋고 가격도 저렴해서 다음에도 또 구매하고 싶어요~\n\n좋은 제품 감사합니다^^',
 '포장이 찢어져서 쌀이 흘러나왔네요',
 '시골에서 보내주신 쌀에 잡곡을 섞어먹는데 이번엔 잡곡을 너무 섞었어요...\n까끌까끌한데 시골에서 보내주신 쌀은 다 섞어서 급히 백미 조금만 사자 하고 주문했어요\n소분된거 너무 마음에 드네요',
 '소용량 찾다가 기대없이 샀는데 맛이 좋네요ㅎㅎ\n도정일자도 6월 29일로 괜찮아요.\n\n2021년 7월 29일 구매 5900원',
 '쌀진짜 맛있어요',
 '고시히카리쌀중 최고!\n진짜 맛있어요\n저는 이 브랜드만 먹게되더라구요\n고시히카리중에서도 제일 맛나고 가격도 좋고...\n또 저는 1인가정이라 소분되어있는게 좋은데 그거로도 딱이예요\n찹쌀없어도 쫀득하니 맛납니다 ^^',
 '애벌레 나왔어요\n받아보고 두번째로 밥 지어먹으려고 부었는데\n\n진짜 큰 애벌레가 나왔어요...징그러워요',
 '(구매일자와 구매가격을 적는 이유는 쿠팡 가격 변동이 조금 있는 것 같아 구매하실 때 가격 참고하시라구 적어요!)\n\n\n♥ 구매일자 : 2021. 07. 06.\n\n\n♥ 구매가격 : 11,060원 (21.07.19.에 가격 보니까 10,900원이네요!)\n\n\n♥ 식품 사용\n: 고시히카리쌀은 처음 먹어 봤어요..ㅎㅎ\n윤기가 나고 밥 맛도 괜찮더라구요!\n밥알 크기는 크진 않고 보통인 것 같아요^^',
 '맛있어요',
 '벌레나왔어요\n살아있는 벌레가 나왔어요 애벌레같은데 너무불쾌합니다\n봉투와 쌀이 움직이면 죽은척하고 가만히있다가 몇초지나면 쌀알들 사이로 파고듭니다 포장뜯자마자 맨위에 있어서발견한거지 속에들어있었으면 실컷먹다가 발견했겠어요 얘가 자꾸 쌀알들 사이로 파고들어 안쪽으로 들어가는 습성이 있네요 뜯자마자 사진,동영상 찍고 바로 반품요청했습니다',
 '와이프랑 맛있는 밥해먹으려고 구매했어요\n맛나요~~~',

In [28]:
#03. 텍스트 전처리하기. 
#(1) 텍스트에서 한글, 영어, 띄어쓰기를 제외하고 모두 삭제하기. 
review_data_pp  = [] 
for i in range(len(review_data)) :
    text = re.sub('[^ㄱ-ㅎ가-힣a-zA-Z0-9 ]', '', review_data[i])
    review_data_pp.append(text)
    
#(2) 처리 결과 확인하기. 
review_data_pp

['맛있습니다맛있습니다 잘먹고있어요',
 '아주맛있다까진아니고 괜찮은편입니다',
 '밥맛이 진짜 조아요밥맛이 진짜 조으네요',
 '배송 겁내 빠름',
 '밥맛이 정말 좋아요아쉬운 것은 혈당 관리 때문에 잡곡밥을 먹어야 해서',
 '좋아요 ㅎㅎ잘 먹을께요',
 '밥할 때 냄새가 나고 밥맛이 텁텁하여 썩 좋은 느낌은 아니었습니다',
 '바구미 한마리가 기어다니는걸 보고 실망',
 '도정일이 6월이더라고요쌀이 하얗지 않고 냄새도 좀 나요',
 '아이 이유식하려고 샀어요쌀 상태 좋습니다',
 '굿굿항상 맛잇게 먹고있어요',
 '평택슈퍼오닝알아주는쌀이라주문함',
 '밥냄새도 너무 좋고 맛있어요',
 '쌀 괜찮아요 밥맛도 맛있어요',
 '걱정안해도 되네요 좋아요품질좋아요',
 '맛있음믿고먹는 평택쌀',
 '맛있어요 재구매의사 있습니다',
 '물건이 안왔는데 왜 배송완료죠',
 '전 이쌀구매해먹은지 2년 넘엇어요 밥맛도 최고 윤기도짱',
 '재구매 하려고요',
 '난 고시히카리만 먹는데 어느 순간 매장에 산거랑 인터넷에 산거랑 다른다는 생각이 많이듬인터넷에 산 고시히카리 제대로 된것 못봤슴이것도 별로네요밥 맛이',
 '최애 쌀입니다',
 '가장맛있는쌀',
 '진짜맛있는 쌀입니다',
 '맛있어요',
 '맛 있네요 담에 또 구매 할께요',
 '햅쌀이라는데 재고 느낌',
 '저는 작년부터 이 쌀만 먹는데 쿠팡에 있길래 쿠팡을 통해서도 두번째 구매입니다주문받고 도정해주셔서 기간은 45일 걸리는데 그래도 쌀이 너무 좋아요깨끗하고 밥도 참 이쁘게 고슬고슬 됩니다 다른 쌀 못 먹겠더라구요배송기간이 있어서 잠시 4키로짜리 좋다는 걸로 사서 먹으면서 기다렸는데 별로 이쌀 강섬쌀 등등 다 먹어봤는데 이게 최고에요그래서 떨어지기 며칠전 미리 주문해놓습니당',
 '평택살았을때 맛이 생각나서 시켰는데 최악이네요',
 '맛있어요',
 '찰지고 맛있어요 만족합니다 ',
 '맛나요 완전 맛나요꾸준히 주문해서 먹었는데 한번은 가격이 너무 비싸져서 다른 쌀 먹어봤는데 슈퍼오닝이 제 입맛을 버릇없게 만들었네요 다른쌀은 찰지고 꼬수운 맛이 덜해요한번 맛없다 느끼니 진짜 밥 부지런히 지어먹는데도 왜 이리 닳지 않고 오래 먹는지겨우 다 먹고 다시 슈퍼오닝으로 밥 짓는데 이제 세상 맛난 밥 먹고 있네요꼬숩고 찰지고 거기다 수확한지 한참 됐는데도 도정을 몇일 전 바로해서 보내주니 수분감이 많아서어쩜 품종 때문일지도 밥할때 다른 쌀에 비해 물을 살짝 적게 잡아도 매우 찰지고 촉촉해요예전엔 쌀을 대충 사서 먹었는데 맛난 쌀에 입맛이 길들여지니 좋은점은 반찬에 덜 집중해도 된다는거 나쁜 점우 다른쌀은 먹기 겁난다는거요정도네요어쨌든 앞으로 한참 동안은 요것만 먹을듯해요 가격만 계속 요정도로 유지 해준다면요 여러번 주문해 먹어봤지만 배송 상태도 항상 괜찮았어요비닐팩에 배송 되다 첨으로 박스에 왔던데 다행히 배송 상태 양호 했어요',
 '항상 먹는 거라 리뷰라 필요 옶어요',
 '누가 슈퍼오닝만 먹는다고해서 그게뭔지 찾아서 샀거든요근데 쌀씻으며 보니 때깔부터 다르더니만밥맛 넘좋네요오늘 남편이랑 타마고스시 해먹었는데 진짜 밖에서먹는 초밥맛이었어요도정도 7월에한거고 싱싱하달까다먹고 또사러올게요 기대이상이군요',
 '재구매했어요',
 '밥맛이 좋음',
 '차지고 맛있네요맛있네요 완죤',
 '함께 일하는 언니가 추천해서 이쌀을 샀는데 안좋네요 도정한지도 오래된것같고 밥맛도 별로고요다시는 사먹지 말아야겠네요',
 '썩 좋은지는 모르겠어요',
 '아주 굿아주 맛있어요문의도 친절하게 해주시고요여기서만 시켜먹어요',
 '가격에 비해서 만족해요 마트에서 이보다 더 비싼가격으로 싼 쌀도 안좋았는데 윤기 있고 밥맛도 좋아요',
 '쌀이 깨끗해보이고 밥 맛이 좋습니다쌀이 좋아요',
 '맛있어요두번째 구매했는데 밥맛이 좋아요',
 '이 판매업자의 모든 상품은 시중가보다 엄청 비싸요와 완전히 속았어요2020년 햅쌀 송탄농협 슈퍼오닝 고시히카리4kg1개믿어지나요 48200원 4kg에 48200원 혹 가격 오기 기재까 아닐까 문의했더니 갓 도정한 쌀이고 같은 제품이라도 가격차이가 있다고 쿠팡측에서 확인했다고 상담원 문자옴 판매자의 전화번호 07174246536 이번호는 신호 가자마자 끊어지고 끊어지고010전화인 줄 알았는데 070으로 사작하는 판매업자디엘컴퍼니샵 판매업자 상품을 보니 농산물뿐 아니라 공산품도 와우 어떤거는 따블이네요 8k쌀이면 96400원 20kg이면 241000원 완전 속았어요 어째 이런 사람을 정상적인 판매업자로 등록시켜 주었는지 주의해서 가격이나 중량을 체크하지 못한 제가 밥이였였나요 와 기분 참 어째 이런 사람을코로나 펜데믹 세상 별사람이 다있군판매업자의 또다른 상품 httpsstorecoupangcomvpvendorsA00307116productsvendorNameEB9494EC9798ECBBB4ED8DBCEB8B88productId128902742outboundShippingPlaceId도시락 싸들고 이 판매업자 쿠팡에서 퇴출활동 하고 싶은데',
 '10 키로가 부담스러운 가족에겐적당한 4키로 입니다밀폐용기 5리터 에 쏙들어가서 2달먹으면 딱 알맞아요밥맛도 찰지고 요즘 쿠팡에서 산 쌀들 왠만하면 다 맛있고괜찮더라구요',
 '맛있어요',
 '고시힠카리 젤 마시써쫀득쫀득 윤기 좌르르 ',
 '한번시켜서 먹어보구 재구입햇어요쿠팡서 다른데도시켜서 먹어봣는데여기쌀이제일 나은듯해요 밥맛좋아요',
 '휼륭해요',
 '좋은 쌀입니다개인적으로 안중고시히까리가 최고에요그 다음이 평택입니다맛있습니다도정일이 올해 4월이에요',
 '박스가 너무커서 다 뜯어져서왔네요 ',
 '윤기나는 맛있는밥 매일 잘먹고 있네요',
 '맛있었겠죠엄빠는 브랜드 품종 안 따지고 그냥 단일 품종이면 오케이지만애기 먹는 쌀은 고시히카리그중에서도 좋다하는 브랜드인 수퍼오닝으로 샀어요다 애만 먹여서 맛은 못 봤네요',
 '쌀이 신선하고 밥맛 좋네요배송 빠르고 재구매 할께요쌀이 신선하고 밥맛 좋네요배송 빠르고 재구매 할께요',
 '밥맛이 좋아요고시히카리 매번 먹는쌀입니다 이쌀 먹다 일반쌀 먹기 힘들어요',
 '찰기가 좋고 맛있어요',
 '선물했는데 좋아합니다',
 '안 좋은 후기가 있어서 걱정했는데 찰밥 같이 맛있고 윤기가 있어요 너무 맛있어요',
 '쌀이 싱싱하고 좋아요',
 '밥맛 좋아서 재구매해요쌀알이 촉촉하고 알차며밥맛이 좋아서 재구매 하면서 상품평 남겨요배송도 빨라요',
 '굿이예용',
 '밥 맛있네여',
 '햅쌀이라서 명절에 먹으려고시킨건데도정날짜가 한달하고도 20일이넘은게왔네요비추입니다',
 '3번째 구매입니다밥 잘 지어먹고싶다쌀이 기본이죠솥이 휘슬러여도 쌀이 묵은쌀이면 꽝입니다근데 휘슬러에 슈퍼오닝쌀로 밥 하면 죽음이에요집 가서 밥먹을 생각뿐',
 '지금 계속 슈퍼오닝 고시히카리 먹는데 좋습니다혼자 살면 4kg 둘이 살면 10kg가 좋을 듯 싶습니다',
 '맛나고 좋아요가격도합리적이고요배송도 만족입니다',
 '역시 쌀은 고시히카리신동진은 알도 작고 날리는 느낌이라 식사후 뭔가 불만족스러운데고시히카리 거기다 햅쌀이니까어렸을적 친할아버지께서 힘들게 농사 지어주셨던 그 밥의 맛이 나네요',
 '맛있대요',
 '훌륭했어요',
 '지금 3번째 구매인가4번째인가 잘모르겠지만쌀 맛갠찮아요 세구이지만 집에서 밥을 잘 안먹어서 작은걸 구매하기 시작했는데 딱 좋아요재구매의사 있어요',
 '4kg 단위로 자주 주문해요 맛이 좋아요',
 '먹는 내내 밥맛좋게 먹었어요밥맛이 좋아요',
 '3번 구매입니다배송은 기냥 봉다리에 와서 불안 했는데 안터졌네요',
 '깨끗하고 밥 맛있어요',
 '항상 먹는 쌀이예요 ㅎㅎ 밥이 맛있어요',
 '역시 고시히카리윤기 좔 좔쫀득쫀득여름철 밥 맛 살아나네요',
 '밥하면 질어요고시히카리인데차지거나 달큰한 맛이 없어요그냥 일반쌀이랑 별 차이 없네요고시히카리나 추청쌀은 그냥 밥만 먹어도 달큰하니 맛있어서 이래서 좋은 쌀 사먹는구나 했는데밥하면 물기도 많고 별로였어요물 줄여서 밥 지어도 쌀알이 쫀득하지가 않고 퍼석해요가끔 쿠팡에서 주문하던 당진쌀이 밥맛이 더 좋은 것 같네요전에 먹던 홈플러스 고시히카리를 다시 사야 할 듯 해요19900원에 구입했어요',
 '추천합니다아주 맛있어요',
 '전에 구매해서 먹고 밥맛이 갠찮아서 또 재구매했어요다 먹고나면 재구매의사있어요',
 '두번째구매입니다 뜯기전이지만 바로전에 먹어봤던지라 믿고 재구매했어요 지금까지 여러브랜드 먹어봤지만 젤 괜찮았어요 여름이라 소량으로 샀어요',
 '예전에 먹어보고 괜찮아서 또 샀어용',
 '맛있네요 쌀알도좋구요',
 '사지마세요냄새나서 못 먹겠어요 ',
 '세번째 재구매 입니다 배송 빨라서 좋구요 쌀 상태도 늘 좋아요 2018년 쌀이도 도정일이 2019년 7월19일로 비교적 최근이네요 두 식구고 집에서 먹는 밥이라 해야 아침 한끼 정도라 4kg 주문해도 충분히 한달은 넘게 먹는 것 같아요 재구매 의사 있어요',
 '밥은 아직 안 해봤어요 좀전에 받았는데 구멍나 있어서 쌀알 좀 버리게 됐네요 배송의 문제인건지',
 '밥 맛있어요',
 '갓지은 밥이 윤기가 흐르고 밥맛이 좋습니다내내 이천쌀만 구매해먹다가 바꿔봤는데 품질 좋습니다생쌀이 깨진것도 많지않은거같고 만족스러워 재구매 의사있습니다 계속 이런 품질 상태를 유지해주시길 바랍니다',
 '진 밥 좋아하는 분들 추천꼬들밥 좋아하는데 물을 조금 넣어도 밥이 질게 되네요 맛없진 않은데 제 스타일은 아님ㅎㅎㅎ',
 '깨끗하고 맛있어요',
 '운이나쁜건지보름전 정미된게왔어요하지만 밥맛이좋아요미각이 훌륭한 삼식이라맛난데요',
 '구매해서 지금 밥을 해먹고 있는데 쌀도 갠찮고 좋아요다시 재구매 할려고 장바구니에 담아놨네요 좋아요',
 '늘이것만먹어요가격이적당해서좋아오',
 '밥맛좋은쌀쌀은 고시히카리만 먹어용매번 도정한지 얼마 안된게 와서 맛이 너무 좋음돌지난 아기까지 3가족인데 평일엔 거의 밥을 안먹어서4키로 사면 2달은 먹는듯요것도 정기배송이 있음 좋겠네오',
 '여러가지 쌀을시켜먹엇지만 정말 최고에요말이필요없음 최고쫀득쫀득이렇게 맛잇는쌀은 처음진짜 태어나서 먹어본쌀중 최고최고',
 '배송 빠르고 좋아요',
 '맛있고 운 좋게도 도정일자가 가까운 상품이 배송되어 신선했어요',
 '맛있어요',
 '쌀마다 상품평이 호불호가 갈려서 찾다찾다 이 제품은 안좋은평은 하나도 없는것같아 구매해봤어요 지퍼팩은 아니지만 여름이라 소분해서 냉장고 넣을거라 상관없지싶어요 쌀알도 좋고 찹쌀 조금 섞어서했더니 아이가 먹다 남긴 차가운 상태여도 맛있더라구요ㅎㅎ 여름이라 4키로짜리 샀는데 잘산것같아요',
 '넘나 맛나네요짱맛있어요고시히카리 첨 먹어보는데쌀눈도 살아있도 밥도 쫀득하니 맛나요',
 'GoodGood',
 '맛나요',
 '쌀은 조금씩 여기저기 주문해서 먹는데 송탄 쌀은 벌써 세네번째 구매예요 가격 배송 품질 다 만족합니다 재구매 의사 있어요',
 '맛있네요 쫀득하구',
 '쌀이 터져서 왔어요애 당장 먹여야돼서 그냥 먹이는데 신발장에 쌀 쏟아지고 난리도 아니네요',
 '쌀은 좋아요쌀이 참 이뿌네요다만 제 밥솥이 안좋아요',
 '재구매에요 이때까지 먹어본 쌀중에 젤 맛있음 짱짱맛',
 '터졌어요',
 '6월 2일 주문해서 3일날 받았는데도정일이 5월 31일로 굉장히 최근이네요',
 '밥 맛이 좋아요',
 '밥 맛이 좋아요 고슬고슬 ',
 '보통쌀',
 '윤기있고 찰진 밥맛골든퀸3호 먹다가 이 제품 주문해봤는데 더 맛있네요윤기가 좌르르하고 찰져요',
 '윤기 흐름 항상 특등급만 먹어와서 상등급 괜찮을까 했는데 이것도 괜찮네요',
 '좋아요쿠팡은 배송이빨라너무 좋구쌀도 괜찮네요',
 '초보 주부라 밥 할때 좀 질게 되어서 다시 해봐야 알겠지만 특별히 맛있다는 생각보단 평범했어요 워낙 밥맛이 좋다는 소문만 믿고 주문했지만 밥 짓는것도 실력이 필요한가 봅니다 물 잘 맞취서 맛있고 윤기있는 밥 대접하고 싶네요',
 '밥맛좋은 고시히까리밥맛 진짜 좋아요 강추합니다그런데 배송이 비닐봉투에 담겨왔는데 찢겨있었어요물론 안에 쌀알들도 많이 밖으로 흘러나왔네요배송을 박스포장이나 안전하게 해주면 좋을듯합니다',
 '상품이 터진게 넣어져서왔어요',
 '우선 4kg을 시켜 먹어봤는데저는 별로네요찰기도 없고 다른 고시히카리 쌀과는 다르게맛이 없어요물을 적게 넣어서 그런가 싶어 많이 넣어봤는데도변함없이 푸석해요지금 다른쌀 구매해보려해요',
 '두번째 구매예요 쌀은 조금씩 사서 이것저것 먹어보는 편인데 슈퍼오닝 쌀 마음에 들어 4kg 한번 더 구매했어요 도정일도 최근이고 만족합니다',
 '기대하고 했는데 망해쓰죽밥을했네요비싼가격하는거 갗아오',
 '최고의밥맛선생님진짜 리얼 대존맛이에요전 우리집 밥솥이 안좋아서 이때까지 밥이 그저그런줄알았는데쌀이 문제였어요 안불려도 어쩜 이렇게 찰지고 맛나죠 재구매 무조건힙니다',
 '늘 먹던것입니다',
 'ㅈㄹ먹고있어요',
 '10kg시키다가 작은것 시켰는데 역시 찰져요',
 '만족해요작년11월쯤부터 계속 이쌀먹었는데품종자체가 찰진것같아요다른쌀처럼 똑같이 밥물잡으면밥이 찰기가많아서 질은느낌이나요개인적으로 진밥을 안좋아해서물 살짝 덜잡고 밥하니 딱 좋습니다',
 '윤기가 있고 맛있네요',
 '고시히카리 쌀중 아주 칭찬합니다옛날엔 안성꺼 진짜 좋아했는데어느순간 요즘 고시히카리 쌀이 왜케맛이 없어졌는지 ㅉㅉㅉ 할쯤시켰는데 도정날짜는 326 도착일은 47이네요밥하면 일반쌀은 시간 지나면노래 지는데 이쌀은 꽤 오래 하얗습니다윤기도 찰기도 오래가네요',
 '믿고먹는 고시히카리 쌀이에요쌀 맛있었어요너무 무거워서 쿠팡으로 시켜봤는데요1인가구이며 20190108일에 사서 20190408에 다먹었어요 2끼먹는 기준으로했을때요자취생들이 사서 두고먹기 좋은 량과 좋은 품질쌀벌레도 안나왓어요  너무 상태좋아서 재구매의사있어요고시히카리쌀은 역시나 맛있네요',
 '쌀알이 원래 먹던것보다 작은편임 그리고 짱짱맛',
 '아직 안먹어봤어요비싸지만 밥맛좋다해서 우선 4키로 주문했네요도정일이 11일 이상 전이지만맛있길 기대해봅니다',
 '고시히카리인데전 맛이 별로 였어요제가 생각한 고시히카리가 아녔어요',
 '도정은 1주일 정도 되요 좋아요',
 '후기 꼼꼼히 살피고 주문했어요 다른 쌀보다 가격은 좀 있는편인데 후기가 좋더라구요 아직 밥은 안해봤는데 배송 빠르고 배송 상태도 깔끔히 잘 전달 받았어요 도정일도 최근이예요 밥 해서 먹어보고 맛있으면 재구매 의사 있습니다',
 '상자가 다 찢어져서 배송 됨쌀터졌을까봐 화날뻔',
 '쌀이 윤기나고 밥맛도 좋아요',
 '드셔보세요두번째 주문했구요 3번째 주문 전 후기 남김니다 쌀이 뽀야니 이쁘구요 정말 달아요 남편도 깔이 맛있었어서 맨밥을 계속 씹게된다고 하네요 늘 찹쌀 섞어먹었는데 이제는 그냥 먹습니다 강추요',
 '쌀은 괜찮은데 끈기가 좀 없는것같음',
 '받자마자 밥 해봤는데 정말 찰지고 맛있어요',
 '다시 구매예정 입니다아기 후기이유식 제품으로 구매했어요쌀알이 깨끗하네요',
 '자주 사는 상품입니다 말 할 필요없이 좋습니다',
 '재구매함두번째 구입맛있어서 재구매밥이 찰기가 돌고 촉촉한게 밥맛이 좋아요이천쌀 우렁쌀 별의별걸 다 먹어봤는데 이게 제일 맛있네요',
 '맛은 있는 데 쪼금 비싼 감이ㅎㅎ',
 '맛있는쌀 저렴하게 잘 샀어용고시히카리 쌀이 맛있다고 해서 구매해봣어요 찰밥처럼 쫀쫀하고 진짜 맛있게 지어집니다 사진은 김이 서려서 뿌옇게 나왔는데 추천해요',
 '밥맛이 상당히 좋습니다 적은 포장으로 자주 사먹는게밥맛을 좋게하는 방법인듯',
 '찰지내요',
 '맛있어요 구수한 밥냄새가 나요',
 '굿',
 '찰기있고 맛납니당 값이 나가는만큼 맛있네용',
 '굿',
 '좋아요 밥 맛있어요',
 '밥 맛있네요',
 '쿠팡의 배송은 좋으나 가격이 조금 비싸요 5Kg도 아니고',
 '잘받고 잘먹고 있네요',
 '다음에도시켜먹을거에요밥알이살아잇고맛잇어요',
 '까다로운 울엄마 입맛에 합격',
 '배송포장모두만족밥맛도찰지고맛있어요아쉬운점쌀이부서짐이있어요너무많이씻으면안될듯',
 '고시히카리 치고는 밥맛이 별로에요맛이없다는건 아닌데 아쉬워요 뭔가',
 '특등은 아닙니당 쌀불려서 밥해봐야겠지만특등인줄 알고 샀는데 상등이네요 밥은 아직 안해봐서 ㅋㅋ',
 '밥이 좀 질게 되더라구요 물 양을 좀 다르게 해야할까요 밥맛은 좋아요',
 'jmt',
 '살다살다 쌀씻다가 밥 겁나 맛있것네하기는 처음이네요2년묵은 쌀만먹다가 이거먹으니 밥 개존맛',
 '밥알이 푸석한 게고시히카리 맞나 싶어요갓지은 밥도 별로  ',
 '괜찮아요때깔 좋고 밥하믄 찰지게 잘되요',
 '이제 쌀 유목민 안해도된당밥맛이 꾸르맛이천쌀 철원오대미 우렁이쌀 추정 온갖거 다 먹어봤는데역시 고시히카리 고시히카리 하는 이유가 있네요최고인듯다음날 먹어도 맛있어요  살찔듯',
 '비싸지만 초강추쌀3번째구입솔직히 타4kg 쌀보다 67천원 정도 비싸지만 이거먹다가 딴쌀 못먹겠슴차지고 윤기간지 좔좔거림쌀과 사랑에 빠지긴 처음',
 '이천대왕님쌀만 쭉 먹었는데 쌀 괜찮네요 찹쌀 섞은것처럼 쫄깃하고 맛있네요',
 '아직안먹었어서 밥맛은 모르겠어요쌀알이 굉장히 작은데지금 다이어트중이라 밥알이라도 큰거먹고싶었는데욕심이겠죠 네네',
 '한번두매하고두번째구매입니당역시나배송빠르고 맛잇고부족함이없네용4키로짜리 품절이라 재입고알림해놧어용ㅎㅎ',
 '나 좀 쌀 미식가다 하시는분들 거 꼭 드세요 정말최고밥맛에 민감하신 분들 이거 꼭 드셔보세요 정말 맛잇어요 정말 정말 이게 내가 원하단 쌀밥의 참맛임 ㅋㅋ',
 '맛나요밥맛있음',
 '도정날짜도 신선하고밥맛도좋고배송도빠르고믿을수있는인증마크도잇고어느것하나 단점이없네요계속구매할예정입니당ㅎㅎ',
 '지인에게 추천받아서 구매했는데 정말 밥 맛이 좋네요',
 '쌀자체는 좋은데 물을 잘맞춰야 겠더라구요 보통쌀에비해 좀질게되는 경향이 그치만 밥맛은 최고입니다',
 '맛있습니다윤기는 나는데 쌀알이 조금 작은게 걸리네요 비교적 맛은 좋네요',
 '햅쌀이 필요한 그대들에게 춫천이요 시가댁에서 농사지어서 쌀을 보내주시는데 햅쌀 받기까지 시간이 쫌 남아서 시중쌀을 구매하게되었습니다햅쌀 먹고싶은데 온라인에서 구매하는건 처음이라 망설여졌는데상품포장 겉면에 도정일이 12월 초라고 인쇄되어있어서 믿음이 가네요밥을 지어보니 밥알도 쫀득쫀득하고 맛있습니다쌀떨어지면 재구매의사 있습니다 배송상태  로켓배송으로 다음날 바로 발송 상태 good종이박스로 포장',
 '굿굿',
 '찰밥같이찰지고좋아요',
 '추천합니다밥솥이 좋지않은거같아서 쌀이라도 맛있는거 먹으려구 유명하길래 구매해봤어요그전에 먹던쌀보다 맛있어요ㅎㅎ계속 시켜먹을게요',
 '이천쌀먹다가 최근별로맘에안들어서구매해봤는데 맛있네요더 찰지다고해야되나이천쌀보다더나은것같아요진짜밥이 맛있네요다먹으면 또구매할게요',
 '고시히카리 한번 사먹어보고 고시히카리 품질에 반해서비싸도 이품종만 먹어요정기배송하던게 품절이되어서 요거한번 사봤는데역시 이것도 괜찮네요잘 먹겠습니다',
 '맛나요 이유식으로 구매 했오요',
 '맛있어요',
 '햅쌀이라그런지 밥이 윤기나고 맛있어요',
 '밥에 윤기가 돌고 맛나네요',
 '맛있네요',
 '맛있습니다',
 '햅쌀이라 맛있어요',
 '맛있어요쌀이 깔끔허네요근데 쌀알이 조금 작은 듯 하네요',
 '재구매의사높음고시히카리는 처음인데 밥 맛있네요또 살 것 같습니다',
 '맛있어요',
 '항상 시켜먹는 썰이에요쫄깃하고 맛있어요',
 '반 존맛탱구리 완전 강추',
 '쌀이 넘좋아요밥솥에 보온해두어도 쌀알이 살아있어요',
 '고시히카리 쌀이 유명해서 구매해서 먹어보니 맛있습니다재구매 의사 있습니다',
 '추천 밥맛조하상태좋고 깨끗 밥도 찰지고 맛나요 굿굿',
 '불순물 뜨는것 없고 깨끗해서 좋아요',
 '쌀이 정말 찰지고 맛나네요 맛있어요',
 '쌀사러가기 귀찮아서 시켜봤는데 기대이상이었습니다 햅쌀답게 찰지고 맛있어요 강추합니다',
 '슈퍼오닝ㅎㅎ나쁘지 않아요 날짜도 최근이고 맛도 괜찮고저흰 여기에 잡곡 섞어 먹는데 아이도 어른도 잘먹고 있습니당 ㅎ',
 '좀 비싸서 망설였는데 쌀 좋아용눈도 하얗고 밥해봤ㄴ데 찰밥처럼 찰지네요',
 '밥맛있게 잘되서 좋아요',
 '좋습니다찰진 밥맛 좋아요',
 '쌀을 까다롭게 고르는 편인데 급하게 쌀이 떨어져 로켓배송이 되는주에 주문했는데 예상보다 맛나고 좋으네요 추천합니다',
 '햇반만 먹다 최근 밥해먹으려고 주문햇는데 쌀이 맛나요상품평은 없고 긴가민가 한번 주문해봣어여 로켓배송도 되고해서 주문햇는데 완전만족합니다 쌀눈이 살아있고 쌀 빛깔도 살아있네여 사진 원래 안찍는데 첨으로 찍어봣네여 흑미좋아해서 같이 주문해봣네여진짜 밥이 맛있어여포장도 깔끔하게 되있었어요',
 '밥이 윤기나고 맛있습니다',
 '밥맛이 최고예요단골될듯합니다',
 '기버터 가격이 좀 비싸요조금 큰용량있으면 좋겠어요',
 '풍질이 별로에요',
 '밥맛이 너무 좋아요밥맛이 좋네요',
 '밥맛좋아요',
 '좋아요 좋아요 좋아요',
 '밥 맛 정말 좋네요 이렇게 좋은 쌀 처음 먹어보네요재 구매 확실하네요',
 '밥맛이 좋아요',
 '괜찮은거같아요',
 '추천해요밥맛이 너무 좋아요',
 '기존에 임금님 이천쌀 먹었고요가격이 조금 덜 부담스러운 고시히카리도 한번 먹어보자 해서 구매했는데 맛도 좋고요한동안 자주 시켜먹게 될것 같아요',
 '대체적으로 괜찬아요 배송이 좀만더 빠르면 합니다',
 '고시히까리 이것도 특상중하로 구분되는줄 이제야 알았네요이번에 산 물건은 상으로 표기되어 있는데 가산농협엔 특품은 없나요 다른곳 쌀보다 23천원 싸길래 샀는데 기왕 젤 비싼 고시히까리 먹는 사람이 특품을 찾지 하등급 찾겠어요',
 '고실고실빛나고졸깃 실하다',
 '밥맛이너무좋아요',
 '윤기좋고 맛도좋고감솨요',
 '너무 맛있었구요또재구매해서 먹을꺼예요',
 '깨끗해요20키로 구매 했습니다쌀 깨끗하니 좋네요밥맛도 괜찮아요배송도 빠르고 꼼꼼하게 포장 되서 왔습니다다시 구매하게 된다면 이제품 택하겠습니다',
 '맛있어요잡곡과 섞어도 찰지네요맛있게 잘 먹을게요',
 '두 번째 구입해요 밥 맛 좋아요',
 '후회 없을 밥맛',
 '정말 쌀이윤기나고 맜있습니다처음엔 비싸다 생가했는데 밥맛에 비하면비싼것이아니네요잘먹을게요',
 '밥맛이 너무 좋아서 밥 할 맛 납니다감사합니다많이 많이 파세요',
 '밥맛 조흠이전에 철원쌀 먹었는데 역시 맛이 좋음 대신 물을 조금 적게 넣어서 해야 좋은 것 같음 기존의 물량으로는 조금 질은 느낌이 옵니다',
 '감사합니다밥맛좋아요 두그릇씩 먹는답니다물은 좀 평소보다 적게 넣어야할듯',
 '비싼만큼 완전 찰지고 맛있어요',
 '너무좋아요',
 '고시히까리쌀 맛있어요',
 '첫째 구매한 쌀은 괞찬았는 데두번째구매한 이번 쌀은 형편없어요마치 동남아에서 수입한 쌀처럼날라다닙니다',
 '고시히카리 밥맛좋아요 최고',
 '쌀이 딱 어제떨어졌거든용ㅋ신속하게 배송해주신덕에 저녁밥을 해먹을수있었네용후기보니까 다들 맛있다고 칭찬하시기에 믿고주문했는데용너무 촉촉하고 찰지고 좋아용퇴근하고 늦게와서 후다닥 씻어서 불릴시간도 없이 쾌속으로했는데도 너무 맛있게 잘된거있죵다음에도 또 다음에도 쭈욱 요쌀만 찾을거같아용최고',
 '품질이 좋아 확실히 밥이 윤기도 있고 맛있어요',
 '좋은 품질과 엄청 빠른 배송상품평이 좀 늦었네요 좋은 품질과 빠른 배송 대만족입니다',
 '찰지고 싸고 좋아요',
 '밥맛좋아요찰기굿윤기굿달큰해요',
 '다른쌀 못먹음중독주위최고의 밥맛',
 '재구매했는데 넘 좋네요 고맙습니다',
 '단일품종이긴 한데 품질이 하네요 구매시 몰랐음품질의 하등급 표기는 상품설명 화면에 나와있었는지 보지도 못했네요 제품포장의 하등급표기를 보니 왠지 쌀이 안좋아보입니다 밥을 하면 윤기는 별로 없어도 먹을만하네요',
 '녹색날알이 너무많았어요',
 '또 주문했습니다 다음에 또 주문할게요',
 '사실 쌀인 줄 알고 현미 주문했어요ㅎㅎ 평생 먹을 분량의 현미인듯',
 '쌀 맛있어요또 주문합니다',
 '초록색 현미가 많이 섞여 있어서 별루입니다촉록색 현미가 많다는건 다 여물지않은벼를 수확했기 때문입니다 실망입니다잘은 안해도 바르게는 해야지요',
 '빠른배송 좋은 상품빠른배송 좋은 상품',
 '화성의 조암 고시히까리가 맞나요이런 쌀은 한번도 못봤던품질에서 맛과 향이 너무 다릅니다오랫동안 먹어왔던 만큼 어느정도 느낌이 있는데 너무 달라요물이 조금 많으면 떡밥되고 조금 덜넣으면 밥알 자체가 까슬하고 어디 외국 수입 쌀 인가요햇살마을 방앗간 이름인가요상점 이름인가요그 동안 최고 품질 좋은 쌀이라 생각했는데 정말 실망했어요 안 사고 싶네요 ',
 '2020년 햅쌀 조암농협 화성고시히카리2020년 햅쌀 조암농협 화성고시히카리 1개 10Kg',
 '좋아요',
 '물건 참 좋네요좋은물건 싸포장 깔끔했어요물건 참 좋네요좋은물건 싸게 잘샀습니다 추천드려요',
 '이쌀먹을때 똥 아주 잘쌋음',
 '보보통약가비쌈10키로인지 알고 삿는데 약간 맛있음',
 '기존에 먹었던 현미보다는 찰기가 있어 만족합니다',
 '밥 맛이아주좋아요 윤기나고 찰지고',
 '당일 도정해서 그런지 밥맛이 최고입니다 좀비싸지만 최고입ㄴ다 적극 추천합니다',
 '배송도 빠르고 제품 품질도 좋았어요 만족합니다',
 '가격은 좀쎄지만 밥맛하나 만큼은 좋아요',
 '도정한지 오래지않아 좋아요밥 이 차지고 맛도좋아요 3년째 단골이네요',
 '정말 이번에는 더 찰지고 맛나요  주위에 소개도 하고 비싸도 이거만 먹을래요',
 '윤기가 좌르르밥맛 좋아요',
 '쌀이 찰지고 맛있습니다 다음에도 구입하고 싶어요',
 '정말맛없는쌀입니다 그냥씰이네요 요번에 뜯구보니 그전에먹던쌀이여서 너무내자신을 잘보지않쿠 비씨니당근맛이겟다하구산게실수이네요 뜯어으니 어쩔수읍이 몇달을먹어야겟네요',
 '감사합니다 ',
 '너무 맛있어서 엄마네도 뱌달시켜드렸어요 ',
 '밥맛 나는 쌀제일 맛있는 쌀이예요 그냥 김치만 갖고도 밥이 맛있어서 잘 먹을 수 있는 쌀입니다',
 '확실히 때깔이 다릅니다어렸을때 농사지어 먹어본 쌀밥입니다쌀뜨물이 뽀얗게 나오네요밥만먹어도 맛있어요 ㅎㅎ',
 '아주 좋아요쿠팡에서 구매한 쌀중엔 최고의품질 입니다',
 '맛도 품질도 쵝오항상 먹는 쌀여기만큼 쌀 맛있고품질 좋은곳아직 못 찾았어요여기쌀이 쵝오요',
 '저희집은 이 쌀만 먹어요가격이 좀 비싼 편이지만 밥맛이 끝내줘요',
 '쌀윤기죽입니다가격대가 있긴하지만 아깝지않아요밥만 먹어도 너무 맛있어요',
 '늘시켜먹는 쌀 밥이 달아요',
 '밥 맛있어요 쌀알도 만족하구요',
 '맛있어요',
 '95점 ',
 '20키로쌀을 주문했는데 옮기다 가벼워서 무게를 재보니 19kg 이네요 황당하네요돈을 1키로만큼 환불해주시던지 주소로 1kg 따로 더 보내주세요신뢰를 바탕으로 지금까지 5번정도시킨것같은데 무게 재보지 않았는데 지금까지 먹었던것도 의심되네요담부턴 못시켜먹을것같네요 속여서팔지맙시다',
 '아직 먹어보진 않았는데 괜찮을것 같아요',
 '기분 별로 먹어보고쌀은 먹던거 남아서 먹고 먹어야되서 아직은 않먹어 밨지만 상품평보고 주문했으니 맛나겠지요 먹어보고 맛없으면 마저 남길께요 맛나면 패스 근데 박스에 포장되서 왔는데도 불구하고 박스는 괜챦은데 옆구리가 조금 터져왔네요 그럼 터진걸 보냈다는 얘기인감 기분좀 언짠아 별 4개요 안만 씻어먹는거라해도 먹는 주식을 터져보내심 아니되오',
 '여태껏 먹은것중 가장 괜찮은것같아 또 구입하고싶네요처음 구입해봤는데찰지고 윤기도 좋고 밥맛이 상당히 좋네요또 구입하고 싶습니다',
 '맛이 있어요빨라서 좋아요',
 '다른쌀보다 밥통에해놓으면색이 바라지않음',
 '너무느리다 느려도 너무 느리다 돈이 이중으로들고 욕만',
 '쌀이 품질이 너무 좋아서 일년넘게 시켜 먹고있는데 배송배송지연으로 마트에가서 쌀 사서왔음배송날짜을 지켰으면 하는 바람입니다',
 '가산 농협 고시히까리쌀 최고입니다 바로 도정 해서 주니까 밥맛은 최고입니다',
 '윤기돌고 찰기도 있어서 꼭 이 제품을 애용하고있어요',
 '많은 쌀을 먹어본결과 고시히까리쌀 최고입니다',
 '쌀이 너무 많이고 친정엄마가 제일 좋아하는 쌀요',
 '쌀알이 고르고 밥에 윤기가 쟈르르 흘러요그동안 시켰던 어떤ㅈ비쌌던 쌀보다 훨씬 좋아요',
 '처음 시켜본 품종인데 맛있어요쌀 윤기도 흐르고 식어도 색이 변하거나 밥알이 날리지 않아 좋아요',
 '항상 먹는쌀 맛있어요',
 '3번째구매쌀굿',
 '여러번 재구매합니다 밥맛최고예요저희는이살만구매합니다',
 '세번째 배송으로 먹고 있어요 맛나요',
 '밥맛이 좋아요 농부님들 수고하셨어요',
 '좋아요계속 구매하여 먹고있는데 좋습니다',
 '지금까지 여러번째 구매해봤는데 여기 쌀이 젤 맛있었어요항상 변하지 않는 맛과 정성에 감사해요',
 '다른쌀 섞이지않고 고르고 밥도맛잏머요',
 '쌀을 택배하는사람이 내동챙이 쳐놓고 가서 터져있었네요 어이없음',
 '굿 쌀진짜 좋아요두번째구매친정엄마가 밥맛이 촣다고에서 또구매했어요진짜내가먹어보고 밥맛이 최고굿 촣은쌀 감사해요또 재구매 생각있습니다',
 '밥맛도 좋고 좋아요',
 '밥맛이 맛있어요',
 '누룽지쌀을 다른곳에서 구입해 먹었는데 품절이라 여기저기 뒤져보다 평이 좋아서 구매를 했어요그런데 생각보다 밥맛도 좋고 도정한지 얼마 안되어서 그런지 구수하면서 윤기도 흐르는게 정말 괜찮았어요두번째 구매합니다',
 '윤기가 반지르르 밥맛이 좋아요',
 '쌀 느무 맛있어요ㅎㅎ밥할때 고소한 냄새가 진동해요고슬고슬하게 지어서 김만 싸먹어도 넘나 맛있네요햅쌀도 아닌데햅쌀 나오면 얼마나 맛있을까요ㅎㅎ비싸도 재구매 할거에요',
 '친정에 쌀이 떨어져서 구매했는데찰지고 맛있다고 하네요밥만먹어도좋다고하십니다재구매 의사있음',
 '찰지고 맛있어요',
 '먹어보지 않아 모르겠어요',
 '항상구매한 상품입니다',
 '오자마자씻어서 전기밥솥에밥을 했는대 너무찰지고 맛있네요압력밥솥에하면 더찰지고맛날거같네요구수한밥냄새식욕이땡기네요 ㅎㅎ',
 '찰지고 맛있어요20kg사서 밥맛이 없으면 그것만큼 난감한일이없을텐데맛있어서 다행이에요우리쌀 좋아요다른쌀 섞지말고 팔아주세요쭈욱사먹을수 있게 해주세요',
 '가격대비 배송도 늦고 품질도 가격대비 별로',
 '배송빠르고 물건 마음에듭니다',
 '밥맛이 좋아요앞으로 이쌀로 바꿔야겠어요',
 '좋아요 ',
 '구매한 이유는 1달전에 한번먹어보니 쌀이 정말좋더군요 추천합니다',
 '포천 고시히까리쌀 먹어보고 다시 주문합니다 밥맞 최고입',
 '좋네요',
 '배송오는날에 안오고 하루 늦게오는게 좀불편햏어요',
 '좋아요다른지역 쌀보다 좋은 편입니다',
 '가격대비 품질 별로네요재구매 안합니다',
 '두번째구입해요 맛있고만족합니다',
 '이글을 보시는분들 절대로 사지 말라고 하고 싶네요고시히까리라고 비싸게 샀는데 영 안 좋네요쌀알이 찹쌀처럼 불투명하고 밥을 해도 맛이 없어요돈 아까워 죽겠어요20키로를 언제 다먹나 걱정이에요',
 '없는 밥맛도 땡기는 찰지고 달달한 쌀밥입니다고시히카리 비싸서 그렇지 가격만 아니면 고민할 필요없는 찰지고 맛난 쌀입니다 암튼 쌀가격 좀 내렸으면 좋겠어요 이제 보통쌀은 못먹게 된 높아진 입맛재구매합니다',
 '윤기흐르고 맛있어요',
 '상등급이라 기대했는데 결과는실망',
 '보통밥 맛이 좋은건 모르겠고 그냥저냥 괜찮아용나쁘진않습니다',
 '좋아요좋아요좋아요좋아요좋아요',
 '쌀알도좋고 밥맛도 좋아요 지금껏 먹은 쌀 중에으뜸입니다',
 '평이 좋아 샀는데  아직 해먹진 않아서 ',
 '배송빠르고 물건 마음에듭니다',
 '맛있어서 재구매합니다',
 '쌀이 쫀득하고 맛나요 재구매 할라고요',
 '비싼만큼 그값을 합디다',
 '상품평보고 샀는데 맛있습니다',
 '가산농협 2018년 햅쌀 포천 고시히카리쌀1개20kg수욜 주문하고 토욜 받앗네요연휴도 끼고 좋은 제품 부탁도 드리고일단 마트에서 고시히카리20kg만 항상 사먹었는데 마트에서 사면 잡곡이랑 섞어서 보관하다가 갑자기 흰쌀밥에 김치 얹어서 먹고 싶다는 충동ㅋ살이야 찌던 말던 일단 남아있는 쌀도 있는데도 불구하고 구매했네요상품평가격이것저것 따지고 비교하고 그나마 여기가 딴데보다 상품평도 좋고해서 일단 시켜보자는 맘에 첫구매에도 불구하고 20kg 시키면서 좋은 제품 부탁 글을 남기니 바로 도정해서 보내주신다는 답글연휴가 끼어서 3일만에 도착했는데 박스에 포장되서 배달이 왔더라고요보는 순간 기분이 좋아지고 작은거에도 신경을 쓰신다는 생각에 얼릉 풀어서 보관통에 담아서 정리하고 밥을 했는데 밥솥뚜껑을 여는순간 하얀 쌀밥이 군침돌게 하더라고요그 자리서 한그릇 떠서 김치랑 순삭해버렸네요ㅋ일단 밥이 달다고 해야되나 찹쌀 섞은것처럼 밥이 찰기도 있네요신랑도 맛잇다고 아주 흐뭇해하네요기존에 있는 쌀과 비교해서는 당일도정 맞는것 같고 밥맛이 넘넘 조아요밥할때 물은 기본보다 쫌 덜 잡는게 맞는거 같네요조은 쌀맛잇는 쌀보내주셔서 감사하고 담에 재구매 100입니다마니 파세요',
 '좋아요',
 '만족합니다쌀이 윤기있고 밥맛이 일반쌀보다 찰기있고 맛나요 재구매합니다 품질이 동일하길 기대해봐요',
 '역시 고시히가리쌀고시히가리쌀 다른 곳 보다는 싼이유로 샀는데 주문과 동시에 도정에 들어가니 참 좋네요쌀을 물에 불려해서 밥을하니 좀 질더군요그래서 쌀씻어 바로하니 맛있는밥이되었어요윤기도 좔좔좔',
 '맛나요',
 '만족합니다',
 '밥윤기나고 찰지고 맛있어요',
 '쌀 좋아요 받자마자 해봣어요',
 '맛납니더',
 '찰지고 맛있네요',
 '첫번째구매였는데 밥맛이 좋네요다음에도 사야겠어요',
 '맛있어요',
 '밥이찰기도없고 금방퍼저요이쌁은 만원에 사라고해도두번다시 안사요',
 '요건 사야돼 윤기 찰기 밥맛 최고온라인으로 쌀은 처음 구매인데요 걱정하면서 시켰는데오잉 잘산것같아요 윤기나구요 촉촉하고 찰기도 찹쌀섞은듯하네요 인생쌀로 정했어요 이제 이걸로 주욱 사야겠어요마트서 싼 쌀사니깐 찰기도없고 식으면 누래지고 딱딱해지더라구요 그래서 좋은쌀 사나봐요 살림고자라 아무생각없이 밥맛이즈뭔들 그냥 살았는데세상 헛살았어용 좋은쌀 감사합니다 또 무한 거래할께요 ',
 '비싼값 하네요 밥맛 짱좋습니다',
 '맛있어요꼼꼼하게 포장 되어 왔어요밥맛도 좋네요',
 '밥맛이 좋아요',
 '좋아요 아가 이유식에 쓸 좋은 쌀 찾다가 샀어요',
 '배송도 빠르고 주문 상품의 품질도 만족스럽네요',
 '저렴한 가격에 좋은 쌀 사서 넘 좋아요',
 '맛잇어요',
 '맛나요',
 '밥맛굿이예요 회사밥안먹고도시락싸가네요',
 '배송이 좀 느렸지만 잘 먹을게요',
 '밥이 찰지고 맛있어요',
 '쌀알갱이가 깨진 것이 좀 많은 듯',
 '찰지고 맛있어요',
 '',
 '밥맛이 아주 좋아요 다음에도 계속 다시구매할게요',
 '너무맛나여',
 '최고',
 '정기적로 구매 해야겠네요고시히카리쌀 밥맛이좋다고 하여 구매 하였는데 밥이 맛있네요',
 '밥을해보니 윤기가 자르르 찰지고 밥맛이 좋네요쌀 알이 좀 작다는것 빼고는 최고입니다 종종 이용할께요',
 '최고',
 '최고',
 '아직 먹어보지않아서리 평을 할 수 없네요',
 '최고',
 '밥 맛이 최고 저울로 달아보니 20k맞고요 밥 맛도 너무 좋아요빠른 배송에 감사합니다 ',
 '이렇게 좋은쌀을 많은분이드셔봤스면합니다',
 '쌀이름을정말잘지으셨네여 밥맛이정말 기찹니다',
 '롯켓배송인데도 하루 늦었는데 포장상태가 엉망 밥못했어요최악입니다왜 찢어진채로 온건지 몰라요아침에 밥할려고 꺼냈다가 쌀 다 쏟았내요치운다고 아침부터 땀좀 흘렸어요배송하기전에 검수 안하나요',
 '맛있는 쌀자취해서 소용량으로 포장된걸로 샀어요밥 지어먹었는데 쌀이 넘 맛있네요',
 '밥알이 조금 작아요 기존쌀의 32 내지 절반정도',
 '맛이없어요',
 '맛있어요여름에는 쌀벌레가 많이 생겨서 냉장고에 넣고 먹으려고 소량씩 주문해요밀봉도 편하게 되어 벌레 생길 일은 절대 없겠네요쌀 표면도 대체로 매끄럽고 좋네요만들어서 먹어보니까 처음에 윤기가 좌르르르한게 맛있었어용ㅎㅎㅎ가격도 저렴해서 자취생 분들이 먹기 딱 좋을듯 해요근데 가격이 확실히 저렴하다 보니까 등급은 보통이네여 ㅎ지인들이 등급에 따라 차이가 많이 난다던데 다음엔 등급 특으로도 한 번 먹어보고 싶어요 ㅎㅎㅎ밥 맛도 좋고 가격도 저렴해서 다음에도 또 구매하고 싶어요좋은 제품 감사합니다',
 '포장이 찢어져서 쌀이 흘러나왔네요',
 '시골에서 보내주신 쌀에 잡곡을 섞어먹는데 이번엔 잡곡을 너무 섞었어요까끌까끌한데 시골에서 보내주신 쌀은 다 섞어서 급히 백미 조금만 사자 하고 주문했어요소분된거 너무 마음에 드네요',
 '소용량 찾다가 기대없이 샀는데 맛이 좋네요ㅎㅎ도정일자도 6월 29일로 괜찮아요2021년 7월 29일 구매 5900원',
 '쌀진짜 맛있어요',
 '고시히카리쌀중 최고진짜 맛있어요저는 이 브랜드만 먹게되더라구요고시히카리중에서도 제일 맛나고 가격도 좋고또 저는 1인가정이라 소분되어있는게 좋은데 그거로도 딱이예요찹쌀없어도 쫀득하니 맛납니다 ',
 '애벌레 나왔어요받아보고 두번째로 밥 지어먹으려고 부었는데진짜 큰 애벌레가 나왔어요징그러워요',
 '구매일자와 구매가격을 적는 이유는 쿠팡 가격 변동이 조금 있는 것 같아 구매하실 때 가격 참고하시라구 적어요 구매일자  2021 07 06 구매가격  11060원 210719에 가격 보니까 10900원이네요 식품 사용 고시히카리쌀은 처음 먹어 봤어요ㅎㅎ윤기가 나고 밥 맛도 괜찮더라구요밥알 크기는 크진 않고 보통인 것 같아요',
 '맛있어요',
 '벌레나왔어요살아있는 벌레가 나왔어요 애벌레같은데 너무불쾌합니다봉투와 쌀이 움직이면 죽은척하고 가만히있다가 몇초지나면 쌀알들 사이로 파고듭니다 포장뜯자마자 맨위에 있어서발견한거지 속에들어있었으면 실컷먹다가 발견했겠어요 얘가 자꾸 쌀알들 사이로 파고들어 안쪽으로 들어가는 습성이 있네요 뜯자마자 사진동영상 찍고 바로 반품요청했습니다',
 '와이프랑 맛있는 밥해먹으려고 구매했어요맛나요',
 '고슬고슬전에 시킨 쌀은 돌도 가끔 씹히고 그랬는데본가에 살았을때 엄마가 고시히카리 쌀만 고집하던게 생각이나서 시킴1키로 금방 먹었지만 돌도 안씹히고 밥도 윤기나고 맛있다',
 '급해서 시켰는데 나름 괜찮았어요',
 '밥지우면 너무 맛있어요',
 '밥이윤기나고 맛있어요',
 '지퍼백 아래쪽이 찢어져서 쌀이 많이 새서 왔어요쿠팡 비닐봉지에 동그란 구멍이 있어서 그 밖으로도 쌀이 많이 빠져나갔어요저만큼 찢어졌으면 포장할 때 쌀이 흘렀을 것 같은데',
 '상품은 좋은지 몰라도 다 터져서 와서 반을 버렸네요  너무 아깝습니다',
 '맛있어요쌀알 상태가 좋아요적당히 구수하고 윤기가 돕니다밥을 자주 해먹지 않아 1kg정도가 딱 좋아요마음에 들어요',
 '밥맛 좋아요일주일에 한두번 밥해먹는 집에 넘 편해요지퍼백이라 그냥 밀봉되니 통에 옮겨담지 않아도 되고 편하네요',
 '맛있어요쌀이 쫀득쫀득하고쌀 종류랑 등급을 같이 고려하고구매하는 편인데맛있습니다아기가 밥만 집어먹어요',
 '밥지엇더니 맛있어요 잡곡도 잘어울려요',
 '굿와 역시 모찌모찌하고 맛있어요 하나 사고 다시 구매했어요ㅋㅋ',
 '맛있었어요쌀알이 작고 윤기돌았네요쌀은 똑 떨어졌는데 쌀 배송까지 3일정도 남아서1kg 구입해 먹었는데 3인기준 가족 딱 34일치 였던것 같아요',
 '소용량이라서 좋은 고시히카리강화 고시히카리 밥 좋아하는데 막 엄청 맛있다 느낌은 아닙니다그래도 일반미 보다 고시히카리라고 써있어서 그런지 맛있는 느낌적 느낌ㅋㅋㅋ 여주쌀 한참 먹다가 갑자기 다른쌀 먹으면 맛없더라고요근데 이건 맛없다 정도는 아니고 엄청 맛있는것도 아니고 적당히 좋습니다윤기 좔좔 이런건 잘 모르겠습니다 잡곡섞어먹습니다무난한맛인데 고시히카리가 좋다고하니까 믿고 먹습니다쌀도 산패되면 독성이 나온다고해서소용량씩 자주 사먹는 편입니다소용량이라 좋고 가격도 괜찮네요',
 '잡곡이랑 섞어먹으려고 샀어요 찰지네요',
 '고시히카리 한번 먹어봤는대맛있어서 생각나 한번 사봄압력 밥솥으로 한듯 햅쌀 맛 좋구요역시 쫀뜩하고요 밥맛이 진짜 조아요1키로라 3일 이면 뚝딱 놀럭가서 먹기 좋구요지퍼로 되어있어 보관 아주 좋아용 쌀알은일반 쌀보다 조금 굵음 그래서 식감이 있어 너무 조음일반 쌀보다 햅쌀이라 좀더 배부른감 있음 맛나요윤기 있고 매끈함 촉촉 매끈 쫀득',
 '아직 먹어보진 못했지만 맛있을거 같아 기대 됩니다2키로 또는 5키로를 주문하고 싶었지만 품절로 인해 1키로과자 한봉지 크기이고 생각보다 작음 지퍼팩 포장이여서 너무 좋아요 자취하는 사람한텐 적당한듯하네요',
 '대한민국만세집에 쌀이 떨어져 급히 먹을 요량으로 생각없이 용량 가벼운 1kg짜리 우리집밥선생 쌀을 구매했다 31절 당일 배송된 쿠팡 포장지를 뜯어봤는데 눈에 보이는 고시히카리 라는 일본어아 나는 왜 이걸 보지 못했단 말인가그 날 나는 차마 쌀을 먹지 못하고 그냥 밥을 굶어버렸다 우리 선조들의 피와 땀이 어린 항일정신을 고작 굶주림 하나에 이토록 패대기를 칠 줄이야',
 '고시히카리쌀맛나요',
 '1인가구이고 고시히카리는 처음 먹어보는데평이 안좋아서 별로 기대를 안했습니다그런데 밥 너무 맛있는데요 저는 만족해요ㅎㅎ',
 '특등급답게 매우 맛있습니다',
 '안성맞춤쌀완전맛있어요 별5개드려요',
 '특등급 답네요 굿',
 '재구매하는중인인데처음보다는 조금 못한것같아요괜찮아요 ',
 '겉으로 보기에는 괜찮은데 맛은 그냥그럼그냥 일반쌀같아요 구수하거나 단맛이 좋거나 쌀알질감이 좋거나 한건 없음 평소 집에서 먹는 쌀이 맛없었는데 큰 차이가 없다',
 '맛있어요맛있어서 요고만 시켜먹어요',

In [29]:
#04. 자연어처리해 형태소 분석하기.
#(1) okt(twitter) 객체 정의하기
okt = Okt()

#(2) 한 레코드 씩 형태소 분석하기.  
extract_value_list = []
for i in range (len(review_data)) :
    extract_value = okt.morphs(review_data[i], stem=True, norm=True)
    extract_value_list.append(extract_value)

#(3) 처리 결과 확인하기. 
extract_value_list

[['맛있다', '\n', '맛있다', '잘', '먹다'],
 ['아주', '맛있다', '아니다', '괜찮다', '편입', '니', '다'],
 ['밥맛', '이', '진짜', '좋다', '~', '\n', '밥맛', '이', '진짜', '좋다', '~'],
 ['배송', '겁내', '빠르다'],
 ['밥맛',
  '이',
  '정말',
  '좋다',
  '.',
  '\n',
  '아쉽다',
  '것',
  '은',
  '혈당',
  '관리',
  '때문',
  '에',
  '잡곡',
  '밥',
  '을',
  '먹다',
  '하다',
  '...'],
 ['좋다', 'ㅎㅎ', '\n', '자다', '먹다'],
 ['밥',
  '하다',
  '때',
  '냄새',
  '가',
  '나다',
  '밥맛',
  '이',
  '텁텁하',
  '여',
  '썩',
  '좋다',
  '느낌',
  '은',
  '아니다'],
 ['바구미', '한', '마리', '가', '기다', '보고', '실망'],
 ['도정',
  '일이',
  '6월',
  '이더라고요',
  'ㅜㅠ',
  '\n',
  '쌀',
  '이',
  '하얗다',
  '않다',
  '냄새',
  '도',
  '좀',
  '나요',
  'ㅠㅠ'],
 ['아이', '이유식', '하다', '사다', '~', '\n', '쌀', '상태', '좋다', '!'],
 ['굿굿', '\n', '항상', '맛', '잇다', '먹다'],
 ['평택', '슈퍼', '오', '닝', '알아주다', '쌀', '이라', '주문', '함'],
 ['밥', '냄새', '도', '너무', '좋다', '맛있다'],
 ['쌀', '괜찮다', '밥맛', '도', '맛있다', '!'],
 ['걱정', '안해', '도', '되다', '좋다', '\n', '품질', '좋다', '.'],
 ['맛있다', '\n', '믿다', '먹다', '평택', '쌀'],
 ['맛있다', '.', '재다', '의사', '있다', '.'],
 ['물건', '이', '안', '오다', '왜', '배송', '완료', '죠', '??'],
 ['전',
  '이',
  '쌀',
  '구',
  '매',
  '해먹',
  '은지',
  '2년',
  '넘엇어',
  '요',
  '밥맛',
  '도',
  '최고',
  '윤기',
  '도',
  '짱'],
 ['재다', '하다', '~'],
 ['난',
  '고시히카리',
  '만',
  '먹다',
  '어느',
  '순간',
  '매장',
  '에',
  '사다',
  '인터넷',
  '에',
  '사다',
  '다르다',
  '생각',
  '이',
  '많다',
  '이듬',
  '.',
  '\n',
  '인터넷',
  '에',
  '산',
  '고시히카리',
  '제대로',
  '되다',
  '못봤슴',
  '.',
  '\n',
  '이',
  '것',
  '도',
  '별로',
  '네',
  '요',
  '.',
  '밥',
  '맛',
  '이',
  '.'],
 ['최애', '쌀', '이다'],
 ['가장', '맛있다', '쌀'],
 ['진짜', '맛있다', '쌀', '이다'],
 ['맛있다'],
 ['맛', '있다', '..', '담', '에', '또', '구매', '하다'],
 ['햅쌀', '이라는', '데', '재고', '느낌'],
 ['저',
  '는',
  '작년',
  '부터',
  '이',
  '쌀',
  '만',
  '먹다',
  '쿠팡',
  '에',
  '있다',
  '쿠팡',
  '을',
  '통',
  '하다',
  '두번째',
  '구매',
  '이다',
  '\n',
  '주문',
  '받다',
  '도정',
  '해주다',
  '기간',
  '은',
  '4-5일',
  '걸리다',
  '그래도',
  '쌀',
  '이',
  '너무',
  '좋다',
  '\n',
  '깨끗하다',
  '밥',
  '도',
  '차다',
  '이쁘다',
  '고슬고슬',
  '되다',
  '다른',
  '쌀',
  '못',
  '먹다',
  '\n',
  '배송',
  '기간',
  '이',
  '있다',
  '잠시',
  '4',
  '키',
  '로',
  '짜다',
  '좋다',
  '것',
  '으로',
  '사서',
  '먹다',
  '기다리다',
  '별로',
  '..',
  '이',
  '*',
  '쌀',
  '강',
  '*',
  '섬쌀',
  '등등',
  '다',
  '먹다',
  '보다',
  '이',
  '게',
  '최고',
  '에요',
  '~',
  '\n',
  '그래서',
  '떨어지다',
  '며칠',
  '전',
  '미리',
  '주문',
  '하다'],
 ['평택', '살다', '때', '맛', '이', '생각나다', '시키다', '최악', '이네', '요', 'ㅠㅠ'],
 ['맛있다'],
 ['차다', '맛있다', '만족하다', '^^~~'],
 ['맛',
  '나',
  '요',
  '~',
  '완전',
  '맛',
  '나',
  '요',
  '~~',
  '\n',
  '꾸준하다',
  '주문',
  '하다',
  '먹다',
  '한번',
  '은',
  '가격',
  '이',
  '너무',
  '비싸다',
  '다른',
  '쌀',
  '먹다',
  '보다',
  '슈퍼',
  '오',
  '닝',
  '이',
  '제',
  '입맛',
  '을',
  '버릇',
  '없다',
  '만들다',
  '..',
  '다른',
  '쌀',
  '은',
  '차다',
  '꼬',
  '수운',
  '맛',
  '이',
  '덜하다',
  '..',
  '\n',
  '한번',
  '맛없다',
  '느끼다',
  '진짜',
  '밥',
  '부지런하다',
  '지다',
  '먹다',
  '왜',
  '이리',
  '닳다',
  '않다',
  '오래',
  '먹다',
  '...',
  'ㅠ',
  '\n',
  '겨우',
  '다',
  '먹다',
  '다시',
  '슈퍼',
  '오',
  '닝',
  '으로',
  '밥',
  '짓다',
  '이제',
  '세상',
  '맛',
  '난',
  '밥',
  '먹다',
  '있다',
  '\n',
  '꼬숩',
  '고',
  '차다',
  '...',
  '거기',
  '다',
  '수확',
  '한지',
  '한참',
  '돼다',
  '도정',
  '을',
  '몇',
  '일',
  '전',
  '바로',
  '하다',
  '보내다',
  '수분',
  '감',
  '이',
  '많다',
  '(',
  '어쩜',
  '품종',
  '때문',
  '일지',
  '도',
  '...)',
  '밥',
  '하다',
  '때',
  '다른',
  '쌀',
  '에',
  '비다',
  '물',
  '을',
  '살짝',
  '적다',
  '잡다',
  '매우',
  '차다',
  '촉촉하다',
  '~~',
  '\n',
  '예전',
  '엔',
  '쌀',
  '을',
  '대충',
  '사서',
  '먹다',
  '맛',
  '난',
  '쌀',
  '에',
  '입맛',
  '이',
  '길들이다',
  '좋다',
  '점',
  '은',
  '반찬',
  '에',
  '덜',
  '집중',
  '하다',
  '되다',
  '..',
  '나쁘다',
  '점',
  '우',
  '다른',
  '쌀',
  '은',
  '먹기',
  '겁나다',
  '..',
  '\n',
  '요',
  '정도',
  '네',
  '요',
  '..',
  '\n',
  '어쨌든',
  '앞',
  '으로',
  '한참',
  '동안',
  '은',
  '요것',
  '만',
  '먹다',
  '해',
  '요',
  '가격',
  '만',
  '계속',
  '요정',
  '도로',
  '유지',
  '해주다',
  '~~~',
  '여러',
  '번',
  '주문',
  '하다',
  '먹다',
  '보다',
  '배송',
  '상태',
  '도',
  '항상',
  '괜찮다',
  '\n',
  '비닐',
  '팩',
  '에',
  '배송',
  '되다',
  '첨으로',
  '박스',
  '에',
  '오다',
  '다행하다',
  '배송',
  '상태',
  '양호',
  '하다'],
 ['항상', '먹다', '거', '라', '리뷰', '라', '필요', '옶어', '요'],
 ['누가',
  '슈퍼',
  '오',
  '닝',
  '만',
  '먹다',
  '하다',
  '그게',
  '무엇',
  '인지',
  '찾다',
  '사다',
  '\n',
  '근데',
  '쌀',
  '씻다',
  '보다',
  '때깔',
  '부터',
  '다르다',
  '\n',
  '밥맛',
  '넘다',
  '좋다',
  '!',
  '\n',
  '오늘',
  '남편',
  '이랑',
  '타마',
  '고',
  '스시',
  '해',
  '먹다',
  '진짜',
  '밖',
  '에서',
  '먹다',
  '초밥',
  '맛',
  '이다',
  '.',
  '\n',
  '도정',
  '도',
  '7월',
  '에한거고',
  '싱싱하다',
  '달다',
  '?',
  '\n',
  '다',
  '먹다',
  '또',
  '사르다',
  '오다',
  '.',
  '기',
  '대',
  '이상',
  '이군',
  '요',
  '.'],
 ['재다', '하다'],
 ['밥맛', '이', '좋다'],
 ['차지', '고', '맛있다', '\n', '맛있다', '완죤'],
 ['함께',
  '일',
  '하다',
  '언니',
  '가',
  '추천',
  '하다',
  '이',
  '쌀',
  '을',
  '사다',
  '~~',
  '안좋다',
  '도정',
  '한',
  '지도',
  '오래되다',
  '같다',
  '밥맛',
  '도',
  '별',
  '로고',
  '요',
  '~',
  '다시다',
  '사먹다',
  '말다'],
 ['썩', '좋다', '모르다'],
 ['아주',
  '굿',
  '\n',
  '아주',
  '맛있다',
  '\n',
  '문의',
  '도',
  '친절하다',
  '해주다',
  '\n',
  '여기',
  '서',
  '만',
  '시키다',
  '먹다',
  '~~'],
 ['가격',
  '에',
  '비',
  '하다',
  '만족하다',
  '~',
  '마트',
  '에서',
  '이보',
  '다',
  '더',
  '비싸다',
  '가격',
  '으로',
  '싸다',
  '쌀',
  '도',
  '안좋다',
  '윤기',
  '있다',
  '밥맛',
  '도',
  '좋다',
  '~^^'],
 ['쌀', '이', '깨끗하다', '보이', '고', '밥', '맛', '이', '좋다', '.', '\n', '쌀', '이', '좋다'],
 ['맛있다', '..', '두번째', '구매', '하다', '밥맛', '이', '좋다', '..'],
 ['이',
  '판매업',
  '자',
  '의',
  '모든',
  '상품',
  '은',
  '시중',
  '가보다',
  '엄청',
  '비싸다',
  '^^~',
  '\n',
  '오다',
  '~,',
  '완전하다',
  '속',
  '았',
  '어',
  '요',
  '.',
  '\n',
  '2020년',
  '햅쌀',
  '송탄',
  '농협',
  '슈퍼',
  '오',
  '닝',
  '고시히카리',
  ',',
  '4',
  'kg',
  ',',
  '1',
  '개',
  '\n',
  '믿어지다',
  '?',
  '48200원',
  ',',
  '4',
  'kg',
  '에',
  '48200원',
  ',',
  '혹',
  '가격',
  '오기',
  '기재',
  '끄다',
  '아니다',
  '문의',
  '하다',
  '갓',
  '도정',
  '한',
  '쌀',
  '이고',
  ',',
  '같다',
  '제품',
  '이라도',
  '가격',
  '차이',
  '가',
  '있다',
  '쿠팡',
  '측',
  '에서',
  '확인',
  '하다',
  '상담',
  '원',
  '문자',
  '옴',
  ',',
  '판매',
  '자의',
  '전화번호',
  '071-7424',
  '-',
  '6536',
  '이',
  '번호',
  '는',
  '신호',
  '가다',
  '끊어지다',
  '끊어지다',
  '..,',
  '010',
  '전화',
  '인',
  '줄',
  '알다',
  '070',
  '으로',
  '사',
  '작',
  '하',
  '는',
  '판매업',
  '자',
  '(',
  '디',
  '엘',
  '컴퍼니',
  '샵',
  '),',
  '판매업',
  '자',
  '상품',
  '을',
  '보다',
  '농산물',
  '뿐',
  '아니다',
  '공산품',
  '도',
  '와우',
  ',',
  '어떤',
  '거',
  '는',
  '따다',
  '블',
  '이네',
  '요',
  ',',
  '8',
  'k',
  '싸다',
  '96400원',
  ',',
  '20',
  'kg',
  '이면',
  '241000원',
  ',',
  '완전',
  '속',
  '았',
  '어',
  '요',
  '.',
  '어째',
  '이렇다',
  '사람',
  '을',
  '정상',
  '적',
  '인',
  '판매업',
  '자',
  '로',
  '등록',
  '시키다',
  '주다',
  ',',
  '주의',
  '하다',
  '가격',
  '이나',
  '중량',
  '을',
  '체크',
  '하다',
  '못',
  '한',
  '제',
  '가',
  '밥',
  '이',
  '이다',
  '?.',
  '오다',
  '기분',
  '차다',
  ',',
  '어째',
  '이렇다',
  '사람',
  '을',
  ',,',
  '코로나',
  '펜데믹',
  '세상',
  '별',
  '사람',
  '이',
  '다',
  '있다',
  '.',
  '\n\n',
  '판매업',
  '자',
  '의',
  '또다른',
  '상품',
  'https://store.coupang.com/vp/vendors/A00307116/products?vendorName=%EB%94%94%EC%97%98%EC%BB%B4%ED%8D%BC%EB%8B%88&productId=128902742&outboundShippingPlaceId=',
  '\n\n',
  '도시락',
  '싸',
  '들다',
  '이',
  '판매업',
  '자',
  '쿠팡',
  '에서',
  '퇴',
  '추다',
  '활동',
  '하다',
  '싶다',
  '..'],
 ['10',
  '키로',
  '가',
  '부담스럽다',
  '가족',
  '에겐',
  '\n\n',
  '적당하다',
  '4',
  '키로',
  '이다',
  '.',
  '\n\n',
  '밀폐',
  '용기',
  '5',
  '리터',
  '에',
  '쏙',
  '들어가다',
  '2',
  '달',
  '먹다',
  '딱',
  '알맞다',
  '.',
  '\n\n',
  '밥맛',
  '도',
  '차다',
  '요즘',
  '쿠팡',
  '에서',
  '산',
  '쌀',
  '들',
  '왠만하다',
  '다',
  '맛있다',
  '\n\n',
  '괜찮다',
  '.'],
 ['맛있다'],
 ['고시', '힠', '카리', '젤', '말다', '써다', '!', '\n', '쫀득쫀득', '윤기', '좌르르', '-'],
 ['한',
  '번시',
  '켜다',
  '먹다',
  '보구',
  '재',
  '구입',
  '하다',
  '\n',
  '쿠팡',
  '서',
  '다르다',
  '시키다',
  '먹다',
  '봣',
  '늘다',
  '\n',
  '여기',
  '쌀',
  '이제일',
  '낫다',
  '해',
  '요',
  '밥맛',
  '좋다'],
 ['휼륭하다'],
 ['좋다',
  '쌀',
  '이다',
  '.',
  '\n',
  '개인',
  '적',
  '으로',
  '안중',
  '고시',
  '히',
  '끄다',
  '리가',
  '최고',
  '에요',
  '.',
  '\n',
  '그',
  '다음',
  '이',
  '평택',
  '이다',
  '.',
  '\n',
  '맛있다',
  '.',
  '\n\n',
  '도정',
  '일이',
  '올해',
  '4월',
  '이에요'],
 ['박스', '가', '너무', '커서', '다', '뜯다', '오다', 'ㅠ'],
 ['윤기', '나', '는', '맛있다', '밥', '매일', '잘', '먹다', '있다', '~~'],
 ['맛있다',
  '\n',
  '엄빠',
  '는',
  '브랜드',
  ',',
  '품종',
  '안',
  '따다',
  '그냥',
  '단일',
  '품종',
  '이',
  '면',
  '오케이',
  '지만',
  '\n',
  '애기',
  '먹다',
  '쌀',
  '은',
  '고시히카리',
  ',',
  '\n',
  '그',
  '중',
  '에서도',
  '좋다',
  '브랜드',
  '인',
  '수퍼',
  '오',
  '닝',
  '으로',
  '사다',
  '.',
  '\n',
  '다',
  '애',
  '만',
  '먹이다',
  '맛',
  '은',
  '못',
  '보다',
  '.'],
 ['쌀',
  '이',
  '신선하다',
  '밥맛',
  '좋다',
  '..',
  '배송',
  '빠르다',
  '재다',
  '하다',
  '\n',
  '쌀',
  '이',
  '신선하다',
  '밥맛',
  '좋다',
  '..',
  '배송',
  '빠르다',
  '재다',
  '하다'],
 ['밥맛',
  '이',
  '좋다',
  '\n',
  '고시히카리',
  '매번',
  '먹다',
  '쌀',
  '이다',
  '이',
  '쌀',
  '먹다',
  '일반',
  '쌀',
  '먹기',
  '힘들다'],
 ['찰기', '가', '좋다', '맛있다', '.'],
 ['선물', '하다', '좋아하다'],
 ['안',
  '좋다',
  '후기',
  '가',
  '있다',
  '걱정',
  '하다',
  '찰밥',
  '같이',
  '맛있다',
  '윤기',
  '가',
  '있다',
  '너무',
  '맛있다'],
 ['쌀', '이', '싱싱하다', '좋다'],
 ['밥맛',
  '좋다',
  '재다',
  '해',
  '요',
  '..',
  '\n',
  '쌀알',
  '이',
  '촉촉하다',
  '알차다',
  '..',
  '밥맛',
  '이',
  '좋다',
  '재다',
  '하다',
  '상품',
  '평',
  '남기다',
  '..',
  '배송',
  '도',
  '빨르다'],
 ['굿', '이', '예', '용'],
 ['밥', '맛있다', '~~'],
 ['햅쌀',
  '이라서',
  '명절',
  '에',
  '먹다',
  '시키다',
  '\n',
  '도정',
  '날짜',
  '가',
  '한',
  '달',
  '하고도',
  '20일',
  '이넘은게',
  '\n',
  '오다',
  '..',
  'ㅜㅜ',
  '비추다',
  '이다'],
 ['3',
  '번째',
  '구매',
  '이다',
  '\n',
  '밥',
  '자다',
  '지다',
  '먹다',
  '!',
  '\n',
  '쌀',
  '이',
  '기본',
  '이',
  '죠',
  '\n',
  '솥',
  '이',
  '휘슬러',
  '여',
  '도',
  '쌀',
  '이',
  '묵다',
  '싸다',
  '꽝',
  '이다',
  '\n',
  '근데',
  '휘슬러',
  '에',
  '슈퍼',
  '오',
  '닝쌀',
  '로',
  '밥',
  '하다',
  '죽음',
  '이에요',
  '\n',
  '집',
  '가다',
  '밥',
  '먹다',
  '생각',
  '뿐'],
 ['지금',
  '계속',
  '슈퍼',
  '오',
  '닝',
  '고시히카리',
  '먹다',
  '좋다',
  '.',
  '\n',
  '혼자',
  '살',
  '면',
  '4',
  'kg',
  ',',
  '둘',
  '이',
  '살',
  '면',
  '10',
  'kg',
  '가다',
  '좋다',
  '듯',
  '싶다',
  '.'],
 ['맛',
  '나다',
  '좋다',
  '\n',
  '가격',
  '도',
  '합리',
  '적',
  '이',
  '고요',
  '.',
  '\n',
  '배송',
  '도',
  '만족',
  '이다'],
 ['역시',
  '쌀',
  '은',
  '고시히카리',
  '.',
  '\n\n',
  '신동진',
  '은',
  '알도',
  '작고',
  '날리다',
  '느낌',
  '이라',
  '식사',
  '후',
  '뭔가',
  '불만족',
  '스러운',
  '데',
  '\n\n',
  '고시히카리',
  '.',
  '거기',
  '다',
  '햅쌀',
  '이니까',
  '\n\n',
  '어리다',
  '적',
  '친하다',
  '아버지',
  '께서',
  '힘들다',
  '농사',
  '지다',
  '그',
  '밥',
  '의',
  '맛',
  '이',
  '나다',
  '.'],
 ['맛있다', '대요'],
 ['훌륭하다', '.'],
 ['지금',
  '3',
  '번째',
  '구매',
  '인가',
  '?',
  '4',
  '번',
  '째',
  '인가',
  '잘',
  '모르다',
  '\n',
  '쌀',
  '맛',
  '괜찮다',
  '세구',
  '이지만',
  '집',
  '에서',
  '밥',
  '을',
  '자다',
  '안',
  '먹다',
  '작다',
  '구매',
  '하다',
  '시작',
  '하다',
  '딱',
  '좋다',
  '\n\n',
  '재다',
  '의사',
  '있다'],
 ['4', 'kg', '단위', '로', '자주', '주문', '하다', '.', '맛', '이', '좋다', '.'],
 ['먹다', '내내', '밥맛', '좋다', '먹다', '.~', '\n', '밥맛', '이', '좋다'],
 ['3',
  '번',
  '구매',
  '이다',
  '\n',
  '배송',
  '은',
  '기',
  '냥',
  '봉',
  '다리',
  '에',
  '오다',
  '불안',
  '하다',
  '안',
  '터지다'],
 ['깨끗하다', '밥', '맛있다'],
 ['항상', '먹다', '싸다', 'ㅎㅎ', '밥', '이', '맛있다'],
 ['역시',
  '고시히카리',
  '\n\n',
  '윤기',
  '좔',
  '좔',
  '\n\n',
  '쫀득쫀득',
  '\n\n',
  '여름철',
  '밥',
  '맛',
  '살아나다'],
 ['밥',
  '하다',
  '지다',
  '\n',
  '고시히카리',
  '인데',
  '\n',
  '차다',
  '달',
  '크다',
  '맛',
  '이',
  '없다',
  '\n',
  '그냥',
  '일',
  '반',
  '쌀',
  '이랑',
  '별',
  '차이',
  '없다',
  '\n',
  '고시히카리',
  '나',
  '추청쌀',
  '은',
  '그냥',
  '밥',
  '만',
  '먹다',
  '달',
  '크다',
  '맛있다',
  '이래서',
  '좋다',
  '쌀',
  '사먹다',
  '하다',
  '...',
  '\n\n',
  '밥',
  '하다',
  '물기',
  '도',
  '많다',
  '별로',
  '이다',
  '\n',
  '물',
  '줄',
  '여서',
  '밥',
  '지',
  '어도',
  '쌀알',
  '이',
  '쫀득',
  '하다',
  '않다',
  '퍼석',
  '해',
  '요',
  '\n',
  '가끔',
  '쿠팡',
  '에서',
  '주문',
  '하다',
  '당진',
  '쌀',
  '이',
  '밥맛',
  '이',
  '더',
  '좋다',
  '것',
  '같다',
  '\n\n',
  '전',
  '에',
  '먹다',
  '홈플러스',
  '고시히카리',
  '를',
  '다시',
  '사다',
  '하다',
  '듯',
  '해',
  '요',
  '\n\n',
  '19,900원',
  '에',
  '구입',
  '하다'],
 ['추천', '하다', '!', '아주', '맛있다', '!'],
 ['전',
  '에',
  '구매',
  '하다',
  '먹다',
  '밥맛',
  '이',
  '괜찮다',
  '또',
  '재다',
  '하다',
  '\n',
  '다',
  '먹다',
  '재다',
  '의사',
  '있다'],
 ['두번째',
  '구매',
  '이다',
  '.',
  '뜯다',
  '바로',
  '전',
  '에',
  '먹다',
  '보다',
  '믿다',
  '재다',
  '하다',
  '.',
  '지금',
  '까지',
  '여러',
  '브랜드',
  '먹다',
  '보다',
  '젤',
  '괜찮다',
  '.',
  '여름',
  '이라',
  '소량',
  '으로',
  '사다',
  '.'],
 ['예전', '에', '먹다', '보고', '괜찮다', '또', '사다'],
 ['맛있다', '.', '쌀', '알도', '좋다', '^^'],
 ['사지', '말다', '~', '냄새', '나서다', '못', '먹다', 'ㅜ'],
 ['세번',
  '째',
  '재다',
  '이다',
  '~',
  '배송',
  '빨',
  '라서',
  '좋다',
  '쌀',
  '상태',
  '도',
  '늘',
  '좋다',
  '!',
  '2018년',
  '싸다',
  '도정',
  '일이',
  '2019년',
  '7월',
  '19일',
  '로',
  '비교',
  '적',
  '최근',
  '이네',
  '요',
  '~',
  '두',
  '식구',
  '고',
  '집',
  '에서',
  '먹다',
  '밥',
  '이라',
  '하다',
  '아침',
  '한',
  '끼',
  '정도',
  '라',
  '4',
  'kg',
  '주문',
  '하다',
  '충분하다',
  '한',
  '달',
  '은',
  '넘다',
  '먹다',
  '것',
  '같다',
  '!',
  '재다',
  '의사',
  '있다',
  '^^'],
 ['밥',
  '은',
  '아직',
  '안',
  '해봤다',
  '좋다',
  '받다',
  '구멍',
  '나',
  '있다',
  '쌀알',
  '좀',
  '버리다',
  '돼다',
  '배송',
  '의',
  '문제',
  '인',
  '건지다',
  '...'],
 ['밥', '맛있다'],
 ['갓',
  '지은',
  '밥',
  '이',
  '윤기',
  '가',
  '흐르다',
  '밥맛',
  '이',
  '좋다',
  '\n',
  '내내',
  '이',
  '천',
  '쌀',
  '만',
  '구매',
  '해먹',
  '다가',
  '바꾸다',
  '보다',
  '품질',
  '좋다',
  '\n',
  '생쌀',
  '이',
  '깨지다',
  '많다',
  '않다',
  '같다',
  '만족스럽다',
  '재다',
  '의사',
  '있다',
  '계속',
  '이렇다',
  '품질',
  '상태',
  '를',
  '유지',
  '해주다',
  '바라다'],
 ['진',
  '밥',
  '좋아하다',
  '분들',
  '추천',
  '\n',
  '꼬들밥',
  '좋아하다',
  '물',
  '을',
  '조금',
  '넣다',
  '밥',
  '이',
  '질',
  '게',
  '되다',
  'ㅠㅠ',
  '\n',
  '맛없다',
  '않다',
  '제',
  '스타일',
  '은',
  '아니다',
  'ㅎㅎㅎ',
  '..'],
 ['깨끗하다', '맛있다', '~~~'],
 ['운',
  '이',
  '나쁘다',
  '건지다',
  '\n',
  '보름',
  '전',
  '정미',
  '되다',
  '오다',
  '\n',
  '하지만',
  '밥맛',
  '이',
  '좋다',
  '\n',
  '미각',
  '이',
  '훌륭하다',
  '삼식이',
  '라',
  '...',
  '\n',
  '맛',
  '나다'],
 ['구매',
  '하다',
  '지금',
  '밥',
  '을',
  '해먹',
  '고',
  '있다',
  '쌀',
  '도',
  '괜찮다',
  '좋다',
  '\n',
  '다시',
  '재다',
  '하다',
  '장바구니',
  '에',
  '담다',
  '좋다'],
 ['늘다', '먹다', '\n', '가격', '이', '적당하다', '좋다'],
 ['밥맛',
  '좋다',
  '쌀',
  '\n',
  '쌀',
  '은',
  '고시히카리',
  '만',
  '먹다',
  '\n',
  '매번',
  '도정',
  '한지',
  '얼마',
  '안되다',
  '오다',
  '맛',
  '이',
  '너무',
  '좋다',
  '\n',
  '돌다',
  '아기',
  '까지',
  '3',
  '가족',
  '인데',
  '평일',
  '엔',
  '거의',
  '밥',
  '을',
  '안',
  '먹다',
  '\n',
  '4',
  '키로',
  '사면',
  '2',
  '달',
  '은',
  '먹다',
  '..',
  '\n',
  '요것',
  '도',
  '정기',
  '배송',
  '이',
  '있다',
  '좋다',
  '네오'],
 ['여러가지',
  '쌀',
  '을',
  '시키다',
  '먹다',
  '엇',
  '지다',
  '정말',
  '최고',
  '에요',
  '~~',
  '말',
  '이',
  '필요없다',
  '~~',
  '최고',
  '쫀득쫀',
  '득',
  '~~~',
  '이렇게',
  '맛',
  '잇다',
  '쌀',
  '은',
  '처음',
  '~~',
  '진짜',
  '태어나다',
  '먹다',
  '본',
  '쌀',
  '중',
  '최고',
  '~~',
  '최고',
  '..!!!'],
 ['배송', '빠르다', '좋다', '~'],
 ['맛있다',
  '운',
  '좋다',
  '도정',
  '일자',
  '가',
  '가깝다',
  '상품',
  '이',
  '배송',
  '되어다',
  '신선하다',
  '^^'],
 ['맛있다'],
 ['쌀',
  '마다',
  '상품',
  '평이',
  '호불호',
  '가',
  '갈리다',
  '찾다',
  '찾다',
  '이',
  '제품',
  '은',
  '안좋다',
  '은평',
  '은',
  '하나',
  '도',
  '없다',
  '같다',
  '구매',
  '해봤다',
  '.',
  '지퍼',
  '팩',
  '은',
  '아니다',
  '여름',
  '이라',
  '소',
  '분해',
  '서',
  '냉장고',
  '넣다',
  '상관없다',
  '.',
  '쌀',
  '알도',
  '좋다',
  '찹쌀',
  '조금',
  '섞다',
  '하다',
  '아이',
  '가',
  '먹다',
  '남기다',
  '차갑다',
  '상태',
  '여',
  '도',
  '맛있다',
  'ㅎㅎ',
  '여름',
  '이라',
  '4',
  '키',
  '로',
  '짜다',
  '사다',
  '잘살다',
  '같다',
  '~!'],
 ['넘다',
  '맛',
  '나다',
  '\n',
  '짱',
  '맛있다',
  '.',
  '\n',
  '고시히카리',
  '첨',
  '먹다',
  '보다',
  '\n',
  '쌀눈',
  '도',
  '살다',
  '밥',
  '도',
  '쫀득하',
  '니',
  '맛',
  '나',
  '요',
  '.'],
 ['Good', '!', '\n', 'Good', '!'],
 ['맛', '나', '요'],
 ['쌀',
  '은',
  '조금씩',
  '여기저기',
  '주문',
  '하다',
  '먹다',
  '송탄',
  '쌀',
  '은',
  '벌써',
  '세네',
  '번',
  '째',
  '구매',
  '예요',
  '!',
  '가격',
  ',',
  '배송',
  ',',
  '품질',
  '다',
  '만족하다',
  '.',
  '재다',
  '의사',
  '있다',
  '~'],
 ['맛있다', '쫀득', '하다'],
 ['쌀',
  '이',
  '터지다',
  '오다',
  '\n',
  '애',
  '당장',
  '먹이다',
  '돼다',
  '그냥',
  '먹이다',
  '신발장',
  '에',
  '쌀',
  '쏟아지다',
  '난리',
  '도',
  '아니다',
  '^^'],
 ['쌀',
  '은',
  '좋다',
  '\n',
  '쌀',
  '이',
  '차다',
  '이뿌다',
  '\n',
  '다만',
  '제',
  '밥솥',
  '이',
  '안좋다'],
 ['재',
  '구매',
  '에요',
  '이',
  '때',
  '까지',
  '먹다',
  '보다',
  '쌀',
  '중',
  '에',
  '젤',
  '맛있다',
  '!',
  '짱짱',
  '맛'],
 ['터지다'],
 ['6월',
  '2일',
  '주문',
  '하다',
  '3일',
  '날',
  '받다',
  '\n',
  '도정',
  '일이',
  '5월',
  '31일',
  '로',
  '굉장하다',
  '최근',
  '이네',
  '요'],
 ['밥', '맛', '이', '좋다', '.'],
 ['밥', '맛', '이', '좋다', '고슬고슬', '!'],
 ['보통', '쌀'],
 ['윤기',
  '있다',
  '찰지다',
  '밥맛',
  '\n',
  '골든',
  '퀸',
  '3',
  '호',
  '먹다',
  '이',
  '제품',
  '주문',
  '해봤다',
  '더',
  '맛있다',
  '.',
  '\n',
  '윤기',
  '가',
  '좌르르',
  '하고',
  '찰지다',
  '.'],
 ['윤기',
  '흐름',
  '.',
  '항상',
  '특등',
  '급',
  '만',
  '먹다',
  '서다',
  '상등',
  '급',
  '괜찮다',
  '하다',
  '이',
  '것',
  '도',
  '괜찮다'],
 ['좋다',
  '~',
  '쿠팡',
  '은',
  '배송',
  '이빨',
  '라',
  '너무',
  '좋다',
  '\n',
  '쌀',
  '도',
  '괜찮다',
  '~~'],
 ['초보',
  '주부',
  '라',
  '밥',
  '하다',
  '때',
  '좀',
  '질',
  '게',
  '되어다',
  '다시',
  '해보다',
  '알다',
  ',',
  '특별하다',
  '맛있다',
  '생각',
  '보단',
  '평범하다',
  '..',
  '워낙',
  '밥맛',
  '이',
  '좋다',
  '소문',
  '만',
  '믿다',
  '주문',
  '하다',
  ',',
  '밥',
  '짓다',
  '실력',
  '이',
  '필요하다',
  '보다',
  '.',
  '물',
  '자다',
  '맞취',
  '서',
  '맛있다',
  '윤기',
  '있다',
  '밥',
  '대접',
  '하고',
  '싶다',
  '~'],
 ['밥맛',
  '좋다',
  '곱다',
  '리',
  '\n',
  '밥맛',
  '진짜',
  '좋다',
  '~~',
  '강',
  '추하다',
  '.',
  '\n',
  '그런데',
  '배송',
  '이',
  '비닐봉투',
  '에',
  '담기다',
  '오다',
  '찢기다',
  '.',
  '\n',
  '물론',
  '안',
  '에',
  '쌀알',
  '들',
  '도',
  '많이',
  '밖',
  '으로',
  '흘러나오다',
  '.',
  '\n',
  '배송',
  '을',
  '박스',
  '포장',
  '이나',
  '안전하다',
  '해주다',
  '좋다',
  '하다',
  '.'],
 ['상품', '이', '터지다', '넣다', '오다', '.'],
 ['우선',
  '4',
  'kg',
  '을',
  '시키다',
  '먹다',
  '보다',
  '\n',
  '저',
  '는',
  '별로',
  '네',
  '요',
  '.',
  '\n',
  '찰',
  '기도',
  '없다',
  '다른',
  '고시히카리',
  '쌀',
  '과는',
  '다르다',
  '\n',
  '맛',
  '이',
  '없다',
  '.',
  '\n',
  '물',
  '을',
  '적다',
  '넣다',
  '그',
  '런가',
  '싶다',
  '많이',
  '넣다',
  '보다',
  '\n',
  '변하다',
  '없이',
  '푸석하다',
  '.',
  '\n',
  '지금',
  '다른',
  '쌀',
  '구매',
  '해보다',
  '해',
  '요',
  'ㅜㅜ'],
 ['두번째',
  '구매',
  '예요',
  '~',
  '쌀',
  '은',
  '조금씩',
  '사서',
  '이',
  '것',
  '저',
  '것',
  '먹다',
  '보다',
  '편',
  '인데',
  ',',
  '슈퍼',
  '오',
  '닝',
  '쌀',
  '마음',
  '에',
  '들다',
  '4',
  'kg',
  '한번',
  '더',
  '구매',
  '하다',
  '~',
  '도정',
  '일도',
  '최근',
  '이고',
  '만족하다',
  '!'],
 ['기대하다', '하다', '망하다', '쓰다', 'ㅠ', '죽밥', '을', '하다', '비싸다', '가격', '하다', '갗아오'],
 ['최고',
  '의',
  '밥맛',
  '선생님',
  '\n',
  '진짜',
  '리얼',
  '대',
  '존맛',
  '이에요',
  '.',
  '\n',
  '전',
  '우리',
  '집',
  '밥솥',
  '이',
  '안좋다',
  '이',
  '때',
  '까지',
  '밥',
  '이',
  '그',
  '저',
  '그런',
  '줄',
  '알다',
  '\n',
  '쌀',
  '이',
  '문제',
  '이다',
  '.',
  '안',
  '불다',
  '어쩜',
  '이렇게',
  '차다',
  '맛',
  '나다',
  '?????',
  '재다',
  '무조건',
  '힙니',
  '다'],
 ['늘', '먹다', '이다'],
 ['ㅈㅏㄹ', '먹다'],
 ['10', 'kg', '시키다', '작다', '시키다', ',,', '역시', '찰지다', '~'],
 ['만족하다',
  '\n',
  '작년',
  '11월',
  '쯤부터',
  '계속',
  '이',
  '쌀',
  '먹다',
  '\n',
  '품종',
  '자체',
  '가',
  '찰지다',
  '같다',
  '\n',
  '다른',
  '쌀',
  '처럼',
  '똑같이',
  '밥물',
  '잡다',
  '\n',
  '밥',
  '이',
  '찰기',
  '가',
  '많다',
  '질',
  '은',
  '느낌',
  '이나',
  '요',
  '\n',
  '개인',
  '적',
  '으로',
  '진밥',
  '을',
  '안',
  '좋아하다',
  '\n',
  '물',
  '살짝',
  '덜',
  '잡고',
  '밥',
  '하다',
  '딱',
  '좋다'],
 ['윤기', '가', '있다', '맛있다'],
 ['고시히카리',
  '쌀',
  '중',
  '아주',
  '칭찬',
  '하다',
  '\n',
  '옛날',
  '엔',
  '안성',
  '꺼',
  '진짜',
  '좋아하다',
  '...',
  '\n',
  '어느',
  '순간',
  '요즘',
  '고시히카리',
  '쌀',
  '이',
  '왜',
  '이렇게',
  '\n',
  '맛',
  '이',
  '없어지다',
  '...',
  'ㅉㅉㅉ',
  '하다',
  '쯤',
  '\n',
  '시키다',
  '도정',
  '날짜',
  '는',
  '3/26',
  '도착',
  '일',
  '은',
  '4/7',
  '이다',
  '\n',
  '밥',
  '하다',
  '일',
  '반',
  '쌀',
  '은',
  '시간',
  '지나다',
  '\n',
  '노래',
  '지다',
  '이',
  '쌀',
  '은',
  '꽤',
  '오래',
  '하얗다',
  '\n',
  '윤기',

In [30]:
#(3) 한 리스트로 저장하기.
morpheme_list = []
for i in range(len(extract_value_list)) :
    morpheme_list.extend(extract_value_list[i])

#(4) 처리 결과 확인하기. 
morpheme_list

['맛있다',
 '\n',
 '맛있다',
 '잘',
 '먹다',
 '아주',
 '맛있다',
 '아니다',
 '괜찮다',
 '편입',
 '니',
 '다',
 '밥맛',
 '이',
 '진짜',
 '좋다',
 '~',
 '\n',
 '밥맛',
 '이',
 '진짜',
 '좋다',
 '~',
 '배송',
 '겁내',
 '빠르다',
 '밥맛',
 '이',
 '정말',
 '좋다',
 '.',
 '\n',
 '아쉽다',
 '것',
 '은',
 '혈당',
 '관리',
 '때문',
 '에',
 '잡곡',
 '밥',
 '을',
 '먹다',
 '하다',
 '...',
 '좋다',
 'ㅎㅎ',
 '\n',
 '자다',
 '먹다',
 '밥',
 '하다',
 '때',
 '냄새',
 '가',
 '나다',
 '밥맛',
 '이',
 '텁텁하',
 '여',
 '썩',
 '좋다',
 '느낌',
 '은',
 '아니다',
 '바구미',
 '한',
 '마리',
 '가',
 '기다',
 '보고',
 '실망',
 '도정',
 '일이',
 '6월',
 '이더라고요',
 'ㅜㅠ',
 '\n',
 '쌀',
 '이',
 '하얗다',
 '않다',
 '냄새',
 '도',
 '좀',
 '나요',
 'ㅠㅠ',
 '아이',
 '이유식',
 '하다',
 '사다',
 '~',
 '\n',
 '쌀',
 '상태',
 '좋다',
 '!',
 '굿굿',
 '\n',
 '항상',
 '맛',
 '잇다',
 '먹다',
 '평택',
 '슈퍼',
 '오',
 '닝',
 '알아주다',
 '쌀',
 '이라',
 '주문',
 '함',
 '밥',
 '냄새',
 '도',
 '너무',
 '좋다',
 '맛있다',
 '쌀',
 '괜찮다',
 '밥맛',
 '도',
 '맛있다',
 '!',
 '걱정',
 '안해',
 '도',
 '되다',
 '좋다',
 '\n',
 '품질',
 '좋다',
 '.',
 '맛있다',
 '\n',
 '믿다',
 '먹다',
 '평택',
 '쌀',
 '맛있다',
 '.',
 '재다',
 '의사',
 '있다',
 '.',
 '물건',
 '이',
 '안',
 '오다',
 '왜',
 '배송',
 '완료',
 '죠',
 '??',
 '전',
 '이',
 '쌀',
 '구',
 '매',
 '해먹',
 '은지',
 '2년',
 '넘엇어',
 '요',
 '밥맛',
 '도',
 '최고',
 '윤기',
 '도',
 '짱',
 '재다',
 '하다',
 '~',
 '난',
 '고시히카리',
 '만',
 '먹다',
 '어느',
 '순간',
 '매장',
 '에',
 '사다',
 '인터넷',
 '에',
 '사다',
 '다르다',
 '생각',
 '이',
 '많다',
 '이듬',
 '.',
 '\n',
 '인터넷',
 '에',
 '산',
 '고시히카리',
 '제대로',
 '되다',
 '못봤슴',
 '.',
 '\n',
 '이',
 '것',
 '도',
 '별로',
 '네',
 '요',
 '.',
 '밥',
 '맛',
 '이',
 '.',
 '최애',
 '쌀',
 '이다',
 '가장',
 '맛있다',
 '쌀',
 '진짜',
 '맛있다',
 '쌀',
 '이다',
 '맛있다',
 '맛',
 '있다',
 '..',
 '담',
 '에',
 '또',
 '구매',
 '하다',
 '햅쌀',
 '이라는',
 '데',
 '재고',
 '느낌',
 '저',
 '는',
 '작년',
 '부터',
 '이',
 '쌀',
 '만',
 '먹다',
 '쿠팡',
 '에',
 '있다',
 '쿠팡',
 '을',
 '통',
 '하다',
 '두번째',
 '구매',
 '이다',
 '\n',
 '주문',
 '받다',
 '도정',
 '해주다',
 '기간',
 '은',
 '4-5일',
 '걸리다',
 '그래도',
 '쌀',
 '이',
 '너무',
 '좋다',
 '\n',
 '깨끗하다',
 '밥',
 '도',
 '차다',
 '이쁘다',
 '고슬고슬',
 '되다',
 '다른',
 '쌀',
 '못',
 '먹다',
 '\n',
 '배송',
 '기간',
 '이',
 '있다',
 '잠시',
 '4',
 '키',
 '로',
 '짜다',
 '좋다',
 '것',
 '으로',
 '사서',
 '먹다',
 '기다리다',
 '별로',
 '..',
 '이',
 '*',
 '쌀',
 '강',
 '*',
 '섬쌀',
 '등등',
 '다',
 '먹다',
 '보다',
 '이',
 '게',
 '최고',
 '에요',
 '~',
 '\n',
 '그래서',
 '떨어지다',
 '며칠',
 '전',
 '미리',
 '주문',
 '하다',
 '평택',
 '살다',
 '때',
 '맛',
 '이',
 '생각나다',
 '시키다',
 '최악',
 '이네',
 '요',
 'ㅠㅠ',
 '맛있다',
 '차다',
 '맛있다',
 '만족하다',
 '^^~~',
 '맛',
 '나',
 '요',
 '~',
 '완전',
 '맛',
 '나',
 '요',
 '~~',
 '\n',
 '꾸준하다',
 '주문',
 '하다',
 '먹다',
 '한번',
 '은',
 '가격',
 '이',
 '너무',
 '비싸다',
 '다른',
 '쌀',
 '먹다',
 '보다',
 '슈퍼',
 '오',
 '닝',
 '이',
 '제',
 '입맛',
 '을',
 '버릇',
 '없다',
 '만들다',
 '..',
 '다른',
 '쌀',
 '은',
 '차다',
 '꼬',
 '수운',
 '맛',
 '이',
 '덜하다',
 '..',
 '\n',
 '한번',
 '맛없다',
 '느끼다',
 '진짜',
 '밥',
 '부지런하다',
 '지다',
 '먹다',
 '왜',
 '이리',
 '닳다',
 '않다',
 '오래',
 '먹다',
 '...',
 'ㅠ',
 '\n',
 '겨우',
 '다',
 '먹다',
 '다시',
 '슈퍼',
 '오',
 '닝',
 '으로',
 '밥',
 '짓다',
 '이제',
 '세상',
 '맛',
 '난',
 '밥',
 '먹다',
 '있다',
 '\n',
 '꼬숩',
 '고',
 '차다',
 '...',
 '거기',
 '다',
 '수확',
 '한지',
 '한참',
 '돼다',
 '도정',
 '을',
 '몇',
 '일',
 '전',
 '바로',
 '하다',
 '보내다',
 '수분',
 '감',
 '이',
 '많다',
 '(',
 '어쩜',
 '품종',
 '때문',
 '일지',
 '도',
 '...)',
 '밥',
 '하다',
 '때',
 '다른',
 '쌀',
 '에',
 '비다',
 '물',
 '을',
 '살짝',
 '적다',
 '잡다',
 '매우',
 '차다',
 '촉촉하다',
 '~~',
 '\n',
 '예전',
 '엔',
 '쌀',
 '을',
 '대충',
 '사서',
 '먹다',
 '맛',
 '난',
 '쌀',
 '에',
 '입맛',
 '이',
 '길들이다',
 '좋다',
 '점',
 '은',
 '반찬',
 '에',
 '덜',
 '집중',
 '하다',
 '되다',
 '..',
 '나쁘다',
 '점',
 '우',
 '다른',
 '쌀',
 '은',
 '먹기',
 '겁나다',
 '..',
 '\n',
 '요',
 '정도',
 '네',
 '요',
 '..',
 '\n',
 '어쨌든',
 '앞',
 '으로',
 '한참',
 '동안',
 '은',
 '요것',
 '만',
 '먹다',
 '해',
 '요',
 '가격',
 '만',
 '계속',
 '요정',
 '도로',
 '유지',
 '해주다',
 '~~~',
 '여러',
 '번',
 '주문',
 '하다',
 '먹다',
 '보다',
 '배송',
 '상태',
 '도',
 '항상',
 '괜찮다',
 '\n',
 '비닐',
 '팩',
 '에',
 '배송',
 '되다',
 '첨으로',
 '박스',
 '에',
 '오다',
 '다행하다',
 '배송',
 '상태',
 '양호',
 '하다',
 '항상',
 '먹다',
 '거',
 '라',
 '리뷰',
 '라',
 '필요',
 '옶어',
 '요',
 '누가',
 '슈퍼',
 '오',
 '닝',
 '만',
 '먹다',
 '하다',
 '그게',
 '무엇',
 '인지',
 '찾다',
 '사다',
 '\n',
 '근데',
 '쌀',
 '씻다',
 '보다',
 '때깔',
 '부터',
 '다르다',
 '\n',
 '밥맛',
 '넘다',
 '좋다',
 '!',
 '\n',
 '오늘',
 '남편',
 '이랑',
 '타마',
 '고',
 '스시',
 '해',
 '먹다',
 '진짜',
 '밖',
 '에서',
 '먹다',
 '초밥',
 '맛',
 '이다',
 '.',
 '\n',
 '도정',
 '도',
 '7월',
 '에한거고',
 '싱싱하다',
 '달다',
 '?',
 '\n',
 '다',
 '먹다',
 '또',
 '사르다',
 '오다',
 '.',
 '기',
 '대',
 '이상',
 '이군',
 '요',
 '.',
 '재다',
 '하다',
 '밥맛',
 '이',
 '좋다',
 '차지',
 '고',
 '맛있다',
 '\n',
 '맛있다',
 '완죤',
 '함께',
 '일',
 '하다',
 '언니',
 '가',
 '추천',
 '하다',
 '이',
 '쌀',
 '을',
 '사다',
 '~~',
 '안좋다',
 '도정',
 '한',
 '지도',
 '오래되다',
 '같다',
 '밥맛',
 '도',
 '별',
 '로고',
 '요',
 '~',
 '다시다',
 '사먹다',
 '말다',
 '썩',
 '좋다',
 '모르다',
 '아주',
 '굿',
 '\n',
 '아주',
 '맛있다',
 '\n',
 '문의',
 '도',
 '친절하다',
 '해주다',
 '\n',
 '여기',
 '서',
 '만',
 '시키다',
 '먹다',
 '~~',
 '가격',
 '에',
 '비',
 '하다',
 '만족하다',
 '~',
 '마트',
 '에서',
 '이보',
 '다',
 '더',
 '비싸다',
 '가격',
 '으로',
 '싸다',
 '쌀',
 '도',
 '안좋다',
 '윤기',
 '있다',
 '밥맛',
 '도',
 '좋다',
 '~^^',
 '쌀',
 '이',
 '깨끗하다',
 '보이',
 '고',
 '밥',
 '맛',
 '이',
 '좋다',
 '.',
 '\n',
 '쌀',
 '이',
 '좋다',
 '맛있다',
 '..',
 '두번째',
 '구매',
 '하다',
 '밥맛',
 '이',
 '좋다',
 '..',
 '이',
 '판매업',
 '자',
 '의',
 '모든',
 '상품',
 '은',
 '시중',
 '가보다',
 '엄청',
 '비싸다',
 '^^~',
 '\n',
 '오다',
 '~,',
 '완전하다',
 '속',
 '았',
 '어',
 '요',
 '.',
 '\n',
 '2020년',
 '햅쌀',
 '송탄',
 '농협',
 '슈퍼',
 '오',
 '닝',
 '고시히카리',
 ',',
 '4',
 'kg',
 ',',
 '1',
 '개',
 '\n',
 '믿어지다',
 '?',
 '48200원',
 ',',
 '4',
 'kg',
 '에',
 '48200원',
 ',',
 '혹',
 '가격',
 '오기',
 '기재',
 '끄다',
 '아니다',
 '문의',
 '하다',
 '갓',
 '도정',
 '한',
 '쌀',
 '이고',
 ',',
 '같다',
 '제품',
 '이라도',
 '가격',
 '차이',
 '가',
 '있다',
 '쿠팡',
 '측',
 '에서',
 '확인',
 '하다',
 '상담',
 '원',
 '문자',
 '옴',
 ',',
 '판매',
 '자의',
 '전화번호',
 '071-7424',
 '-',
 '6536',
 '이',
 '번호',
 '는',
 '신호',
 '가다',
 '끊어지다',
 '끊어지다',
 '..,',
 '010',
 '전화',
 '인',
 '줄',
 '알다',
 '070',
 '으로',
 '사',
 '작',
 '하',
 '는',
 '판매업',
 '자',
 '(',
 '디',
 '엘',
 '컴퍼니',
 '샵',
 '),',
 '판매업',
 '자',
 '상품',
 '을',
 '보다',
 '농산물',
 '뿐',
 '아니다',
 '공산품',
 '도',
 '와우',
 ',',
 '어떤',
 '거',
 '는',
 '따다',
 '블',
 '이네',
 '요',
 ',',
 '8',
 'k',
 '싸다',
 '96400원',
 ',',
 '20',
 'kg',
 '이면',
 '241000원',
 ',',
 '완전',
 '속',
 '았',
 '어',
 '요',
 '.',
 '어째',
 '이렇다',
 '사람',
 '을',
 '정상',
 '적',
 '인',
 '판매업',
 '자',
 '로',
 '등록',
 '시키다',
 '주다',
 ',',
 '주의',
 '하다',
 '가격',
 '이나',
 '중량',
 '을',
 '체크',
 '하다',
 '못',
 '한',
 '제',
 '가',
 '밥',
 '이',
 '이다',
 '?.',
 '오다',
 '기분',
 '차다',
 ',',
 '어째',
 '이렇다',
 '사람',
 '을',
 ',,',
 '코로나',
 '펜데믹',
 '세상',
 '별',
 '사람',
 '이',
 '다',
 '있다',
 '.',
 '\n\n',
 '판매업',
 '자',
 '의',
 '또다른',
 '상품',
 'https://store.coupang.com/vp/vendors/A00307116/products?vendorName=%EB%94%94%EC%97%98%EC%BB%B4%ED%8D%BC%EB%8B%88&productId=128902742&outboundShippingPlaceId=',
 '\n\n',
 '도시락',
 '싸',
 '들다',
 '이',
 '판매업',
 '자',
 '쿠팡',
 '에서',
 '퇴',
 '추다',
 '활동',
 '하다',
 '싶다',
 '..',
 '10',
 '키로',
 '가',
 '부담스럽다',
 '가족',
 '에겐',
 '\n\n',
 '적당하다',
 '4',
 '키로',
 '이다',
 '.',
 '\n\n',
 '밀폐',
 '용기',
 '5',
 '리터',
 '에',
 '쏙',
 '들어가다',
 '2',
 '달',
 '먹다',
 '딱',
 '알맞다',
 '.',
 '\n\n',
 '밥맛',
 '도',
 '차다',
 '요즘',
 '쿠팡',
 '에서',
 '산',
 '쌀',
 '들',
 '왠만하다',
 '다',
 '맛있다',
 '\n\n',
 '괜찮다',
 '.',
 '맛있다',
 '고시',
 '힠',
 '카리',
 '젤',
 '말다',
 '써다',
 '!',
 '\n',
 '쫀득쫀득',
 '윤기',
 '좌르르',
 '-',
 '한',
 '번시',
 '켜다',
 ...]

In [31]:
#(5) 특수문자 공백처리하기. 
morpheme_list_pp  = [] 
for i in range(len(morpheme_list)) :
    text = re.sub('[^가-힣 ]', '', morpheme_list[i])
    morpheme_list_pp.append(text)

#(6) 처리 결과 확인하기. 
morpheme_list_pp

['맛있다',
 '',
 '맛있다',
 '잘',
 '먹다',
 '아주',
 '맛있다',
 '아니다',
 '괜찮다',
 '편입',
 '니',
 '다',
 '밥맛',
 '이',
 '진짜',
 '좋다',
 '',
 '',
 '밥맛',
 '이',
 '진짜',
 '좋다',
 '',
 '배송',
 '겁내',
 '빠르다',
 '밥맛',
 '이',
 '정말',
 '좋다',
 '',
 '',
 '아쉽다',
 '것',
 '은',
 '혈당',
 '관리',
 '때문',
 '에',
 '잡곡',
 '밥',
 '을',
 '먹다',
 '하다',
 '',
 '좋다',
 '',
 '',
 '자다',
 '먹다',
 '밥',
 '하다',
 '때',
 '냄새',
 '가',
 '나다',
 '밥맛',
 '이',
 '텁텁하',
 '여',
 '썩',
 '좋다',
 '느낌',
 '은',
 '아니다',
 '바구미',
 '한',
 '마리',
 '가',
 '기다',
 '보고',
 '실망',
 '도정',
 '일이',
 '월',
 '이더라고요',
 '',
 '',
 '쌀',
 '이',
 '하얗다',
 '않다',
 '냄새',
 '도',
 '좀',
 '나요',
 '',
 '아이',
 '이유식',
 '하다',
 '사다',
 '',
 '',
 '쌀',
 '상태',
 '좋다',
 '',
 '굿굿',
 '',
 '항상',
 '맛',
 '잇다',
 '먹다',
 '평택',
 '슈퍼',
 '오',
 '닝',
 '알아주다',
 '쌀',
 '이라',
 '주문',
 '함',
 '밥',
 '냄새',
 '도',
 '너무',
 '좋다',
 '맛있다',
 '쌀',
 '괜찮다',
 '밥맛',
 '도',
 '맛있다',
 '',
 '걱정',
 '안해',
 '도',
 '되다',
 '좋다',
 '',
 '품질',
 '좋다',
 '',
 '맛있다',
 '',
 '믿다',
 '먹다',
 '평택',
 '쌀',
 '맛있다',
 '',
 '재다',
 '의사',
 '있다',
 '',
 '물건',
 '이',
 '안',
 '오다',
 '왜',
 '배송',
 '완료',
 '죠',
 '',
 '전',
 '이',
 '쌀',
 '구',
 '매',
 '해먹',
 '은지',
 '년',
 '넘엇어',
 '요',
 '밥맛',
 '도',
 '최고',
 '윤기',
 '도',
 '짱',
 '재다',
 '하다',
 '',
 '난',
 '고시히카리',
 '만',
 '먹다',
 '어느',
 '순간',
 '매장',
 '에',
 '사다',
 '인터넷',
 '에',
 '사다',
 '다르다',
 '생각',
 '이',
 '많다',
 '이듬',
 '',
 '',
 '인터넷',
 '에',
 '산',
 '고시히카리',
 '제대로',
 '되다',
 '못봤슴',
 '',
 '',
 '이',
 '것',
 '도',
 '별로',
 '네',
 '요',
 '',
 '밥',
 '맛',
 '이',
 '',
 '최애',
 '쌀',
 '이다',
 '가장',
 '맛있다',
 '쌀',
 '진짜',
 '맛있다',
 '쌀',
 '이다',
 '맛있다',
 '맛',
 '있다',
 '',
 '담',
 '에',
 '또',
 '구매',
 '하다',
 '햅쌀',
 '이라는',
 '데',
 '재고',
 '느낌',
 '저',
 '는',
 '작년',
 '부터',
 '이',
 '쌀',
 '만',
 '먹다',
 '쿠팡',
 '에',
 '있다',
 '쿠팡',
 '을',
 '통',
 '하다',
 '두번째',
 '구매',
 '이다',
 '',
 '주문',
 '받다',
 '도정',
 '해주다',
 '기간',
 '은',
 '일',
 '걸리다',
 '그래도',
 '쌀',
 '이',
 '너무',
 '좋다',
 '',
 '깨끗하다',
 '밥',
 '도',
 '차다',
 '이쁘다',
 '고슬고슬',
 '되다',
 '다른',
 '쌀',
 '못',
 '먹다',
 '',
 '배송',
 '기간',
 '이',
 '있다',
 '잠시',
 '',
 '키',
 '로',
 '짜다',
 '좋다',
 '것',
 '으로',
 '사서',
 '먹다',
 '기다리다',
 '별로',
 '',
 '이',
 '',
 '쌀',
 '강',
 '',
 '섬쌀',
 '등등',
 '다',
 '먹다',
 '보다',
 '이',
 '게',
 '최고',
 '에요',
 '',
 '',
 '그래서',
 '떨어지다',
 '며칠',
 '전',
 '미리',
 '주문',
 '하다',
 '평택',
 '살다',
 '때',
 '맛',
 '이',
 '생각나다',
 '시키다',
 '최악',
 '이네',
 '요',
 '',
 '맛있다',
 '차다',
 '맛있다',
 '만족하다',
 '',
 '맛',
 '나',
 '요',
 '',
 '완전',
 '맛',
 '나',
 '요',
 '',
 '',
 '꾸준하다',
 '주문',
 '하다',
 '먹다',
 '한번',
 '은',
 '가격',
 '이',
 '너무',
 '비싸다',
 '다른',
 '쌀',
 '먹다',
 '보다',
 '슈퍼',
 '오',
 '닝',
 '이',
 '제',
 '입맛',
 '을',
 '버릇',
 '없다',
 '만들다',
 '',
 '다른',
 '쌀',
 '은',
 '차다',
 '꼬',
 '수운',
 '맛',
 '이',
 '덜하다',
 '',
 '',
 '한번',
 '맛없다',
 '느끼다',
 '진짜',
 '밥',
 '부지런하다',
 '지다',
 '먹다',
 '왜',
 '이리',
 '닳다',
 '않다',
 '오래',
 '먹다',
 '',
 '',
 '',
 '겨우',
 '다',
 '먹다',
 '다시',
 '슈퍼',
 '오',
 '닝',
 '으로',
 '밥',
 '짓다',
 '이제',
 '세상',
 '맛',
 '난',
 '밥',
 '먹다',
 '있다',
 '',
 '꼬숩',
 '고',
 '차다',
 '',
 '거기',
 '다',
 '수확',
 '한지',
 '한참',
 '돼다',
 '도정',
 '을',
 '몇',
 '일',
 '전',
 '바로',
 '하다',
 '보내다',
 '수분',
 '감',
 '이',
 '많다',
 '',
 '어쩜',
 '품종',
 '때문',
 '일지',
 '도',
 '',
 '밥',
 '하다',
 '때',
 '다른',
 '쌀',
 '에',
 '비다',
 '물',
 '을',
 '살짝',
 '적다',
 '잡다',
 '매우',
 '차다',
 '촉촉하다',
 '',
 '',
 '예전',
 '엔',
 '쌀',
 '을',
 '대충',
 '사서',
 '먹다',
 '맛',
 '난',
 '쌀',
 '에',
 '입맛',
 '이',
 '길들이다',
 '좋다',
 '점',
 '은',
 '반찬',
 '에',
 '덜',
 '집중',
 '하다',
 '되다',
 '',
 '나쁘다',
 '점',
 '우',
 '다른',
 '쌀',
 '은',
 '먹기',
 '겁나다',
 '',
 '',
 '요',
 '정도',
 '네',
 '요',
 '',
 '',
 '어쨌든',
 '앞',
 '으로',
 '한참',
 '동안',
 '은',
 '요것',
 '만',
 '먹다',
 '해',
 '요',
 '가격',
 '만',
 '계속',
 '요정',
 '도로',
 '유지',
 '해주다',
 '',
 '여러',
 '번',
 '주문',
 '하다',
 '먹다',
 '보다',
 '배송',
 '상태',
 '도',
 '항상',
 '괜찮다',
 '',
 '비닐',
 '팩',
 '에',
 '배송',
 '되다',
 '첨으로',
 '박스',
 '에',
 '오다',
 '다행하다',
 '배송',
 '상태',
 '양호',
 '하다',
 '항상',
 '먹다',
 '거',
 '라',
 '리뷰',
 '라',
 '필요',
 '옶어',
 '요',
 '누가',
 '슈퍼',
 '오',
 '닝',
 '만',
 '먹다',
 '하다',
 '그게',
 '무엇',
 '인지',
 '찾다',
 '사다',
 '',
 '근데',
 '쌀',
 '씻다',
 '보다',
 '때깔',
 '부터',
 '다르다',
 '',
 '밥맛',
 '넘다',
 '좋다',
 '',
 '',
 '오늘',
 '남편',
 '이랑',
 '타마',
 '고',
 '스시',
 '해',
 '먹다',
 '진짜',
 '밖',
 '에서',
 '먹다',
 '초밥',
 '맛',
 '이다',
 '',
 '',
 '도정',
 '도',
 '월',
 '에한거고',
 '싱싱하다',
 '달다',
 '',
 '',
 '다',
 '먹다',
 '또',
 '사르다',
 '오다',
 '',
 '기',
 '대',
 '이상',
 '이군',
 '요',
 '',
 '재다',
 '하다',
 '밥맛',
 '이',
 '좋다',
 '차지',
 '고',
 '맛있다',
 '',
 '맛있다',
 '완죤',
 '함께',
 '일',
 '하다',
 '언니',
 '가',
 '추천',
 '하다',
 '이',
 '쌀',
 '을',
 '사다',
 '',
 '안좋다',
 '도정',
 '한',
 '지도',
 '오래되다',
 '같다',
 '밥맛',
 '도',
 '별',
 '로고',
 '요',
 '',
 '다시다',
 '사먹다',
 '말다',
 '썩',
 '좋다',
 '모르다',
 '아주',
 '굿',
 '',
 '아주',
 '맛있다',
 '',
 '문의',
 '도',
 '친절하다',
 '해주다',
 '',
 '여기',
 '서',
 '만',
 '시키다',
 '먹다',
 '',
 '가격',
 '에',
 '비',
 '하다',
 '만족하다',
 '',
 '마트',
 '에서',
 '이보',
 '다',
 '더',
 '비싸다',
 '가격',
 '으로',
 '싸다',
 '쌀',
 '도',
 '안좋다',
 '윤기',
 '있다',
 '밥맛',
 '도',
 '좋다',
 '',
 '쌀',
 '이',
 '깨끗하다',
 '보이',
 '고',
 '밥',
 '맛',
 '이',
 '좋다',
 '',
 '',
 '쌀',
 '이',
 '좋다',
 '맛있다',
 '',
 '두번째',
 '구매',
 '하다',
 '밥맛',
 '이',
 '좋다',
 '',
 '이',
 '판매업',
 '자',
 '의',
 '모든',
 '상품',
 '은',
 '시중',
 '가보다',
 '엄청',
 '비싸다',
 '',
 '',
 '오다',
 '',
 '완전하다',
 '속',
 '았',
 '어',
 '요',
 '',
 '',
 '년',
 '햅쌀',
 '송탄',
 '농협',
 '슈퍼',
 '오',
 '닝',
 '고시히카리',
 '',
 '',
 '',
 '',
 '',
 '개',
 '',
 '믿어지다',
 '',
 '원',
 '',
 '',
 '',
 '에',
 '원',
 '',
 '혹',
 '가격',
 '오기',
 '기재',
 '끄다',
 '아니다',
 '문의',
 '하다',
 '갓',
 '도정',
 '한',
 '쌀',
 '이고',
 '',
 '같다',
 '제품',
 '이라도',
 '가격',
 '차이',
 '가',
 '있다',
 '쿠팡',
 '측',
 '에서',
 '확인',
 '하다',
 '상담',
 '원',
 '문자',
 '옴',
 '',
 '판매',
 '자의',
 '전화번호',
 '',
 '',
 '',
 '이',
 '번호',
 '는',
 '신호',
 '가다',
 '끊어지다',
 '끊어지다',
 '',
 '',
 '전화',
 '인',
 '줄',
 '알다',
 '',
 '으로',
 '사',
 '작',
 '하',
 '는',
 '판매업',
 '자',
 '',
 '디',
 '엘',
 '컴퍼니',
 '샵',
 '',
 '판매업',
 '자',
 '상품',
 '을',
 '보다',
 '농산물',
 '뿐',
 '아니다',
 '공산품',
 '도',
 '와우',
 '',
 '어떤',
 '거',
 '는',
 '따다',
 '블',
 '이네',
 '요',
 '',
 '',
 '',
 '싸다',
 '원',
 '',
 '',
 '',
 '이면',
 '원',
 '',
 '완전',
 '속',
 '았',
 '어',
 '요',
 '',
 '어째',
 '이렇다',
 '사람',
 '을',
 '정상',
 '적',
 '인',
 '판매업',
 '자',
 '로',
 '등록',
 '시키다',
 '주다',
 '',
 '주의',
 '하다',
 '가격',
 '이나',
 '중량',
 '을',
 '체크',
 '하다',
 '못',
 '한',
 '제',
 '가',
 '밥',
 '이',
 '이다',
 '',
 '오다',
 '기분',
 '차다',
 '',
 '어째',
 '이렇다',
 '사람',
 '을',
 '',
 '코로나',
 '펜데믹',
 '세상',
 '별',
 '사람',
 '이',
 '다',
 '있다',
 '',
 '',
 '판매업',
 '자',
 '의',
 '또다른',
 '상품',
 '',
 '',
 '도시락',
 '싸',
 '들다',
 '이',
 '판매업',
 '자',
 '쿠팡',
 '에서',
 '퇴',
 '추다',
 '활동',
 '하다',
 '싶다',
 '',
 '',
 '키로',
 '가',
 '부담스럽다',
 '가족',
 '에겐',
 '',
 '적당하다',
 '',
 '키로',
 '이다',
 '',
 '',
 '밀폐',
 '용기',
 '',
 '리터',
 '에',
 '쏙',
 '들어가다',
 '',
 '달',
 '먹다',
 '딱',
 '알맞다',
 '',
 '',
 '밥맛',
 '도',
 '차다',
 '요즘',
 '쿠팡',
 '에서',
 '산',
 '쌀',
 '들',
 '왠만하다',
 '다',
 '맛있다',
 '',
 '괜찮다',
 '',
 '맛있다',
 '고시',
 '힠',
 '카리',
 '젤',
 '말다',
 '써다',
 '',
 '',
 '쫀득쫀득',
 '윤기',
 '좌르르',
 '',
 '한',
 '번시',
 '켜다',
 ...]

In [32]:
#(7) 데이터 프레임 변환하기. 
morpheme_df = pd.DataFrame({'value': morpheme_list_pp})

#(8) 불용어 처리하기. 
for i in range(len(STOPWORD)) :
    morpheme_df[morpheme_df['value']==STOPWORD[i]] = np.nan

#(9) 데이터프레임 보기 좋게 구성하기.
word_frequency = morpheme_df.value_counts().to_frame()
word_frequency = word_frequency.reset_index()
word_frequency.columns = ['value','count']
word_frequency

#(10) 단어 글자 수가 1 이하인 값 처리하기
for i in range(len(word_frequency))            :
    try                                        :
        if len(word_frequency['value'][i]) < 2 :
            word_frequency.at[i ,'count'] = 0
    except Exception                           :
        print(f'ERROR ! index_num = {i}')

#(11) count 값이 5 이상인 행만 출력하기. 
word_frequency = word_frequency[word_frequency['count'] >= 5]

#(12) 엑셀로 저장하기.
word_frequency.to_excel(f'../data/NLP/{CULTIVAR}_word_frequency.xlsx', index=False)

#(13) 결과 확인하기. 
word_frequency

      value  count
10       윤기    919
27       곱다    341
37      찰지다    255
38       지다    251
75       찰기    111
83     고소하다     97
88     구수하다     88
96       돼다     79
99     촉촉하다     76
112      달다     61
114     하얗다     61
126      짜다     55
130      누렇     54
136    투명하다     49
138      쫀득     48
149    쫀득쫀득     41
153      단맛     40
176      굵다     30
187     쫀득하     25
188    고슬고슬     25
194     탁하다     24
196     기름기     23
207    탱글탱글     19
212    탱탱하다     18
215      진밥     18
217  탱글탱글하다     17
223     씹히다     17
226   푸석거리다     17
227     볶음밥     16
228      찰밥     16
230      투명     16
232    통통하다     16
233     진하다     16
243     누룽지     14
247    매끈하다     14
250      라면     13
254      쫄깃     13
255      햇반     13
256      초밥     13
257  고슬고슬하다     13
263  푸석푸석하다     12
270      달달     11
283    꼬들꼬들     10
284    딱딱하다     10
302    푸석하다      9
312   쫀득쫀득해      8
336    고실고실      7
343    푸석푸석      6
344    쫀득거리      6
345      매끈      6
349    시큼하다      6
353     누런색      6
370     쫀득해      6
388    달콤하다      5
392   부스러지다      5