In [1]:
#2021.10.20. TUE
#Team_SmokeFree

## Data Preprocessing For MCLP 
#00. 패키지 호출하기. 
import warnings
import pandas as pd 
import numpy as np 
import geopandas as gpd
from fiona.crs import from_epsg

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

#00-2. 사전 변수 설정하기.
NAME = '음식점_외식'
GU_LIST = ['금천구', '관악구', '구로구', '마포구', '은평구', '서대문구', '용산구', '중구', '동작구', '영등포구', '관악구', '서초구']

In [2]:
#01. RANDOM_POINT 데이터셋 전처리하기. 
#(1) RANDOM_POINT 데이터셋 불러오기. 
RANDOM_POINT = gpd.read_file('../data/shp/RANDOM_POINT_DIFF_INTE/RANDOM_POINT_DIFF_INTE.shp', encoding='utf-8')

#(2) 필요 컬럼만 추출하기. 
RANDOM_POINT = RANDOM_POINT[['rand_point', 'SGG_NM', 'geometry']] 

#(3) 처리 결과 확인하기. 
RANDOM_POINT

       rand_point SGG_NM                       geometry
0               0    금천구  POINT (192337.743 438954.077)
1               1    금천구  POINT (192425.234 438954.212)
2               2    금천구  POINT (192413.198 438951.433)
3               3    금천구  POINT (192327.406 438953.454)
4               4    금천구  POINT (192358.272 438959.210)
...           ...    ...                            ...
40286       41191    동작구  POINT (195897.989 444499.242)
40287       41192    동작구  POINT (195904.434 444535.270)
40288       41193    동작구  POINT (195908.806 444516.805)
40289       41194    동작구  POINT (195906.649 444565.088)
40290       41195    동작구  POINT (195895.561 444485.845)

[40291 rows x 3 columns]

In [3]:
#(4) 버퍼 지정하기. 
RANDOM_POINT_BUFFER = RANDOM_POINT.buffer(100)

In [4]:
#02. COUNT DATASET 불러오기. 
#(1) 데이터셋 불러오기. 
COUNT_DATASET = pd.read_excel(f'A:/Python_Project/Team_SmokeFree/Data/01_Feature_Data/서울특별시_{NAME}_pp.xlsx')

#(2) 필요 자치구만 선택하기. 
COUNT_DATASET['INJ_GU'] = 0
for i in range(len(COUNT_DATASET)) : 
  if COUNT_DATASET['자치구'][i] in GU_LIST :
    COUNT_DATASET['INJ_GU'][i] = 1

#(3) INJ_GU == 1인 값만 추출하기. 
COUNT_DATASET = COUNT_DATASET[COUNT_DATASET['INJ_GU'] == 1]

#(4) INJ_GU 컬럼 삭제하기.
COUNT_DATASET = COUNT_DATASET.drop(['INJ_GU'], axis=1)

#(5) 인덱스 초기화하기. 
COUNT_DATASET = COUNT_DATASET.reset_index()

#(6) geometry 추가하기. 
COUNT_DATASET_point = gpd.points_from_xy(COUNT_DATASET['경도'], COUNT_DATASET['위도'])

#(7) 데이터셋 재구축하기. 
COUNT_DATASET = gpd.GeoDataFrame(COUNT_DATASET[COUNT_DATASET.columns], geometry=COUNT_DATASET_point, crs=from_epsg(4326))

#(8) 좌표계 변환하기. 
COUNT_DATASET = COUNT_DATASET.to_crs(epsg=5181)

#(9) 처리 결과 확인하기. 
COUNT_DATASET

,index,자치구,행정동_코드,행정동,사업장명,업종,소재지_지번_주소,소재지_도로명_주소,위도,경도,geometry
0,3,구로구,1153055000,구로제4동,여름엔빙수겨울엔떡국,외식,서울특별시 구로구 구로동 734-18번지 1층,서울특별시 구로구 구로동로22길 21 1층 (구로동),37.489547,126.885584,POINT (189881.302 443350.104)
1,5,관악구,1162066500,서림동,보스턴피자,외식,서울특별시 관악구 신림동 116-2번지 대학당,서울특별시 관악구 신림로22길 5 대학당 지하1층 (신림동),37.471628,126.935285,POINT (194275.383 441357.185)
2,6,영등포구,1156062000,양평제2동,식껍선유도역점,외식,서울특별시 영등포구 양평동4가 22-1번지 구산드림타워,서울특별시 영등포구 선유로47길 15 구산드림타워 1층 108-1호 (양평동4가),37.535390,126.895006,POINT (190720.241 448437.091)
3,13,중구,1114060500,을지로동,찜이로닭,외식,서울특별시 중구 을지로4가 323 지하1층 106호 107호,서울특별시 중구 을지로 170 지하1층 106107호 (을지로4가),37.566125,126.997308,POINT (199762.169 451843.197)
4,15,마포구,1144066000,서교동,차르,외식,서울특별시 마포구 서교동 354-5번지 RYSE,서울특별시 마포구 양화로 130 RYSE 4층 (서교동),37.554322,126.921190,POINT (193036.242 450536.108)
...,...,...,...,...,...,...,...,...,...,...,...
37732,86642,용산구,1117053000,남영동,온오프커피(ONOFF COFFEE),외식,서울특별시 용산구 남영동 3-1,서울특별시 용산구 두텁바위로 12 1층 (남영동),37.545120,126.973354,POINT (197645.234 449512.178)
37733,86643,용산구,1117053000,남영동,진1926 서울역 트윈시티점,외식,서울특별시 용산구 동자동 56 트윈시티 남산,서울특별시 용산구 한강대로 366 트윈시티 남산 B동 1층 101호 (동자동),37.551066,126.972887,POINT (197604.155 450172.180)
37734,86644,용산구,1117053000,남영동,인생아구찜,외식,서울특별시 용산구 갈월동 57-3 (지상1층),서울특별시 용산구 두텁바위로1길 23 (갈월동(지상1층)),37.545732,126.973659,POINT (197672.207 449580.184)
37735,86645,용산구,1117053000,남영동,참치정육점,외식,서울특별시 용산구 갈월동 92-3,서울특별시 용산구 한강대로77길 8 1층 (갈월동),37.542182,126.972121,POINT (197536.174 449186.183)
37736,86646,용산구,1117053000,남영동,쏠레피자,외식,서울특별시 용산구 동자동 35-14,서울특별시 용산구 후암로57길 55 2층 (동자동),37.551066,126.974098,POINT (197711.165 450172.183)

In [5]:
#(6) 새 컬럼 만들기. 
RANDOM_POINT[f'{NAME}_COUNT'] = 0

#(7) 포함 여부 파악하여 계산 후, 컬럼에 값 지정하기. 
for i in range(len(RANDOM_POINT))                                                  :
    value_count_list = []
    for k in range(len(COUNT_DATASET))                                             :
        if (RANDOM_POINT_BUFFER[i].contains(COUNT_DATASET['geometry'][k])) == True :
            value_count = 'YES'
            value_count_list.append(value_count)
    RANDOM_POINT[f'{NAME}_COUNT'][i] = len(value_count_list)
    print(f'DONE ! INDEX_NUM = {i}')

DONE ! INDEX_NUM = 0
DONE ! INDEX_NUM = 1
DONE ! INDEX_NUM = 2
DONE ! INDEX_NUM = 3
DONE ! INDEX_NUM = 4
DONE ! INDEX_NUM = 5
DONE ! INDEX_NUM = 6
DONE ! INDEX_NUM = 7
DONE ! INDEX_NUM = 8
DONE ! INDEX_NUM = 9
DONE ! INDEX_NUM = 10
DONE ! INDEX_NUM = 11
DONE ! INDEX_NUM = 12
DONE ! INDEX_NUM = 13
DONE ! INDEX_NUM = 14
DONE ! INDEX_NUM = 15
DONE ! INDEX_NUM = 16
DONE ! INDEX_NUM = 17
DONE ! INDEX_NUM = 18
DONE ! INDEX_NUM = 19
DONE ! INDEX_NUM = 20
DONE ! INDEX_NUM = 21
DONE ! INDEX_NUM = 22
DONE ! INDEX_NUM = 23
DONE ! INDEX_NUM = 24
DONE ! INDEX_NUM = 25
DONE ! INDEX_NUM = 26
DONE ! INDEX_NUM = 27
DONE ! INDEX_NUM = 28
DONE ! INDEX_NUM = 29
DONE ! INDEX_NUM = 30
DONE ! INDEX_NUM = 31
DONE ! INDEX_NUM = 32
DONE ! INDEX_NUM = 33
DONE ! INDEX_NUM = 34
DONE ! INDEX_NUM = 35
DONE ! INDEX_NUM = 36
DONE ! INDEX_NUM = 37
DONE ! INDEX_NUM = 38
DONE ! INDEX_NUM = 39
DONE ! INDEX_NUM = 40
DONE ! INDEX_NUM = 41
DONE ! INDEX_NUM = 42
DONE ! INDEX_NUM = 43
DONE ! INDEX_NUM = 44
DONE ! INDEX_NUM = 45
DONE ! INDEX_NUM = 46
DONE ! INDEX_NUM = 47
DONE ! INDEX_NUM = 48
DONE ! INDEX_NUM = 49
DONE ! INDEX_NUM = 50
DONE ! INDEX_NUM = 51
DONE ! INDEX_NUM = 52
DONE ! INDEX_NUM = 53
DONE ! INDEX_NUM = 54
DONE ! INDEX_NUM = 55
DONE ! INDEX_NUM = 56
DONE ! INDEX_NUM = 57
DONE ! INDEX_NUM = 58
DONE ! INDEX_NUM = 59
DONE ! INDEX_NUM = 60
DONE ! INDEX_NUM = 61
DONE ! INDEX_NUM = 62
DONE ! INDEX_NUM = 63
DONE ! INDEX_NUM = 64
DONE ! INDEX_NUM = 65
DONE ! INDEX_NUM = 66
DONE ! INDEX_NUM = 67
DONE ! INDEX_NUM = 68
DONE ! INDEX_NUM = 69
DONE ! INDEX_NUM = 70
DONE ! INDEX_NUM = 71
DONE ! INDEX_NUM = 72
DONE ! INDEX_NUM = 73
DONE ! INDEX_NUM = 74
DONE ! INDEX_NUM = 75
DONE ! INDEX_NUM = 76
DONE ! INDEX_NUM = 77
DONE ! INDEX_NUM = 78
DONE ! INDEX_NUM = 79
DONE ! INDEX_NUM = 80
DONE ! INDEX_NUM = 81
DONE ! INDEX_NUM = 82
DONE ! INDEX_NUM = 83
DONE ! INDEX_NUM = 84
DONE ! INDEX_NUM = 85
DONE ! INDEX_NUM = 86
DONE ! INDEX_NUM = 87
DONE ! INDEX_NUM = 88
DONE ! INDEX_NUM = 89
DONE ! INDEX_NUM = 90
DONE ! INDEX_NUM = 91
DONE ! INDEX_NUM = 92
DONE ! INDEX_NUM = 93
DONE ! INDEX_NUM = 94
DONE ! INDEX_NUM = 95
DONE ! INDEX_NUM = 96
DONE ! INDEX_NUM = 97
DONE ! INDEX_NUM = 98
DONE ! INDEX_NUM = 99
DONE ! INDEX_NUM = 100
DONE ! INDEX_NUM = 101
DONE ! INDEX_NUM = 102
DONE ! INDEX_NUM = 103
DONE ! INDEX_NUM = 104
DONE ! INDEX_NUM = 105
DONE ! INDEX_NUM = 106
DONE ! INDEX_NUM = 107
DONE ! INDEX_NUM = 108
DONE ! INDEX_NUM = 109
DONE ! INDEX_NUM = 110
DONE ! INDEX_NUM = 111
DONE ! INDEX_NUM = 112
DONE ! INDEX_NUM = 113
DONE ! INDEX_NUM = 114
DONE ! INDEX_NUM = 115
DONE ! INDEX_NUM = 116
DONE ! INDEX_NUM = 117
DONE ! INDEX_NUM = 118
DONE ! INDEX_NUM = 119
DONE ! INDEX_NUM = 120
DONE ! INDEX_NUM = 121
DONE ! INDEX_NUM = 122
DONE ! INDEX_NUM = 123
DONE ! INDEX_NUM = 124
DONE ! INDEX_NUM = 125
DONE ! INDEX_NUM = 126
DONE ! INDEX_NUM = 127
DONE ! INDEX_NUM = 128
DONE ! INDEX_NUM = 129
DONE ! INDEX_NUM = 130
DONE ! INDEX_NUM = 131
DONE ! INDEX_NUM = 132
DONE ! INDEX_NUM = 133
DONE ! INDEX_NUM = 134
DONE ! INDEX_NUM = 135
DONE ! INDEX_NUM = 136
DONE ! INDEX_NUM = 137
DONE ! INDEX_NUM = 138
DONE ! INDEX_NUM = 139
DONE ! INDEX_NUM = 140
DONE ! INDEX_NUM = 141
DONE ! INDEX_NUM = 142
DONE ! INDEX_NUM = 143
DONE ! INDEX_NUM = 144
DONE ! INDEX_NUM = 145
DONE ! INDEX_NUM = 146
DONE ! INDEX_NUM = 147
DONE ! INDEX_NUM = 148
DONE ! INDEX_NUM = 149
DONE ! INDEX_NUM = 150
DONE ! INDEX_NUM = 151
DONE ! INDEX_NUM = 152
DONE ! INDEX_NUM = 153
DONE ! INDEX_NUM = 154
DONE ! INDEX_NUM = 155
DONE ! INDEX_NUM = 156
DONE ! INDEX_NUM = 157
DONE ! INDEX_NUM = 158
DONE ! INDEX_NUM = 159
DONE ! INDEX_NUM = 160
DONE ! INDEX_NUM = 161
DONE ! INDEX_NUM = 162
DONE ! INDEX_NUM = 163
DONE ! INDEX_NUM = 164
DONE ! INDEX_NUM = 165
DONE ! INDEX_NUM = 166
DONE ! INDEX_NUM = 167
DONE ! INDEX_NUM = 168
DONE ! INDEX_NUM = 169
DONE ! INDEX_NUM = 170
DONE ! INDEX_NUM = 171
DONE ! INDEX_NUM = 172
DONE ! INDEX_NUM = 173
DONE ! INDEX_NUM = 174
DONE ! INDEX_NUM = 175
DONE ! INDEX_NUM = 176
DONE ! INDEX_NUM = 177
DONE ! INDEX_NUM = 178
DONE ! INDEX_NUM = 179
DONE ! INDEX_NUM = 180
DONE ! INDEX_NUM = 181
DONE ! INDEX_NUM = 182
DONE ! INDEX_NUM = 183
DONE ! INDEX_NUM = 184
DONE ! INDEX_NUM = 185
DONE ! INDEX_NUM = 186
DONE ! INDEX_NUM = 187
DONE ! INDEX_NUM = 188
DONE ! INDEX_NUM = 189
DONE ! INDEX_NUM = 190
DONE ! INDEX_NUM = 191
DONE ! INDEX_NUM = 192
DONE ! INDEX_NUM = 193
DONE ! INDEX_NUM = 194
DONE ! INDEX_NUM = 195
DONE ! INDEX_NUM = 196
DONE ! INDEX_NUM = 197
DONE ! INDEX_NUM = 198
DONE ! INDEX_NUM = 199
DONE ! INDEX_NUM = 200
DONE ! INDEX_NUM = 201
DONE ! INDEX_NUM = 202
DONE ! INDEX_NUM = 203
DONE ! INDEX_NUM = 204
DONE ! INDEX_NUM = 205
DONE ! INDEX_NUM = 206
DONE ! INDEX_NUM = 207
DONE ! INDEX_NUM = 208
DONE ! INDEX_NUM = 209
DONE ! INDEX_NUM = 210
DONE ! INDEX_NUM = 211
DONE ! INDEX_NUM = 212
DONE ! INDEX_NUM = 213
DONE ! INDEX_NUM = 214
DONE ! INDEX_NUM = 215
DONE ! INDEX_NUM = 216
DONE ! INDEX_NUM = 217
DONE ! INDEX_NUM = 218
DONE ! INDEX_NUM = 219
DONE ! INDEX_NUM = 220
DONE ! INDEX_NUM = 221
DONE ! INDEX_NUM = 222
DONE ! INDEX_NUM = 223
DONE ! INDEX_NUM = 224
DONE ! INDEX_NUM = 225
DONE ! INDEX_NUM = 226
DONE ! INDEX_NUM = 227

In [ ]:
 #(8) 처리 결과 확인하기. 
RANDOM_POINT

In [ ]:
#(9) 처리 결과 저장하기.
RANDOM_POINT.to_excel(f'temp_file.xlsx', index=False)