In [1]:
#2021.10.15. FRI
#Team_SmokeFree

## Dataset Integrity Check
#00. 패키지 호출하기.
import pandas as pd 
import warnings

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

#00-1. 사전 변수 설정하기.
NAME = '금연구역'
IS_GOOD_DATASET = 0

#02. 법정동을 행정동으로 변환하기. 
#(1) 데이터셋 불러오기. 
Dataset = pd.read_excel(f'../data/01_Feature_Data/서울특별시_{NAME}_pp.xlsx')
dong_data = pd.read_excel('../data/서울특별시_행정동_법정동_코드.xlsx')

#(2) 처리 결과 확인하기. 
Dataset

,INDEX,자치구,행정동_코드,행정동,사업장명,소재지_지번_주소,소재지_도로명_주소,위도,경도
0,0,영등포구,1156063000,신길제1동,삼두어린이집,서울특별시 영등포구 신길동 2-5번지,서울특별시 영등포구 여의대방로59길 16-17,37.514563,126.924292
1,1,영등포구,1156069000,신길제7동,사랑어린이집,서울특별시 영등포구 신길동 897-1번지 109동 102호 삼환아파트,서울특별시 영등포구 여의대방로43라길 9 109동 102호(신길동삼환아파트),37.507964,126.919514
2,2,영등포구,1156065000,신길제3동,사랑나무어린이집,서울특별시 영등포구 신길동 364번지 건영아파트 라동 101호,서울특별시 영등포구 도림로 313 건영아파트 라동 101호,37.505984,126.900975
3,3,영등포구,1156060500,문래동,비율라어린이집,서울특별시 영등포구 문래동4가 11-7번지,서울특별시 영등포구 도림로141가길 33-4,37.516140,126.889298
4,4,영등포구,1156071000,대림제2동,튼튼어린이집,서울특별시 영등포구 대림동 1083-5번지,서울특별시 영등포구 디지털로37길 5 (대림동),37.489150,126.898741
...,...,...,...,...,...,...,...,...,...
9978,9980,양천구,1147062000,신정1동,단지(어린이공원),서울특별시 양천구 신정1동 1047-1,서울특별시 양천구 신정동 중앙로36길 1,37.520944,126.858240
9979,9981,양천구,1147063000,신정2동,신세계(어린이공원),서울특별시 양천구 신정2동 119-3,NaN,37.521721,126.858348
9980,9982,양천구,1147063000,신정2동,신정(어린이공원),서울특별시 양천구 신정2동 128-198,NaN,37.520466,126.857237
9981,9983,양천구,1147064000,신정3동,꽃사슴(어린이공원),서울특별시 양천구 신정3동 1195,서울특별시 양천구 중앙로29길 108-15,37.521627,126.848532
9982,9984,양천구,1147064000,신정3동,신기(어린이공원),서울특별시 양천구 신정3동 1260,NaN,37.514028,126.854294

In [2]:
dong_data.head()

     시도명 시군구명       행정동코드    행정동       법정동코드  법정동
0  서울특별시  종로구  1111000000    NaN  1111000000  종로구
1  서울특별시  종로구  1111051500  청운효자동  1111010100  청운동
2  서울특별시  종로구  1111051500  청운효자동  1111010200  신교동
3  서울특별시  종로구  1111051500  청운효자동  1111010300  궁정동
4  서울특별시  종로구  1111051500  청운효자동  1111010400  효자동

In [3]:
#03. 행정동 무결성 검사하기. 
#(1) 작업 시행하기. 
IGH_list = []
for i in range(len(Dataset))                                    :
    for k in range(len(dong_data))                              :
        if Dataset['행정동'][i] == dong_data['행정동'][k]       : 
            IGH = f'{i}'
            IGH_list.append(IGH)
            break

#(2) 처리 결과 확인하기. 
if len(IGH_list) == len(Dataset) :
    print('COMPLETE INTEGRITY.')
else                                                            :
    for i in range(len(Dataset))                                :
        for k in range(len(dong_data))                          :
            if Dataset['행정동_코드'][i] == dong_data['행정동코드'][k] : 
                Dataset['행정동'][i] = dong_data['행정동'][k]
                break
    
    IGH_list = []
    for i in range(len(Dataset))                                :
        for k in range(len(dong_data))                          :
            if Dataset['행정동'][i] == dong_data['행정동'][k]   : 
                IGH = f'{i}'
                IGH_list.append(IGH)
                break
    IS_GOOD_DATASET =+ 1
    if len(IGH_list) == len(Dataset)                            :
        print('IMPERFECT INTEGRITY, SO THE CONVERSION CODE WORKED.')

COMPLETE INTEGRITY.

In [4]:
#04. 자치구 무결성 검사하기. 
#(1) 작업 시행하기. 
IGG_list = []
for i in range(len(Dataset))                                    :
    for k in range(len(dong_data))                              :
        if Dataset['자치구'][i] == dong_data['시군구명'][k]     : 
            IGG = f'{i}'
            IGG_list.append(IGG)
            break

#(2) 처리 결과 확인하기. 
if len(IGG_list) == len(Dataset)                                :
    print('COMPLETE INTEGRITY.')
else                                                            :
    for i in range(len(Dataset))                                :
        for k in range(len(dong_data))                          :
            if Dataset['행정동_코드'][i] == dong_data['행정동코드'][k] : 
                Dataset['자치구'][i] = dong_data['시군구명'][k]
                break
    
    IGG_list = []
    for i in range(len(Dataset))                                :
        for k in range(len(dong_data))                          :
            if Dataset['자치구'][i] == dong_data['시군구명'][k] : 
                IGG = f'{i}'
                IGG_list.append(IGG)
                break    
    IS_GOOD_DATASET =+ 1
    if len(IGG_list) == len(Dataset)                            :
        print('IMPERFECT INTEGRITY, SO THE CONVERSION CODE WORKED.')

COMPLETE INTEGRITY.

In [5]:
#05. 위도, 경도 좌표값 결측치 있는지 확인하기. 
#(1) 위도 값 파악하기. 
if Dataset['위도'].isna().sum() == 0 : 
    print('COMPLETE INTEGRITY.')
else                                 :
    IS_GOOD_DATASET =+ 1
    print('IMPERFECT INTEGRITY, SO YOU MUST DO SOME EXTRA WORK.')

COMPLETE INTEGRITY.

In [6]:
#(2) 경도 값 파악하기. 
if Dataset['경도'].isna().sum() == 0 : 
    print('COMPLETE INTEGRITY.')
else                                 :
    IS_GOOD_DATASET =+ 1
    print('IMPERFECT INTEGRITY, SO YOU MUST DO SOME EXTRA WORK.')

COMPLETE INTEGRITY.

In [7]:
#05. 처리 결과 저장하기.
if IS_GOOD_DATASET == 0 :
    print("YOU DON'T NEED TO DO ANY WORK.")
else                    :
    Dataset.to_excel('temp_file.xlsx', index=False)
    print('YOU MUST DO SOME EXTRA WORK.')

YOU DON'T NEED TO DO ANY WORK.