In [15]:
#2021.08.18. WED
#Team_밥믈리에
 
## Indicator Scaling
#00. 패키지 호출
import pandas as pd 
import warnings 
from sklearn.preprocessing import MinMaxScaler

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

In [23]:
#01. 데이터셋 전처리하기.
#(1) 데이터셋 불러오기.
cultivar_indicator_grouping = pd.read_excel('../data/nlp/cultivar_indicator_grouping.xlsx')

#(2) indicator 컬럼 인덱스 설정하기. 
cultivar_indicator_grouping.set_index('indicator', inplace=True)

#(3) 처리 결과 확인하기.
cultivar_indicator_grouping

,count_고시히카리,count_골드퀸,count_삼광,count_새청무,count_신동진,count_영호진미,count_오대,count_일품,count_진상,count_참드림,count_추청,count_히토메보레
indicator,,,,,,,,,,,,
고들하다,90,2,47,3,94,35,29,6,6,3,73,1
고소하다,176,187,130,8,272,66,86,25,12,22,184,10
달다,112,13,64,2,116,21,52,8,14,7,94,12
담백하다,10,64,10,0,16,5,12,3,0,0,12,0
부드럽다,58,2,60,0,74,34,21,4,6,3,87,20
쫀득하다,192,8,90,4,154,79,86,11,19,14,103,7
찰지다,233,14,147,5,321,127,133,28,29,19,188,6
촉촉하다,102,5,38,5,121,35,46,9,13,5,82,6

In [3]:
#(3) 기존 데이터셋의 전치 행렬 만들기. 
cultivar_indicator_grouping_T = cultivar_indicator_grouping.T

#(4) 처리 결과 확인하기. 
cultivar_indicator_grouping_T

indicator    고들하다  고소하다   달다  담백하다  부드럽다  쫀득하다  찰지다  촉촉하다
count_고시히카리    90   176  112    10    58   192  233   102
count_골드퀸       2   187   13    64     2     8   14     5
count_밀키퀸       0     3    1     1     1     0    2     0
count_삼광       47   130   64    10    60    90  147    38
count_새청무       3     8    2     0     0     4    5     5
count_신동진      94   272  116    16    74   154  321   121
count_영호진미     35    66   21     5    34    79  127    35
count_오대       29    86   52    12    21    86  133    46
count_일품        6    25    8     3     4    11   28     9
count_진상        6    12   14     0     6    19   29    13
count_참드림       3    22    7     0     3    14   19     5
count_추청       73   184   94    12    87   103  188    82
count_히토메보레     1    10   12     0    20     7    6     6
count_하이아미      2     2    1     0    25     1    2     1

In [4]:
#02. 데이터셋 컬럼 별로 스케일링하기.
#(1) MinMaxScaler 객체 할당하기.
scaler = MinMaxScaler()

#(2) 스케일링 처리하기. 
cultivar_indicator_scaling = pd.DataFrame(
    scaler.fit_transform(cultivar_indicator_grouping),
    columns=cultivar_indicator_grouping.columns, 
    index=cultivar_indicator_grouping.index
)

#(3) 데이터프레임으로 변환하기. 
cultivar_indicator_scaling

,count_고시히카리,count_골드퀸,count_밀키퀸,count_삼광,count_새청무,count_신동진,count_영호진미,count_오대,count_일품,count_진상,count_참드림,count_추청,count_히토메보레,count_하이아미
indicator,,,,,,,,,,,,,,
고들하다,0.358744,0.000000,0.000000,0.270073,0.375,0.255738,0.245902,0.140496,0.12,0.206897,0.136364,0.346591,0.05,0.08
고소하다,0.744395,1.000000,1.000000,0.875912,1.000,0.839344,0.500000,0.611570,0.88,0.413793,1.000000,0.977273,0.50,0.08
달다,0.457399,0.059459,0.333333,0.394161,0.250,0.327869,0.131148,0.330579,0.20,0.482759,0.318182,0.465909,0.60,0.04
담백하다,0.000000,0.335135,0.333333,0.000000,0.000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.00
부드럽다,0.215247,0.000000,0.333333,0.364964,0.000,0.190164,0.237705,0.074380,0.04,0.206897,0.136364,0.426136,1.00,1.00
쫀득하다,0.816143,0.032432,0.000000,0.583942,0.500,0.452459,0.606557,0.611570,0.32,0.655172,0.636364,0.517045,0.35,0.04
찰지다,1.000000,0.064865,0.666667,1.000000,0.625,1.000000,1.000000,1.000000,1.00,1.000000,0.863636,1.000000,0.30,0.08
촉촉하다,0.412556,0.016216,0.000000,0.204380,0.625,0.344262,0.245902,0.280992,0.24,0.448276,0.227273,0.397727,0.30,0.04

In [5]:
#(3) 데이터셋 저장하기. 
cultivar_indicator_scaling.T.to_excel('../data/nlp/cultivar_indicator_scaling.xlsx')

In [19]:
#03-1. 전체 유효 데이터 갯수로 나누어 스케일링하기.
#(1) 해당 값 전체 유효 데이터 개수로 나누고 100 곱하기. 
cultivar_indicator_scaling_02 = cultivar_indicator_grouping
cultivar_indicator_scaling_02['count_고시히카리'] = cultivar_indicator_grouping['count_고시히카리']/7724 * 100
cultivar_indicator_scaling_02['count_골드퀸'] = cultivar_indicator_grouping['count_골드퀸']/523 * 100
#cultivar_indicator_scaling_02['count_밀키퀸'] = cultivar_indicator_grouping['count_밀키퀸']/47 * 100
cultivar_indicator_scaling_02['count_삼광'] = cultivar_indicator_grouping['count_삼광']/5021 * 100
#cultivar_indicator_scaling_02['count_새누리'] = cultivar_indicator_grouping['count_새누리']/86 * 100
cultivar_indicator_scaling_02['count_새청무'] = cultivar_indicator_grouping['count_새청무']/170 * 100
cultivar_indicator_scaling_02['count_신동진'] = cultivar_indicator_grouping['count_신동진']/9438 * 100
cultivar_indicator_scaling_02['count_영호진미'] = cultivar_indicator_grouping['count_영호진미']/2979 * 100
cultivar_indicator_scaling_02['count_오대'] = cultivar_indicator_grouping['count_오대']/4556 * 100
cultivar_indicator_scaling_02['count_일품'] = cultivar_indicator_grouping['count_일품']/785 * 100
cultivar_indicator_scaling_02['count_진상'] = cultivar_indicator_grouping['count_진상']/1252 * 100
cultivar_indicator_scaling_02['count_참드림'] = cultivar_indicator_grouping['count_참드림']/610 * 100
cultivar_indicator_scaling_02['count_추청'] = cultivar_indicator_grouping['count_추청']/5701 * 100
#cultivar_indicator_scaling_02['count_하이아미'] = cultivar_indicator_grouping['count_하이아미']/134 * 100
cultivar_indicator_scaling_02['count_히토메보레'] = cultivar_indicator_grouping['count_히토메보레']/429 * 100

#(2) 처리 결과 확인하기. 
cultivar_indicator_scaling_02

,count_고시히카리,count_골드퀸,count_삼광,count_새청무,count_신동진,count_영호진미,count_오대,count_일품,count_진상,count_참드림,count_추청,count_하이아미,count_히토메보레
indicator,,,,,,,,,,,,,
고들하다,1.165199,0.382409,0.936069,1.764706,0.995974,1.174891,0.636523,0.764331,0.479233,0.491803,1.280477,1.492537,0.233100
고소하다,2.278612,35.755258,2.589126,4.705882,2.881967,2.215509,1.887621,3.184713,0.958466,3.606557,3.227504,1.492537,2.331002
달다,1.450026,2.485660,1.274646,1.176471,1.229074,0.704935,1.141352,1.019108,1.118211,1.147541,1.648834,0.746269,2.797203
담백하다,0.129467,12.237094,0.199164,0.000000,0.169527,0.167842,0.263389,0.382166,0.000000,0.000000,0.210489,0.000000,0.000000
부드럽다,0.750906,0.382409,1.194981,0.000000,0.784064,1.141323,0.460931,0.509554,0.479233,0.491803,1.526048,18.656716,4.662005
쫀득하다,2.485759,1.529637,1.792472,2.352941,1.631702,2.651897,1.887621,1.401274,1.517572,2.295082,1.806701,0.746269,1.631702
찰지다,3.016572,2.676864,2.927704,2.941176,3.401144,4.263176,2.919227,3.566879,2.316294,3.114754,3.297667,1.492537,1.398601
촉촉하다,1.320559,0.956023,0.756821,2.941176,1.282051,1.174891,1.009658,1.146497,1.038339,0.819672,1.438344,0.746269,1.398601

In [20]:
#(4) 데이터셋 저장하기.
cultivar_indicator_scaling_02.to_excel('../data/nlp/cultivar_indicator_scaling_02.xlsx')

In [14]:
import pandas as pd
cultivar_indicator_scaling_02 = pd.read_excel('../data/nlp/cultivar_indicator_scaling_02.xlsx')
cultivar_indicator_scaling_02.set_index('indicator', inplace=True)
cultivar_indicator_scaling_02

FileNotFoundError: [Errno 2] No such file or directory: '../data/nlp/cultivar_indicator_scaling_02.xlsx'

In [21]:
#03-2. 지표 별로 MinmaxScaling 처리하기. 
#(1) 객체 할당하기.
scaler = MinMaxScaler()

#(2) 스케일링 처리하기. 
cultivar_indicator_scaling_03 = pd.DataFrame(
    scaler.fit_transform(cultivar_indicator_scaling_02.T),
    columns=cultivar_indicator_scaling_02.T.columns, 
    index=cultivar_indicator_scaling_02.T.index
)

#(3) 데이터프레임으로 변환하기. 
cultivar_indicator_scaling_03

indicator,고들하다,고소하다,달다,담백하다,부드럽다,쫀득하다,찰지다,촉촉하다
count_고시히카리,0.608576,0.037939,0.356117,0.010580,0.040249,0.912817,0.564821,0.261647
count_골드퀸,0.097485,1.000000,0.851098,1.000000,0.020497,0.411081,0.446231,0.095564
count_삼광,0.458975,0.046862,0.272294,0.016275,0.064051,0.549007,0.533797,0.004808
count_새청무,1.000000,0.107694,0.225371,0.000000,0.000000,0.843120,0.538501,1.000000
count_신동진,0.498087,0.055278,0.250513,0.013854,0.042026,0.464641,0.699072,0.244103
count_영호진미,0.614904,0.036125,0.000000,0.013716,0.061175,1.000000,1.000000,0.195280
count_오대,0.263399,0.026702,0.208586,0.021524,0.024706,0.598938,0.530838,0.120000
count_일품,0.346846,0.063979,0.150159,0.031230,0.027312,0.343721,0.756928,0.182344
count_진상,0.160703,0.000000,0.197525,0.000000,0.025687,0.404750,0.320359,0.133067
count_참드림,0.168910,0.076102,0.211544,0.000000,0.026361,0.812757,0.599095,0.033443
count_추청,0.683842,0.065208,0.451137,0.017201,0.081796,0.556474,0.662949,0.315310
count_하이아미,0.822299,0.015348,0.019756,0.000000,1.000000,0.000000,0.032792,0.000000
count_히토메보레,0.000000,0.039444,1.000000,0.000000,0.249883,0.464641,0.000000,0.297203

In [22]:
#(4) 데이터셋 저장하기. 
cultivar_indicator_scaling_03.to_excel('../data/nlp/cultivar_indicator_scaling_03.xlsx')

In [10]:
#04. 전치 데이터셋 스케일링하기.
#(1) 스케일링 처리하기. 
cultivar_indicator_scaling_T = pd.DataFrame(
    scaler.fit_transform(cultivar_indicator_grouping_T),
    columns=cultivar_indicator_grouping_T.columns, 
    index=cultivar_indicator_grouping_T.index
)

#(3) 데이터프레임으로 변환하기. 
cultivar_indicator_scaling_T

indicator,고들하다,고소하다,달다,담백하다,부드럽다,쫀득하다,찰지다,촉촉하다
count_고시히카리,0.957447,0.644444,0.965217,0.156250,0.666667,1.000000,0.724138,0.842975
count_골드퀸,0.021277,0.685185,0.104348,1.000000,0.022989,0.041667,0.037618,0.041322
count_밀키퀸,0.000000,0.003704,0.000000,0.015625,0.011494,0.000000,0.000000,0.000000
count_삼광,0.500000,0.474074,0.547826,0.156250,0.689655,0.468750,0.454545,0.314050
count_새청무,0.031915,0.022222,0.008696,0.000000,0.000000,0.020833,0.009404,0.041322
count_신동진,1.000000,1.000000,1.000000,0.250000,0.850575,0.802083,1.000000,1.000000
count_영호진미,0.372340,0.237037,0.173913,0.078125,0.390805,0.411458,0.391850,0.289256
count_오대,0.308511,0.311111,0.443478,0.187500,0.241379,0.447917,0.410658,0.380165
count_일품,0.063830,0.085185,0.060870,0.046875,0.045977,0.057292,0.081505,0.074380
count_진상,0.063830,0.037037,0.113043,0.000000,0.068966,0.098958,0.084639,0.107438
count_참드림,0.031915,0.074074,0.052174,0.000000,0.034483,0.072917,0.053292,0.041322
count_추청,0.776596,0.674074,0.808696,0.187500,1.000000,0.536458,0.583072,0.677686
count_히토메보레,0.010638,0.029630,0.095652,0.000000,0.229885,0.036458,0.012539,0.049587
count_하이아미,0.021277,0.000000,0.000000,0.000000,0.287356,0.005208,0.000000,0.008264

In [11]:
#(4) 데이터셋 저장하기. 
cultivar_indicator_scaling_T.to_excel('../data/nlp/cultivar_indicator_scaling_T.xlsx')