In [2]:
#2021.08.18. WED
#Team_밥믈리에

#00. 패키지 호출
import pandas as pd 
import warnings 
from sklearn.preprocessing import MinMaxScaler

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

In [3]:
#01. 데이터셋 전처리하기.
#(1) 데이터셋 불러오기.
cultivar_indicator_grouping = pd.read_excel('../data/nlp/cultivar_idicator_grouping.xlsx')

#(2) indicator 컬럼 인덱스 설정하기. 
cultivar_indicator_grouping.set_index('indicator', inplace=True)

#(3) 처리 결과 확인하기.
cultivar_indicator_grouping

,count_고시히카리,count_골드퀸,count_밀키퀸,count_삼광,count_새청무,count_신동진,count_영호진미,count_오대,count_일품,count_진상,count_참드림,count_추청,count_하이아미,count_히토메보레
indicator,,,,,,,,,,,,,,
고소하다,177,189,3,131,8,272,66,86,25,12,22,184,2,10
고슬하다,49,1,0,28,1,36,18,16,2,3,2,33,0,0
꼬들하다,26,1,0,11,0,35,11,11,3,2,0,27,2,1
달다,112,13,1,64,2,116,21,52,8,14,7,94,1,12
딱딱하다,8,1,0,13,0,32,15,11,1,4,0,15,0,1
부드럽다,39,1,0,24,0,41,25,13,3,5,2,62,1,3
질다,23,2,0,11,1,29,12,14,2,1,2,35,0,1
쫀득하다,192,8,0,90,4,154,79,86,11,19,14,103,1,7
찰지다,234,14,2,147,5,322,129,135,28,29,19,189,2,6
촉촉하다,77,3,0,26,4,83,22,28,6,9,3,45,0,4
탱탱하다,69,1,0,30,1,118,17,31,1,7,8,40,0,3
푸석하다,69,4,1,62,2,142,73,73,13,16,4,169,2,0

In [4]:
#(3) 기존 데이터셋의 전치 행렬 만들기. 
cultivar_indicator_grouping_T = cultivar_indicator_grouping.T

#(4) 처리 결과 확인하기. 
cultivar_indicator_grouping_T

indicator,고소하다,고슬하다,꼬들하다,달다,딱딱하다,부드럽다,질다,쫀득하다,찰지다,촉촉하다,탱탱하다,푸석하다
count_고시히카리,177,49,26,112,8,39,23,192,234,77,69,69
count_골드퀸,189,1,1,13,1,1,2,8,14,3,1,4
count_밀키퀸,3,0,0,1,0,0,0,0,2,0,0,1
count_삼광,131,28,11,64,13,24,11,90,147,26,30,62
count_새청무,8,1,0,2,0,0,1,4,5,4,1,2
count_신동진,272,36,35,116,32,41,29,154,322,83,118,142
count_영호진미,66,18,11,21,15,25,12,79,129,22,17,73
count_오대,86,16,11,52,11,13,14,86,135,28,31,73
count_일품,25,2,3,8,1,3,2,11,28,6,1,13
count_진상,12,3,2,14,4,5,1,19,29,9,7,16
count_참드림,22,2,0,7,0,2,2,14,19,3,8,4
count_추청,184,33,27,94,15,62,35,103,189,45,40,169
count_하이아미,2,0,2,1,0,1,0,1,2,0,0,2
count_히토메보레,10,0,1,12,1,3,1,7,6,4,3,0

In [5]:
#02. 데이터셋 스케일링하기.
#(1) Min-Max Scaler 객체 할당하기.
scaler = MinMaxScaler()

#(2) 스케일링 처리하기. 
cultivar_indicator_scaling = pd.DataFrame(
    scaler.fit_transform(cultivar_indicator_grouping),
    columns=cultivar_indicator_grouping.columns, 
    index=cultivar_indicator_grouping.index)

#(3) 데이터프레임으로 변환하기. 
cultivar_indicator_scaling

,count_고시히카리,count_골드퀸,count_밀키퀸,count_삼광,count_새청무,count_신동진,count_영호진미,count_오대,count_일품,count_진상,count_참드림,count_추청,count_하이아미,count_히토메보레
indicator,,,,,,,,,,,,,,
고소하다,0.747788,1.000000,1.000000,0.882353,1.000,0.829352,0.466102,0.604839,0.888889,0.392857,1.000000,0.971264,1.0,0.833333
고슬하다,0.181416,0.000000,0.000000,0.125000,0.125,0.023891,0.059322,0.040323,0.037037,0.071429,0.090909,0.103448,0.0,0.000000
꼬들하다,0.079646,0.000000,0.000000,0.000000,0.000,0.020478,0.000000,0.000000,0.074074,0.035714,0.000000,0.068966,1.0,0.083333
달다,0.460177,0.063830,0.333333,0.389706,0.250,0.296928,0.084746,0.330645,0.259259,0.464286,0.318182,0.454023,0.5,1.000000
딱딱하다,0.000000,0.000000,0.000000,0.014706,0.000,0.010239,0.033898,0.000000,0.000000,0.107143,0.000000,0.000000,0.0,0.083333
부드럽다,0.137168,0.000000,0.000000,0.095588,0.000,0.040956,0.118644,0.016129,0.074074,0.142857,0.090909,0.270115,0.5,0.250000
질다,0.066372,0.005319,0.000000,0.000000,0.125,0.000000,0.008475,0.024194,0.037037,0.000000,0.090909,0.114943,0.0,0.083333
쫀득하다,0.814159,0.037234,0.000000,0.580882,0.500,0.426621,0.576271,0.604839,0.370370,0.642857,0.636364,0.505747,0.5,0.583333
찰지다,1.000000,0.069149,0.666667,1.000000,0.625,1.000000,1.000000,1.000000,1.000000,1.000000,0.863636,1.000000,1.0,0.500000
촉촉하다,0.305310,0.010638,0.000000,0.110294,0.500,0.184300,0.093220,0.137097,0.185185,0.285714,0.136364,0.172414,0.0,0.333333
탱탱하다,0.269912,0.000000,0.000000,0.139706,0.125,0.303754,0.050847,0.161290,0.000000,0.214286,0.363636,0.143678,0.0,0.250000
푸석하다,0.269912,0.015957,0.333333,0.375000,0.250,0.385666,0.525424,0.500000,0.444444,0.535714,0.181818,0.885057,1.0,0.000000

In [6]:
#(3) 데이터셋 저장하기. 
cultivar_indicator_scaling.T.to_excel('../data/nlp/cultivar_indicator_scaling.xlsx')

In [7]:
#03. 전체 유효 데이터 갯수로 나누어 스케일링하기.
#(1) 해당 값 전체 유효 데이터 개수로 나누고 100 곱하기. 
cultivar_indicator_scaling_02 = cultivar_indicator_grouping
cultivar_indicator_scaling_02['count_고시히카리'] = cultivar_indicator_grouping['count_고시히카리']/7724 * 100
cultivar_indicator_scaling_02['count_골드퀸'] = cultivar_indicator_grouping['count_골드퀸']/523 * 100
cultivar_indicator_scaling_02['count_밀키퀸'] = cultivar_indicator_grouping['count_밀키퀸']/47 * 100
cultivar_indicator_scaling_02['count_삼광'] = cultivar_indicator_grouping['count_삼광']/5021 * 100
#cultivar_indicator_scaling_02['count_새누리'] = cultivar_indicator_grouping['count_새누리']/86 * 100
cultivar_indicator_scaling_02['count_새청무'] = cultivar_indicator_grouping['count_새청무']/170 * 100
cultivar_indicator_scaling_02['count_신동진'] = cultivar_indicator_grouping['count_신동진']/9438 * 100
cultivar_indicator_scaling_02['count_영호진미'] = cultivar_indicator_grouping['count_영호진미']/2979 * 100
cultivar_indicator_scaling_02['count_오대'] = cultivar_indicator_grouping['count_오대']/4556 * 100
cultivar_indicator_scaling_02['count_일품'] = cultivar_indicator_grouping['count_일품']/785 * 100
cultivar_indicator_scaling_02['count_진상'] = cultivar_indicator_grouping['count_진상']/1252 * 100
cultivar_indicator_scaling_02['count_참드림'] = cultivar_indicator_grouping['count_참드림']/610 * 100
cultivar_indicator_scaling_02['count_추청'] = cultivar_indicator_grouping['count_추청']/5701 * 100
cultivar_indicator_scaling_02['count_하이아미'] = cultivar_indicator_grouping['count_하이아미']/134 * 100
cultivar_indicator_scaling_02['count_히토메보레'] = cultivar_indicator_grouping['count_히토메보레']/429 * 100

#(2) 처리 결과 확인하기. 
cultivar_indicator_scaling_02

,count_고시히카리,count_골드퀸,count_밀키퀸,count_삼광,count_새청무,count_신동진,count_영호진미,count_오대,count_일품,count_진상,count_참드림,count_추청,count_하이아미,count_히토메보레
indicator,,,,,,,,,,,,,,
고소하다,2.291559,36.137667,6.382979,2.609042,4.705882,2.881967,2.215509,1.887621,3.184713,0.958466,3.606557,3.227504,1.492537,2.331002
고슬하다,0.634386,0.191205,0.000000,0.557658,0.588235,0.381437,0.604230,0.351185,0.254777,0.239617,0.327869,0.578846,0.000000,0.000000
꼬들하다,0.336613,0.191205,0.000000,0.219080,0.000000,0.370841,0.369251,0.241440,0.382166,0.159744,0.000000,0.473601,1.492537,0.233100
달다,1.450026,2.485660,2.127660,1.274646,1.176471,1.229074,0.704935,1.141352,1.019108,1.118211,1.147541,1.648834,0.746269,2.797203
딱딱하다,0.103573,0.191205,0.000000,0.258913,0.000000,0.339055,0.503525,0.241440,0.127389,0.319489,0.000000,0.263112,0.000000,0.233100
부드럽다,0.504920,0.191205,0.000000,0.477992,0.000000,0.434414,0.839208,0.285338,0.382166,0.399361,0.327869,1.087529,0.746269,0.699301
질다,0.297773,0.382409,0.000000,0.219080,0.588235,0.307268,0.402820,0.307287,0.254777,0.079872,0.327869,0.613927,0.000000,0.233100
쫀득하다,2.485759,1.529637,0.000000,1.792472,2.352941,1.631702,2.651897,1.887621,1.401274,1.517572,2.295082,1.806701,0.746269,1.631702
찰지다,3.029518,2.676864,4.255319,2.927704,2.941176,3.411740,4.330312,2.963126,3.566879,2.316294,3.114754,3.315208,1.492537,1.398601
촉촉하다,0.996893,0.573614,0.000000,0.517825,2.352941,0.879424,0.738503,0.614574,0.764331,0.718850,0.491803,0.789335,0.000000,0.932401
탱탱하다,0.893320,0.191205,0.000000,0.597491,0.588235,1.250265,0.570661,0.680421,0.127389,0.559105,1.311475,0.701631,0.000000,0.699301
푸석하다,0.893320,0.764818,2.127660,1.234814,1.176471,1.504556,2.450487,1.602283,1.656051,1.277955,0.655738,2.964392,1.492537,0.000000

In [8]:
#(3) 데이터셋 저장하기. 
cultivar_indicator_scaling_02.T.to_excel('../data/nlp/cultivar_indicator_scaling_02.xlsx')

In [9]:
#04. 전치 데이터셋 스케일링하기.
#(1) 스케일링 처리하기. 
cultivar_indicator_scaling_T = pd.DataFrame(
    scaler.fit_transform(cultivar_indicator_grouping_T),
    columns=cultivar_indicator_grouping_T.columns, 
    index=cultivar_indicator_grouping_T.index)

#(3) 데이터프레임으로 변환하기. 
cultivar_indicator_scaling_T

indicator,고소하다,고슬하다,꼬들하다,달다,딱딱하다,부드럽다,질다,쫀득하다,찰지다,촉촉하다,탱탱하다,푸석하다
count_고시히카리,0.648148,1.000000,0.742857,0.965217,0.25000,0.629032,0.657143,1.000000,0.725000,0.927711,0.584746,0.408284
count_골드퀸,0.692593,0.020408,0.028571,0.104348,0.03125,0.016129,0.057143,0.041667,0.037500,0.036145,0.008475,0.023669
count_밀키퀸,0.003704,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005917
count_삼광,0.477778,0.571429,0.314286,0.547826,0.40625,0.387097,0.314286,0.468750,0.453125,0.313253,0.254237,0.366864
count_새청무,0.022222,0.020408,0.000000,0.008696,0.00000,0.000000,0.028571,0.020833,0.009375,0.048193,0.008475,0.011834
count_신동진,1.000000,0.734694,1.000000,1.000000,1.00000,0.661290,0.828571,0.802083,1.000000,1.000000,1.000000,0.840237
count_영호진미,0.237037,0.367347,0.314286,0.173913,0.46875,0.403226,0.342857,0.411458,0.396875,0.265060,0.144068,0.431953
count_오대,0.311111,0.326531,0.314286,0.443478,0.34375,0.209677,0.400000,0.447917,0.415625,0.337349,0.262712,0.431953
count_일품,0.085185,0.040816,0.085714,0.060870,0.03125,0.048387,0.057143,0.057292,0.081250,0.072289,0.008475,0.076923
count_진상,0.037037,0.061224,0.057143,0.113043,0.12500,0.080645,0.028571,0.098958,0.084375,0.108434,0.059322,0.094675
count_참드림,0.074074,0.040816,0.000000,0.052174,0.00000,0.032258,0.057143,0.072917,0.053125,0.036145,0.067797,0.023669
count_추청,0.674074,0.673469,0.771429,0.808696,0.46875,1.000000,1.000000,0.536458,0.584375,0.542169,0.338983,1.000000
count_하이아미,0.000000,0.000000,0.057143,0.000000,0.00000,0.016129,0.000000,0.005208,0.000000,0.000000,0.000000,0.011834
count_히토메보레,0.029630,0.000000,0.028571,0.095652,0.03125,0.048387,0.028571,0.036458,0.012500,0.048193,0.025424,0.000000

In [ ]:
#(4) 데이터셋 저장하기. 
cultivar_indicator_scaling_T.to_excel('../data/nlp/cultivar_indicator_scaling_T.xlsx')