In [2]:
#2021.10.20. TUE
#Team_SmokeFree

## Data Preprocessing For MCLP 
#00. 패키지 호출하기. 
import warnings
import re
import pandas as pd 
import numpy as np 
import geopandas as gpd
from fiona.crs import from_epsg
import requests

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

#01. kakao_api_key.txt 파일 부르기. 
with open("A:/Python_Project/Team_SmokeFree/key/kakao_api_key.txt",mode="r") as key_file :
    kakao_api_key = key_file.read()

In [3]:
#01. RANDOM_POINT 데이터셋 전처리하기. 
#(1) RANDOM_POINT 데이터셋 불러오기. 
RANDOM_POINT = pd.read_csv('temp_file_03.csv', encoding='utf-8')

#(2) 처리 결과 확인하기. 
RANDOM_POINT

       rand_point SGG_NM                                     geometry
0               0    금천구  POINT (126.9134055885386 37.44996180218595)
1               1    금천구  POINT (126.9143943524618 37.44996374526017)
2               2    금천구  POINT (126.9142583604479 37.44993860398068)
3               3    금천구  POINT (126.9132887655418 37.44995610565504)
4               4    금천구  POINT (126.9136375368365 37.45000822498514)
...           ...    ...                                          ...
40286       41191    동작구  POINT (126.9536105492901 37.49994690939378)
40287       41192    동작구  POINT (126.9536832343939 37.50027154889482)
40288       41193    동작구  POINT (126.9537327787121 37.50010520158163)
40289       41194    동작구  POINT (126.9537081199655 37.50054022273152)
40290       41195    동작구   POINT (126.9535831660898 37.4998261925987)

[40291 rows x 3 columns]

In [4]:
#(3) 위도, 경도 추출하기. 
RANDOM_POINT['위도'] = np.nan
RANDOM_POINT['경도'] = np.nan

for i in range(len(RANDOM_POINT)) :
    RANDOM_POINT['경도'][i] = float(re.sub('[^0-9.]','', RANDOM_POINT['geometry'][i].split(' ')[1]))
    RANDOM_POINT['위도'][i] = float(re.sub('[^0-9.]','', RANDOM_POINT['geometry'][i].split(' ')[2]))

#(4) 처리 결과 확인하기. 
RANDOM_POINT

,rand_point,SGG_NM,geometry,위도,경도
0,0,금천구,POINT (126.9134055885386 37.44996180218595),37.449962,126.913406
1,1,금천구,POINT (126.9143943524618 37.44996374526017),37.449964,126.914394
2,2,금천구,POINT (126.9142583604479 37.44993860398068),37.449939,126.914258
3,3,금천구,POINT (126.9132887655418 37.44995610565504),37.449956,126.913289
4,4,금천구,POINT (126.9136375368365 37.45000822498514),37.450008,126.913638
...,...,...,...,...,...
40286,41191,동작구,POINT (126.9536105492901 37.49994690939378),37.499947,126.953611
40287,41192,동작구,POINT (126.9536832343939 37.50027154889482),37.500272,126.953683
40288,41193,동작구,POINT (126.9537327787121 37.50010520158163),37.500105,126.953733
40289,41194,동작구,POINT (126.9537081199655 37.50054022273152),37.500540,126.953708
40290,41195,동작구,POINT (126.9535831660898 37.4998261925987),37.499826,126.953583

In [5]:
#(5) 다음 작업을 위한 복사본 저장하기. 
RANDOM_POINT_no_HGD = RANDOM_POINT

In [6]:
# API LIMIT TEST 
# local_url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
# x = 126.973899
# y = 37.5701764
# url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
# REQ_RESULT = requests.get(url, headers={"Authorization":f"KakaoAK {kakao_api_key}"}).json()
# REQ_RESULT

{'meta': {'total_count': 2},
 'documents': [{'region_type': 'B',
   'code': '1111012000',
   'address_name': '서울특별시 종로구 신문로1가',
   'region_1depth_name': '서울특별시',
   'region_2depth_name': '종로구',
   'region_3depth_name': '신문로1가',
   'region_4depth_name': '',
   'x': 126.97390161420634,
   'y': 37.57017314981071},
  {'region_type': 'H',
   'code': '1111053000',
   'address_name': '서울특별시 종로구 사직동',
   'region_1depth_name': '서울특별시',
   'region_2depth_name': '종로구',
   'region_3depth_name': '사직동',
   'region_4depth_name': '',
   'x': 126.96884605608865,
   'y': 37.57618696588561}]}

In [9]:
#03. API 이용하여 정보 추출하기. 
#(1) 주소지를 기반으로 행정동 코드, 경도, 위도 추출하여 리스트에 추가하기. 
RANDOM_POINT_no_HGD_x       = RANDOM_POINT_no_HGD['경도'].values
RANDOM_POINT_no_HGD_y       = RANDOM_POINT_no_HGD['위도'].values
RANDOM_POINT_no_HGD_자치구      = []
RANDOM_POINT_no_HGD_행정동_코드 = []

local_url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
for num in range(len(RANDOM_POINT_no_HGD_x))                                                        :
    try                                                                                             :
        x = RANDOM_POINT_no_HGD_x[num]
        y = RANDOM_POINT_no_HGD_y[num]   
        url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
    except Exception                                                                                :
        x = RANDOM_POINT_no_HGD_x[num]
        y = RANDOM_POINT_no_HGD_y[num]      
        url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
    try                                                                                             : 
        REQ_RESULT = requests.get(url, headers={"Authorization":f"KakaoAK {kakao_api_key}"}).json()
        RANDOM_POINT_no_HGD_자치구.append(REQ_RESULT['documents'][1]['region_2depth_name'])
        RANDOM_POINT_no_HGD_행정동_코드.append(REQ_RESULT['documents'][1]['code'])
        print(f'DONE ! index_num = {num}')
    except Exception                                                                                :
        try                                                                                         :
            x = RANDOM_POINT_no_HGD_x[num]
            y = RANDOM_POINT_no_HGD_y[num]   
            url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
            REQ_RESULT = requests.get(url, headers={"Authorization":f"KakaoAK {kakao_api_key}"}).json()
            RANDOM_POINT_no_HGD_자치구.append(REQ_RESULT['documents'][1]['region_2depth_name'])
            RANDOM_POINT_no_HGD_행정동_코드.append(REQ_RESULT['documents'][1]['code'])
            print(f'DONE ! index_num = {num}')
        except Exception                                                                            :
            RANDOM_POINT_no_HGD_자치구.append('ERROR')
            RANDOM_POINT_no_HGD_행정동_코드.append('ERROR')
            print(f'ERROR ! index_num = {num}')

DONE ! index_num = 0
DONE ! index_num = 1
DONE ! index_num = 2
DONE ! index_num = 3
DONE ! index_num = 4
DONE ! index_num = 5
DONE ! index_num = 6
DONE ! index_num = 7
DONE ! index_num = 8
DONE ! index_num = 9
DONE ! index_num = 10
DONE ! index_num = 11
DONE ! index_num = 12
DONE ! index_num = 13
DONE ! index_num = 14
DONE ! index_num = 15
DONE ! index_num = 16
DONE ! index_num = 17
DONE ! index_num = 18
DONE ! index_num = 19
DONE ! index_num = 20
DONE ! index_num = 21
DONE ! index_num = 22
DONE ! index_num = 23
DONE ! index_num = 24
DONE ! index_num = 25
DONE ! index_num = 26
DONE ! index_num = 27
DONE ! index_num = 28
DONE ! index_num = 29
DONE ! index_num = 30
DONE ! index_num = 31
DONE ! index_num = 32
DONE ! index_num = 33
DONE ! index_num = 34
DONE ! index_num = 35
DONE ! index_num = 36
DONE ! index_num = 37
DONE ! index_num = 38
DONE ! index_num = 39
DONE ! index_num = 40
DONE ! index_num = 41
DONE ! index_num = 42
DONE ! index_num = 43
DONE ! index_num = 44
DONE ! index_num = 45
DONE ! index_num = 46
DONE ! index_num = 47
DONE ! index_num = 48
DONE ! index_num = 49
DONE ! index_num = 50
DONE ! index_num = 51
DONE ! index_num = 52
DONE ! index_num = 53
DONE ! index_num = 54
DONE ! index_num = 55
DONE ! index_num = 56
DONE ! index_num = 57
DONE ! index_num = 58
DONE ! index_num = 59
DONE ! index_num = 60
DONE ! index_num = 61
DONE ! index_num = 62
DONE ! index_num = 63
DONE ! index_num = 64
DONE ! index_num = 65
DONE ! index_num = 66
DONE ! index_num = 67
DONE ! index_num = 68
DONE ! index_num = 69
DONE ! index_num = 70
DONE ! index_num = 71
DONE ! index_num = 72
DONE ! index_num = 73
DONE ! index_num = 74
DONE ! index_num = 75
DONE ! index_num = 76
DONE ! index_num = 77
DONE ! index_num = 78
DONE ! index_num = 79
DONE ! index_num = 80
DONE ! index_num = 81
DONE ! index_num = 82
DONE ! index_num = 83
DONE ! index_num = 84
DONE ! index_num = 85
DONE ! index_num = 86
DONE ! index_num = 87
DONE ! index_num = 88
DONE ! index_num = 89
DONE ! index_num = 90
DONE ! index_num = 91
DONE ! index_num = 92
DONE ! index_num = 93
DONE ! index_num = 94
DONE ! index_num = 95
DONE ! index_num = 96
DONE ! index_num = 97
DONE ! index_num = 98
DONE ! index_num = 99
DONE ! index_num = 100
DONE ! index_num = 101
DONE ! index_num = 102
DONE ! index_num = 103
DONE ! index_num = 104
DONE ! index_num = 105
DONE ! index_num = 106
DONE ! index_num = 107
DONE ! index_num = 108
DONE ! index_num = 109
DONE ! index_num = 110
DONE ! index_num = 111
DONE ! index_num = 112
DONE ! index_num = 113
DONE ! index_num = 114
DONE ! index_num = 115
DONE ! index_num = 116
DONE ! index_num = 117
DONE ! index_num = 118
DONE ! index_num = 119
DONE ! index_num = 120
DONE ! index_num = 121
DONE ! index_num = 122
DONE ! index_num = 123
DONE ! index_num = 124
DONE ! index_num = 125
DONE ! index_num = 126
DONE ! index_num = 127
DONE ! index_num = 128
DONE ! index_num = 129
DONE ! index_num = 130
DONE ! index_num = 131
DONE ! index_num = 132
DONE ! index_num = 133
DONE ! index_num = 134
DONE ! index_num = 135
DONE ! index_num = 136
DONE ! index_num = 137
DONE ! index_num = 138
DONE ! index_num = 139
DONE ! index_num = 140
DONE ! index_num = 141
DONE ! index_num = 142
DONE ! index_num = 143
DONE ! index_num = 144
DONE ! index_num = 145
DONE ! index_num = 146
DONE ! index_num = 147
DONE ! index_num = 148
DONE ! index_num = 149
DONE ! index_num = 150
DONE ! index_num = 151
DONE ! index_num = 152
DONE ! index_num = 153
DONE ! index_num = 154
DONE ! index_num = 155
DONE ! index_num = 156
DONE ! index_num = 157
DONE ! index_num = 158
DONE ! index_num = 159
DONE ! index_num = 160
DONE ! index_num = 161
DONE ! index_num = 162
DONE ! index_num = 163
DONE ! index_num = 164
DONE ! index_num = 165
DONE ! index_num = 166
DONE ! index_num = 167
DONE ! index_num = 168
DONE ! index_num = 169
DONE ! index_num = 170
DONE ! index_num = 171
DONE ! index_num = 172
DONE ! index_num = 173
DONE ! index_num = 174
DONE ! index_num = 175
DONE ! index_num = 176
DONE ! index_num = 177
DONE ! index_num = 178
DONE ! index_num = 179
DONE ! index_num = 180
DONE ! index_num = 181
DONE ! index_num = 182
DONE ! index_num = 183
DONE ! index_num = 184
DONE ! index_num = 185
DONE ! index_num = 186
DONE ! index_num = 187
DONE ! index_num = 188
DONE ! index_num = 189
DONE ! index_num = 190
DONE ! index_num = 191
DONE ! index_num = 192
DONE ! index_num = 193
DONE ! index_num = 194
DONE ! index_num = 195
DONE ! index_num = 196
DONE ! index_num = 197
DONE ! index_num = 198
DONE ! index_num = 199
DONE ! index_num = 200
DONE ! index_num = 201
DONE ! index_num = 202
DONE ! index_num = 203
DONE ! index_num = 204
DONE ! index_num = 205
DONE ! index_num = 206
DONE ! index_num = 207
DONE ! index_num = 208
DONE ! index_num = 209
DONE ! index_num = 210
DONE ! index_num = 211
DONE ! index_num = 212
DONE ! index_num = 213
DONE ! index_num = 214
DONE ! index_num = 215
DONE ! index_num = 216
DONE ! index_num = 217
DONE ! index_num = 218
DONE ! index_num = 219
DONE ! index_num = 220
DONE ! index_num = 221
DONE ! index_num = 222
DONE ! index_num = 223
DONE ! index_num = 224
DONE ! index_num = 225
DONE ! index_num = 226
DONE ! index_num = 227
DONE ! index_num = 228
DONE ! index_num = 229
DONE ! index_num = 230
DONE ! index_num = 231
DONE ! index_num = 232
DONE ! index_num = 233
DONE ! index_num = 234
DONE ! index_num = 235
DONE ! index_num = 236
DONE ! index_num = 237
DONE ! index_num = 238
DONE ! index_num = 239
DONE ! index_num = 240
DONE ! index_num = 241
DONE ! index_num = 242
DONE ! index_num = 243
DONE ! index_num = 244
DONE ! index_num = 245
DONE ! index_num = 246
DONE ! index_num = 247
DONE ! index_num = 248
DONE ! index_num = 249
DONE ! index_num = 250
DONE ! index_num = 251
DONE ! index_num = 252
DONE ! index_num = 253
DONE ! index_num = 254
DONE ! index_num = 255
DONE ! index_num = 256
DONE ! index_num = 257
DONE ! index_num = 258
DONE ! index_num = 259
DONE ! index_num = 260
DONE ! index_num = 261
DONE ! index_num = 262
DONE ! index_num = 263
DONE ! index_num = 264
DONE ! index_num = 265
DONE ! index_num = 266
DONE ! index_num = 267
DONE ! index_num = 268
DONE ! index_num = 269
DONE ! index_num = 270
DONE ! index_num = 271
DONE ! index_num = 272
DONE ! index_num = 273
DONE ! index_num = 274
DONE ! index_num = 275
DONE ! index_num = 276
DONE ! index_num = 277
DONE ! index_num = 278
DONE ! index_num = 279
DONE ! index_num = 280
DONE ! index_num = 281
DONE ! index_num = 282
DONE ! index_num = 283
DONE ! index_num = 284
DONE ! index_num = 285
DONE ! index_num = 286
DONE ! index_num = 287
DONE ! index_num = 288
DONE ! index_num = 289
DONE ! index_num = 290
DONE ! index_num = 291
DONE ! index_num = 292
DONE ! index_num = 293
DONE ! index_num = 294
DONE ! index_num = 295
DONE ! index_num = 296
DONE ! index_num = 297
DONE ! index_num = 298
DONE ! index_num = 299
DONE ! index_num = 300
DONE ! index_num = 301
DONE ! index_num = 302
DONE ! index_num = 303
DONE ! index_num = 304
DONE ! index_num = 305
DONE ! index_num = 306
DONE ! index_num = 307
DONE ! index_num = 308
DONE ! index_num = 309
DONE ! index_num = 310
DONE ! index_num = 311
DONE ! index_num = 312
DONE ! index_num = 313
DONE ! index_num = 314
DONE ! index_num = 315
DONE ! index_num = 316
DONE ! index_num = 317
DONE ! index_num = 318
DONE ! index_num = 319
DONE ! index_num = 320
DONE ! index_num = 321
DONE ! index_num = 322
DONE ! index_num = 323
DONE ! index_num = 324
DONE ! index_num = 325
DONE ! index_num = 326
DONE ! index_num = 327
DONE ! index_num = 328
DONE ! index_num = 329
DONE ! index_num = 330
DONE ! index_num = 331
DONE ! index_num = 332
DONE ! index_num = 333
DONE ! index_num = 334
DONE ! index_num = 335
DONE ! index_num = 336
DONE ! index_num = 337
DONE ! index_num = 338
DONE ! index_num = 339
DONE ! index_num = 340
DONE ! index_num = 341
DONE ! index_num = 342
DONE ! index_num = 343
DONE ! index_num = 344
DONE ! index_num = 345
DONE ! index_num = 346
DONE ! index_num = 347
DONE ! index_num = 348
DONE ! index_num = 349
DONE ! index_num = 350
DONE ! index_num = 351
DONE ! index_num = 352
DONE ! index_num = 353
DONE ! index_num = 354
DONE ! index_num = 355
DONE ! index_num = 356
DONE ! index_num = 357
DONE ! index_num = 358
DONE ! index_num = 359
DONE ! index_num = 360
DONE ! index_num = 361
DONE ! index_num = 362
DONE ! index_num = 363
DONE ! index_num = 364
DONE ! index_num = 365
DONE ! index_num = 366
DONE ! index_num = 367
DONE ! index_num = 368
DONE ! index_num = 369
DONE ! index_num = 370
DONE ! index_num = 371
DONE ! index_num = 372
DONE ! index_num = 373
DONE ! index_num = 374
DONE ! index_num = 375
DONE ! index_num = 376
DONE ! index_num = 377
DONE ! index_num = 378
DONE ! index_num = 379
DONE ! index_num = 380
DONE ! index_num = 381
DONE ! index_num = 382
DONE ! index_num = 383
DONE ! index_num = 384
DONE ! index_num = 385
DONE ! index_num = 386
DONE ! index_num = 387
DONE ! index_num = 388
DONE ! index_num = 389
DONE ! index_num = 390
DONE ! index_num = 391
DONE ! index_num = 392
DONE ! index_num = 393
DONE ! index_num = 394
DONE ! index_num = 395
DONE ! index_num = 396
DONE ! index_num = 397
DONE ! index_num = 398
DONE ! index_num = 399
DONE ! index_num = 400
DONE ! index_num = 401
DONE ! index_num = 402
DONE ! index_num = 403
DONE ! index_num = 404
DONE ! index_num = 405
DONE ! index_num = 406
DONE ! index_num = 407
DONE ! index_num = 408
DONE ! index_num = 409
DONE ! index_num = 410
DONE ! index_num = 411
DONE ! index_num = 412
DONE ! index_num = 413
DONE ! index_num = 414
DONE ! index_num = 415
DONE ! index_num = 416
DONE ! index_num = 417
DONE ! index_num = 418
DONE ! index_num = 419
DONE ! index_num = 420
DONE ! index_num = 421
DONE ! index_num = 422
DONE ! index_num = 423
DONE ! index_num = 424
DONE ! index_num = 425
DONE ! index_num = 426
DONE ! index_num = 427
DONE ! index_num = 428
DONE ! index_num = 429
DONE ! index_num = 430
DONE ! index_num = 431
DONE ! index_num = 432
DONE ! index_num = 433
DONE ! index_num = 434
DONE ! index_num = 435
DONE ! index_num = 436
DONE ! index_num = 437
DONE ! index_num = 438
DONE ! index_num = 439
DONE ! index_num = 440
DONE ! index_num = 441
DONE ! index_num = 442
DONE ! index_num = 443
DONE ! index_num = 444
DONE ! index_num = 445
DONE ! index_num = 446
DONE ! index_num = 447
DONE ! index_num = 448
DONE ! index_num = 449
DONE ! index_num = 450
DONE ! index_num = 451
DONE ! index_num = 452
DONE ! index_num = 453
DONE ! index_num = 454
DONE ! index_num = 455
DONE ! index_num = 456
DONE ! index_num = 457
DONE ! index_num = 458
DONE ! index_num = 459
DONE ! index_num = 460
DONE ! index_num = 461
DONE ! index_num = 462
DONE ! index_num = 463
DONE ! index_num = 464
DONE ! index_num = 465
DONE ! index_num = 466
DONE ! index_num = 467
DONE ! index_num = 468
DONE ! index_num = 469
DONE ! index_num = 470
DONE ! index_num = 471
DONE ! index_num = 472
DONE ! index_num = 473
DONE ! index_num = 474
DONE ! index_num = 475
DONE ! index_num = 476
DONE ! index_num = 477
DONE ! index_num = 478
DONE ! index_num = 479
DONE ! index_num = 480
DONE ! index_num = 481
DONE ! index_num = 482
DONE ! index_num = 483
DONE ! index_num = 484
DONE ! index_num = 485
DONE ! index_num = 486
DONE ! index_num = 487
DONE ! index_num = 488
DONE ! index_num = 489
DONE ! index_num = 490
DONE ! index_num = 491
DONE ! index_num = 492
DONE ! index_num = 493
DONE ! index_num = 494
DONE ! index_num = 495
DONE ! index_num = 496
DONE ! index_num = 497
DONE ! index_num = 498
DONE ! index_num = 499
DONE ! index_num = 500
DONE ! index_num = 501
DONE ! index_num = 502
DONE ! index_num = 503
DONE ! index_num = 504
DONE ! index_num = 505
DONE ! index_num = 506
DONE ! index_num = 507
DONE ! index_num = 508
DONE ! index_num = 509
DONE ! index_num = 510
DONE ! index_num = 511
DONE ! index_num = 512
DONE ! index_num = 513
DONE ! index_num = 514
DONE ! index_num = 515
DONE ! index_num = 516
DONE ! index_num = 517
DONE ! index_num = 518
DONE ! index_num = 519
DONE ! index_num = 520
DONE ! index_num = 521
DONE ! index_num = 522
DONE ! index_num = 523
DONE ! index_num = 524
DONE ! index_num = 525
DONE ! index_num = 526
DONE ! index_num = 527
DONE ! index_num = 528
DONE ! index_num = 529
DONE ! index_num = 530
DONE ! index_num = 531
DONE ! index_num = 532
DONE ! index_num = 533
DONE ! index_num = 534
DONE ! index_num = 535
DONE ! index_num = 536
DONE ! index_num = 537
DONE ! index_num = 538
DONE ! index_num = 539
DONE ! index_num = 540
DONE ! index_num = 541
DONE ! index_num = 542
DONE ! index_num = 543
DONE ! index_num = 544
DONE ! index_num = 545
DONE ! index_num = 546
DONE ! index_num = 547
DONE ! index_num = 548
DONE ! index_num = 549
DONE ! index_num = 550
DONE ! index_num = 551
DONE ! index_num = 552
DONE ! index_num = 553
DONE ! index_num = 554
DONE ! index_num = 555
DONE ! index_num = 556
DONE ! index_num = 557
DONE ! index_num = 558
DONE ! index_num = 559
DONE ! index_num = 560
DONE ! index_num = 561
DONE ! index_num = 562
DONE ! index_num = 563
DONE ! index_num = 564
DONE ! index_num = 565
DONE ! index_num = 566
DONE ! index_num = 567
DONE ! index_num = 568
DONE ! index_num = 569
DONE ! index_num = 570
DONE ! index_num = 571
DONE ! index_num = 572
DONE ! index_num = 573
DONE ! index_num = 574
DONE ! index_num = 575
DONE ! index_num = 576
DONE ! index_num = 577
DONE ! index_num = 578
DONE ! index_num = 579
DONE ! index_num = 580
DONE ! index_num = 581
DONE ! index_num = 582
DONE ! index_num = 583
DONE ! index_num = 584
DONE ! index_num = 585
DONE ! index_num = 586
DONE ! index_num = 587
DONE ! index_num = 588
DONE ! index_num = 589
DONE ! index_num = 590
DONE ! index_num = 591
DONE ! index_num = 592
DONE ! index_num = 593
DONE ! index_num = 594
DONE ! index_num = 595
DONE ! index_num = 596
DONE ! index_num = 597
DONE ! index_num = 598
DONE ! index_num = 599
DONE ! index_num = 600
DONE ! index_num = 601
DONE ! index_num = 602
DONE ! index_num = 603
DONE ! index_num = 604
DONE ! index_num = 605
DONE ! index_num = 606
DONE ! index_num = 607
DONE ! index_num = 608
DONE ! index_num = 609
DONE ! index_num = 610
DONE ! index_num = 611
DONE ! index_num = 612
DONE ! index_num = 613
DONE ! index_num = 614
DONE ! index_num = 615
DONE ! index_num = 616
DONE ! index_num = 617
DONE ! index_num = 618
DONE ! index_num = 619
DONE ! index_num = 620
DONE ! index_num = 621
DONE ! index_num = 622
DONE ! index_num = 623
DONE ! index_num = 624
DONE ! index_num = 625
DONE ! index_num = 626
DONE ! index_num = 627
DONE ! index_num = 628
DONE ! index_num = 629
DONE ! index_num = 630
DONE ! index_num = 631
DONE ! index_num = 632
DONE ! index_num = 633
DONE ! index_num = 634
DONE ! index_num = 635
DONE ! index_num = 636
DONE ! index_num = 637
DONE ! index_num = 638
DONE ! index_num = 639
DONE ! index_num = 640
DONE ! index_num = 641
DONE ! index_num = 642
DONE ! index_num = 643
DONE ! index_num = 644
DONE ! index_num = 645
DONE ! index_num = 646
DONE ! index_num = 647
DONE ! index_num = 648
DONE ! index_num = 649
DONE ! index_num = 650
DONE ! index_num = 651
DONE ! index_num = 652
DONE ! index_num = 653
DONE ! index_num = 654
DONE ! index_num = 655
DONE ! index_num = 656
DONE ! index_num = 657
DONE ! index_num = 658
DONE ! index_num = 659
DONE ! index_num = 660
DONE ! index_num = 661
DONE ! index_num = 662
DONE ! index_num = 663
DONE ! index_num = 664
DONE ! index_num = 665
DONE ! index_num = 666
DONE ! index_num = 667
DONE ! index_num = 668
DONE ! index_num = 669
DONE ! index_num = 670
DONE ! index_num = 671
DONE ! index_num = 672
DONE ! index_num = 673
DONE ! index_num = 674
DONE ! index_num = 675
DONE ! index_num = 676
DONE ! index_num = 677
DONE ! index_num = 678
DONE ! index_num = 679
DONE ! index_num = 680
DONE ! index_num = 681
DONE ! index_num = 682
DONE ! index_num = 683
DONE ! index_num = 684
DONE ! index_num = 685
DONE ! index_num = 686
DONE ! index_num = 687
DONE ! index_num = 688
DONE ! index_num = 689
DONE ! index_num = 690
DONE ! index_num = 691
DONE ! index_num = 692
DONE ! index_num = 693
DONE ! index_num = 694
DONE ! index_num = 695
DONE ! index_num = 696
DONE ! index_num = 697
DONE ! index_num = 698
DONE ! index_num = 699
DONE ! index_num = 700
DONE ! index_num = 701
DONE ! index_num = 702
DONE ! index_num = 703
DONE ! index_num = 704
DONE ! index_num = 705
DONE ! index_num = 706
DONE ! index_num = 707
DONE ! index_num = 708
DONE ! index_num = 709
DONE ! index_num = 710
DONE ! index_num = 711
DONE ! index_num = 712
DONE ! index_num = 713
DONE ! index_num = 714
DONE ! index_num = 715
DONE ! index_num = 716
DONE ! index_num = 717
DONE ! index_num = 718
DONE ! index_num = 719
DONE ! index_num = 720
DONE ! index_num = 721
DONE ! index_num = 722
DONE ! index_num = 723
DONE ! index_num = 724
DONE ! index_num = 725
DONE ! index_num = 726
DONE ! index_num = 727
DONE ! index_num = 728
DONE ! index_num = 729
DONE ! index_num = 730
DONE ! index_num = 731
DONE ! index_num = 732
DONE ! index_num = 733
DONE ! index_num = 734
DONE ! index_num = 735
DONE ! index_num = 736
DONE ! index_num = 737
DONE ! index_num = 738
DONE ! index_num = 739
DONE ! index_num = 740
DONE ! index_num = 741
DONE ! index_num = 742
DONE ! index_num = 743
DONE ! index_num = 744
DONE ! index_num = 745
DONE ! index_num = 746
DONE ! index_num = 747
DONE ! index_num = 748
DONE ! index_num = 749
DONE ! index_num = 750
DONE ! index_num = 751
DONE ! index_num = 752
DONE ! index_num = 753
DONE ! index_num = 754
DONE ! index_num = 755
DONE ! index_num = 756
DONE ! index_num = 757
DONE ! index_num = 758
DONE ! index_num = 759
DONE ! index_num = 760
DONE ! index_num = 761
DONE ! index_num = 762
DONE ! index_num = 763
DONE ! index_num = 764
DONE ! index_num = 765
DONE ! index_num = 766
DONE ! index_num = 767
DONE ! index_num = 768
DONE ! index_num = 769
DONE ! index_num = 770
DONE ! index_num = 771
DONE ! index_num = 772
DONE ! index_num = 773
DONE ! index_num = 774
DONE ! index_num = 775
DONE ! index_num = 776
DONE ! index_num = 777
DONE ! index_num = 778
DONE ! index_num = 779
DONE ! index_num = 780
DONE ! index_num = 781
DONE ! index_num = 782
DONE ! index_num = 783
DONE ! index_num = 784
DONE ! index_num = 785
DONE ! index_num = 786
DONE ! index_num = 787
DONE ! index_num = 788
DONE ! index_num = 789
DONE ! index_num = 790
DONE ! index_num = 791
DONE ! index_num = 792
DONE ! index_num = 793
DONE ! index_num = 794
DONE ! index_num = 795
DONE ! index_num = 796
DONE ! index_num = 797
DONE ! index_num = 798
DONE ! index_num = 799
DONE ! index_num = 800
DONE ! index_num = 801
DONE ! index_num = 802
DONE ! index_num = 803
DONE ! index_num = 804
DONE ! index_num = 805
DONE ! index_num = 806
DONE ! index_num = 807
DONE ! index_num = 808
DONE ! index_num = 809
DONE ! index_num = 810
DONE ! index_num = 811
DONE ! index_num = 812
DONE ! index_num = 813
DONE ! index_num = 814
DONE ! index_num = 815
DONE ! index_num = 816
DONE ! index_num = 817
DONE ! index_num = 818
DONE ! index_num = 819
DONE ! index_num = 820
DONE ! index_num = 821
DONE ! index_num = 822
DONE ! index_num = 823
DONE ! index_num = 824
DONE ! index_num = 825
DONE ! index_num = 826
DONE ! index_num = 827
DONE ! index_num = 828
DONE ! index_num = 829
DONE ! index_num = 830
DONE ! index_num = 831
DONE ! index_num = 832
DONE ! index_num = 833
DONE ! index_num = 834
DONE ! index_num = 835
DONE ! index_num = 836
DONE ! index_num = 837
DONE ! index_num = 838
DONE ! index_num = 839
DONE ! index_num = 840
DONE ! index_num = 841
DONE ! index_num = 842
DONE ! index_num = 843
DONE ! index_num = 844
DONE ! index_num = 845
DONE ! index_num = 846
DONE ! index_num = 847
DONE ! index_num = 848
DONE ! index_num = 849
DONE ! index_num = 850
DONE ! index_num = 851
DONE ! index_num = 852
DONE ! index_num = 853
DONE ! index_num = 854
DONE ! index_num = 855
DONE ! index_num = 856
DONE ! index_num = 857
DONE ! index_num = 858
DONE ! index_num = 859
DONE ! index_num = 860
DONE ! index_num = 861
DONE ! index_num = 862
DONE ! index_num = 863
DONE ! index_num = 864
DONE ! index_num = 865
DONE ! index_num = 866
DONE ! index_num = 867
DONE ! index_num = 868
DONE ! index_num = 869
DONE ! index_num = 870
DONE ! index_num = 871
DONE ! index_num = 872
DONE ! index_num = 873

In [11]:
#(2) 값 추가하기.
RANDOM_POINT_no_HGD['자치구']      = RANDOM_POINT_no_HGD_자치구
RANDOM_POINT_no_HGD['행정동_코드'] = RANDOM_POINT_no_HGD_행정동_코드

#(5) 처리 결과 확인하기. 
RANDOM_POINT_no_HGD

,rand_point,SGG_NM,geometry,위도,경도,자치구,행정동_코드
0,0,금천구,POINT (126.9134055885386 37.44996180218595),37.449962,126.913406,금천구,1154568000
1,1,금천구,POINT (126.9143943524618 37.44996374526017),37.449964,126.914394,금천구,1154568000
2,2,금천구,POINT (126.9142583604479 37.44993860398068),37.449939,126.914258,금천구,1154568000
3,3,금천구,POINT (126.9132887655418 37.44995610565504),37.449956,126.913289,금천구,1154568000
4,4,금천구,POINT (126.9136375368365 37.45000822498514),37.450008,126.913638,금천구,1154568000
...,...,...,...,...,...,...,...
40286,41191,동작구,POINT (126.9536105492901 37.49994690939378),37.499947,126.953611,동작구,1159053000
40287,41192,동작구,POINT (126.9536832343939 37.50027154889482),37.500272,126.953683,동작구,1159053000
40288,41193,동작구,POINT (126.9537327787121 37.50010520158163),37.500105,126.953733,동작구,1159053000
40289,41194,동작구,POINT (126.9537081199655 37.50054022273152),37.500540,126.953708,동작구,1159053000
40290,41195,동작구,POINT (126.9535831660898 37.4998261925987),37.499826,126.953583,동작구,1159053000

In [13]:
#(6) 처리 결과 저장하기. 
RANDOM_POINT_no_HGD.to_excel('temp_file.xlsx', index=False)